### ISSUE TITLE
CF 1.6 Chapter 5 - Checking Coordinate Attribute

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#100]
Compliance checker should check the "coordinates" attribute for geophysical data variables and verify that each coordinate variable in the space delimited list is a coordinate variable.

Note: this is optionally recommended by Chapter 5

> The use of coordinate variables is required whenever they are applicable. That
> is, auxiliary coordinate variables may not be used as the only way to identify
> latitude and longitude coordinates that could be identified using coordinate
> variables. This is both to enhance conformance to COARDS and to facilitate the
> use of generic applications that recognize the NUG convention for coordinate
> variables. An application that is trying to find the latitude coordinate of a
> variable should always look first to see if any of the variable's dimensions
> correspond to a latitude coordinate variable. If the latitude coordinate is not
> found this way, then the auxiliary coordinate variables listed by the
> coordinates attribute should be checked. Note that it is permissible, but
> optional, to list coordinate variables as well as auxiliary coordinate
> variables in the coordinates attribute.

**Comment by kknee** [comment]
solved as of release 2.0

**Comment by daf** [comment]
Can we link this to a commit that demonstrates fixing?

**Comment by lukecampbell** [comment]
I can't pinpoint the specific commit, I think it happened over several different changes. The best I could maybe do is write a test that verifies this and tag that here?

**Comment by daf** [comment]
Yeah that's probably even better.

**Comment by lukecampbell** [comment]
I do recall that this was fixed around the time I was troubleshooting the recursive `coordinates` issues though. I'll try to add a test.

**Comment by DanielJMaher** [comment]
@daf @lukecampbell What's the call here guys?  AM i just writing a test to prove that it works, or should I dive in a bit and find the commit?

**Comment by lukecampbell** [comment]
here
https://github.com/ioos/compliance-checker/pull/219
