### ISSUE TITLE
Create a Compliance Checker docs site at https://ioos.github.io/compliance-checker

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#1006]
Currently, we have user documentation for Compliance Checker in two places:

* GitHub Readme: https://github.com/ioos/compliance-checker
* Website: https://compliance.ioos.us/about
* CC Wiki: https://github.com/ioos/compliance-checker/wiki

To improve usability and consistency between this library and other IOOS libraries, can we create a user documentation site for Compliance Checker that includes content from both of the above and perhaps builds out additional dataset/use case examples?

For reference, the menu bar at the top of https://ioos.github.io/, when updated tomorrow (Apr 11), will include links to other IOOS libraries with Sphinx docs (erddap, ioos_qc).  Unless there's a reason not to, let's aim to be consistent and develop Sphinx-based docs for Compliance Checker, and once finished, trim the content in the README accordingly.  

Ideas for improving docs:
* we could consider asking users to contribute datasets they've used CC with to develop examples from
* have an unfamiliar but Python-literate user(s) work though the existing docs and point out issues, suggest gaps to fill, or give any other suggestions

xref to discussion of menu bar changes at ioos.github.io: https://github.com/ioos/documentation-theme-jekyll/issues/10#issuecomment-1501962377

**Comment by mwengren** [comment]
Also, there is some documentation in the [CC Wiki](https://github.com/ioos/compliance-checker/wiki) that should be migrated into the resulting Sphinx-based overall CC project docs.

**Comment by ocefpaf** [comment]
I started the API docs in https://github.com/ioos/compliance-checker/pull/1007

**Comment by ocefpaf** [comment]
@mwengren the docs are live! We still need to improve it's readability, add examples, and development docs but the API part is done.

**Comment by ocefpaf** [comment]
I think we can close this one and open a new one with points on improving the docs.
