### ISSUE TITLE
Fix compliance checker integration tests

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#1012]
**Version of compliance checker running:**

Current `master` and `development` branches as of time of this writing.

**Describe the checker this affects:**
N/A
**Attach a minimal CDL or NetCDF file which is able to reproduce the issue**

**To Reproduce:**
_List the steps or command line to run to reproduce the issue_
Run integration tests

**Describe the issue below:**
_Any additional detail or information relevant to the issue_
Several links used for the integration tests are broken, causing tests to fail.  Special attention should be paid to finding an SOS service which will continue to be maintained in the long term.

**Comment by ocefpaf** [comment]
@benjwadams I believe this one was addressed, right?

**Comment by benjwadams** [comment]
Yes, integration tests are all passing now in addition to all other CI checks.   Closing.
