### ISSUE TITLE
OGC: OG-1.0

### ISSUE THREAD

**Issue by jcermauwedu** [ioos/compliance-checker#1055]
It looks like the OGC group is considering a [checker](https://github.com/OceanGlidersCommunity/OG-format-user-manual/discussions/165).  Is this going to be a separate tool, or should it be a consideration here?

**Comment by benjwadams** [comment]
We'll definitely consider it as it's a target for the IOOS Glider DAC in the near future.  However, recent CF versions are not yet supported.

cc: @kerfoot @mwengren

**Comment by jcermauwedu** [comment]
A plugin [repo](https://github.com/uw-farlab/cc-plugin-og) has been established and can be moved into the IOOS repository when ready.
