### ISSUE TITLE
Latest release 5.1.1 not available on PyPI

### ISSUE THREAD

**Issue by SpacemanPaul** [ioos/compliance-checker#1085]
Github reports the latest release of compliance-checker as 5.1.1 (released 2024-04-17)

PyPI reports the latest available release of compliance-checker as 5.1.0 (released 2023-05-18).
https://github.com/ioos/compliance-checker/releases

https://pypi.org/project/compliance-checker/#history

**Comment by ocefpaf** [comment]
I'll fix this later today. Something is broken in our PyPI GHA.

**Comment by ocefpaf** [comment]
Done: https://pypi.org/project/compliance-checker/5.1.1/

Thanks for reporting.
