### ISSUE TITLE
Error while processing the job

### ISSUE THREAD

**Issue by edesfandiari** [ioos/compliance-checker#1086]
**Version of compliance checker running:**

**Describe the checker this affects:**
_The ACDD, IOOS, and CF checkers are currently considered in scope for the purposes of the issue tracking on this repository. Issues with other plugins should be placed into their respective repositories._

**Attach a minimal CDL or NetCDF file which is able to reproduce the issue**

**To Reproduce:**
_List the steps or command line to run to reproduce the issue_

**Describe the issue below:**
_Any additional detail or information relevant to the issue_

**Comment by edesfandiari** [comment]
Recently, my attempts to check few short files using CF 1.6, 1.7, or 1.8 keep failing. The .nc files upload 
successfully but they all fail with "Error while processing the job. Job Timed Out" messages! My attempts
even fails for same files that were successfully checked back in February. I'm using Linux RedHat and
have the same issue using both Chrome and FireFox.

Also, the 'feedback'  does not function either. Sending a note results in
=>
compliance.ioos.us says
An Error has Occurred

**Comment by edesfandiari** [comment]
Note - The uploaded file
GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.csv
is actually the same duplicate copy of
GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.nc.csv

**Comment by benjwadams** [comment]
Well, for one thing, Compliance Checker doesn't work on CSV currently to the best of my knowledge, even with formatting that IOOS recommends.

**Comment by ocefpaf** [comment]
I assume that was a copy and paste issue b/c the image above shows a different file. If you can share that file we can try to help you debug it.

**Comment by edesfandiari** [comment]
The uploaded file was a netcdf file. I used the "Paste, drop, or click to add files"  at the bottom of the
page to do my uploads. But, the .nc[4] is not among the allowed options. Therefore, I added a 
dummy .csv extension to my file to be able to upload it. However, I just noticed the attach option 
on top of the page and was able to upload my .nc4 file. As mentioned before, the CF checker 
times out for all netcdf and hdf files. I also asked a colleague to try it and he had the same issue.

**Comment by edesfandiari** [comment]
I'm sorry but I can't attache any of my .nc, .nc4, .hdf. or .cdl files. I keep getting "We don't support that file type"
as seen in this upload_options.png screenshot.
![upload_options](https://github.com/ioos/compliance-checker/assets/100610812/f07876c6-7b86-464d-a794-4de225d9a172)

**Comment by edesfandiari** [comment]
As suggested, I also opened this issue, yesterday:
https://github.com/ioos/compliance-checker-web/issues/121

**Comment by edesfandiari** [comment]
sure. Here it is.
[GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.zip](https://github.com/ioos/compliance-checker/files/15487743/GiOCEAN_e1.aci_tavg_1dy_glo_L360x181_p27.19980201_1200z.nc4.zip)

**Comment by ocefpaf** [comment]
> Yes, that is correct. As previously stated, I've been using the online https://compliance.ioos.us/index.html

@edesfandiari we needed to be sure that it was not the file first and it seems you did not try the CLI, right?

Let's move this discussion to https://github.com/ioos/compliance-checker-web/issues/121 b/c here is nothing wrong with the code here.

**Comment by edesfandiari** [comment]
Correct, I have always used the online version and never the CLI.
