### ISSUE TITLE
Unrecognized standard name for "concentration_of_colored_dissolved_organic_matter_in_sea_water_expressed_as_equivalent_mass_fraction_of_quinine_sulfate_dihydrate"

### ISSUE THREAD

**Issue by fgayanilo** [ioos/compliance-checker#1105]
**Version of compliance checker running:**
Online and client based

**Describe the checker this affects:**
CF compliance checkers 

**To Reproduce:**
Check with CF 1.7 and the standard name "concentration_of_colored_dissolved_organic_matter_in_sea_water_expressed_as_equivalent_mass_fraction_of_quinine_sulfate_dihydrate" is not recognized

**Describe the issue below:**
the checker returns an error

**Comment by benjwadams** [comment]
From the CLI version of Compliance Checker, have you tried the `-d latest` option?  It should try to fetch the most recent CF Standard Name data, and this may solve your problem.  By default compliance checker does not try to immediately fetch the latest standard name table, this might be a misfeature that we attempt to turn on by default in the future.

**Comment by benjwadams** [comment]
Please submit CDL or NetCDF file.
