### ISSUE TITLE
NODC Compliance Checker

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#115]
A lot of the IOOS projects make submissions to NODC for Archival, here's the NODC template.

I'd like to get this as a compliance checker test. It's basically ACDD but with some twists of CF.

http://www.nodc.noaa.gov/data/formats/netcdf/v1.1/

**Comment by daf** [comment]
Seems like a good candidate for the plugin based thing I need to complete for #60 / #99.  Or maybe it's a core check?

**Comment by lukecampbell** [comment]
I feel like all of the tests are candidates for plugins.

**Comment by daf** [comment]
IMO CF and probably ACDD should be core ones.

**Comment by mbiddle-nodc** [comment]
Just an FYI, now that NODC is NCEI, so all references to NODC will be changing to NCEI. If your thinking of adding a plugin I would reference NODC as NCEI. I will discuss this internally and report back to make sure I am relaying the information correctly.

Another note, if the checker already validates against CF and ACDD, the only addition for the "NODC" check would be specific attributes/variables that we recommend. For example:
uuid
platform
instrument
sea_name
nodc_name
nodc_template_version

Our templates were fundamentally based on CF and ACDD. Your checker should already be doing most of the heavy lifting here.

**Comment by lukecampbell** [comment]
This is being satisfied in a project as a plugin https://github.com/ioos/cc-plugin-ncei/
