### ISSUE TITLE
Remove references to udunits from docs

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#120]
README, ubuntu install guide, and various comments in code still refer to udunits and trouble surrounding it.

As of #114 we no longer use udunits, so these need to be removed.

**Comment by lukecampbell** [comment]
I think technically we still use udunits, we just don't use udunitspy.

**Comment by daf** [comment]
I got those confused a bit this afternoon, but same applies for udunitspy,
still reffed plenty.

**Comment by DanielJMaher** [comment]
@daf After reviewing this, really only the ubuntu-install-guide and teh README.md should be changed.  The other references to udunits are direct quotes from the CF 1.6 document and udunitspy isn't mentioned anywhere but those two files. 

Is it alright if I just remove from those files?

**Comment by daf** [comment]
Yes, that's what's needed.

**Comment by DanielJMaher** [comment]
@daf i confused myself.  Check all that apply:

[ ] Remove reference to udunits
[ ] Remove reference to udunitspy

**Comment by daf** [comment]
- [x] udunitspy
