### ISSUE TITLE
Contributor Name and Contributor Role Checks

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#122]
Just some basic syntax checks to make sure the contributor names are comma separated and that the roles are also comma separated. Also that each name has an associated role.

**Comment by kknee** [comment]
This is for CF and ACDD

**Comment by DanielJMaher** [comment]
This is going to be kind of tricky.  These are all rational ways to include my name as a contributor:

Daniel Maher
DMaher
D. Maher
Daniel James Maher
Maher, Daniel
Maher, Daniel, James

We need to either make a standard or we are going to have a lot of incredibly awkward edge cases.

**Comment by DanielJMaher** [comment]
Here is an ipython notebook that I created that will be the basis of the code.  Mind taking a look at the assumptions and logic @lukecampbell and @daf ??

Also, please look at the first line of unique_names?  I think there is a better way to do it.

I am changing it to a .zip  so that it loads, but download it and turn it back into a .ipynb

[Name_Checker.zip](https://github.com/ioos/compliance-checker/files/158836/Name_Checker.zip)

**Comment by daf** [comment]
Dude.  Use gist.github.com, especially for ipynb, which github will happily render for you in browser.

Second, I'm not sure how you can enforce "comma separation" of names when given so many different naming customs exists in different cultures (try putting a spanish or portuguese name in), you'll have no way of figuring out when one name stops and and another begins.  If the original author of the file doesn't comma separate, I'm not sure you can do much other than say "number of contributors: 1" which isn't even in the purview of CF/ACDD afaik.

I think all you can really do is make sure the cardinality of comma-separated fields in names and roles lines up, and if it doesn't, purport a failure.

**Comment by DanielJMaher** [comment]
@daf How do i do that for ipython notebook

**Comment by daf** [comment]
Drag and drop an ipynb file on gist.github.com

**Comment by DanielJMaher** [comment]
https://gist.github.com/DanielJMaher/0558880f3e0ca199aefa

**Comment by ocefpaf** [comment]
There is also an extension, [`gistit`](https://github.com/minrk/ipython_extensions/tree/master/nbextensions), that adds a button to your Jupyter notebooks to send/update gists.

**Comment by DanielJMaher** [comment]
i did my best to update this without spending too much time.  All i did was add in additional words for "and" in multiple languages and better allowed for the oxford comma which is prevalent in some languages, but not others.  

https://gist.github.com/DanielJMaher/70d73566b61c0e85a395

**Comment by daf** [comment]
By different languages, I meant different culture naming possibilities.  See [Spanish Naming Customs](https://en.wikipedia.org/wiki/Spanish_naming_customs), [Portuguese Naming Customs](https://en.wikipedia.org/wiki/Portuguese_name).  Take for instance these famous footballers:

- Cristiano Ronaldo dos Santos Aveiro
- Ronaldo Luís Nazário de Lima

And these other randomly sampled full names:
- José Antonio Gómez Iglesias
- Filipe Pires Alvarenga Fernandes (hi @ocefpaf !)
- [Bandar bin Abdulaziz Al Saud](https://en.wikipedia.org/wiki/Bandar_bin_Abdulaziz_Al_Saud)

From what I gather, none of these names would pass any testing done ("Too long", "Capitalization") and what not.  It's an impossible task to try and write a name parser in the first place, and this check certainly doesn't need it.  All we should be doing is checking the number of commas that appear, and making sure if a value for role is specified, the same number of commas should appear (therefore a role is associated with every name).  If not, report an issue.  There is really nothing else you can do.

**Comment by DanielJMaher** [comment]
"Wont fix" -- Luke
