### ISSUE TITLE
Unnecessary data shuffling in CF check_packed_data

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#128]
While investigating the causes of issue #70 (slow-running checker for large files) @fxmzb123 found that the `check_packed_data` method (in CF suite) was responsible for a lot of the running time. The current implementation calls `numpy.reshape` on each variable 5 times, which can be pretty slow for large multi-dimensional arrays. This could certainly be optimised by doing the reshape only once for a variable.

Going further, I think that reshaping data arrays is actually unnecessary here. The CF convention only refers to the data types of the variable itself, and some of its attributes. Surely these can be determined without manipulating the entire array.

**Comment by mhidas** [comment]
To be a bit more specific, for a NetCDF object, each variable has an attribute `var.dtype` (the type of the values stored in the file), and this needs to be compared to `var.add_offset.dtype` and `var.scale_factor.dtype`.

**Comment by mhidas** [comment]
The [CF convention](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#packed-data) also specifies that the types of the variable attributes _FillValue, valid_min, valid_max, valid_range (when they exist) should also be the same as `var.dtype`. This is currently not implemented.

**Comment by daf** [comment]
See #129
