### ISSUE TITLE
CF check_units should not skip scalar variables

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#130]
In cf.py `check_units` requires variables to have a *units* attribute, with some exceptions. Currently one of the exceptions is any variable with `v.shape == ()`, i.e. scalar variables. This seems wrong to me. [CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#units) says "Units are not required for dimensionless *quantities*". This refers to the physical quantity being stored, not the number of values or their (lack of) association with any dimension in the file.

For example, in a file containing a single timeseries, we may store the location in dimensionless variables, and these should have units.

**Comment by daf** [comment]
Fixed in #177
