### ISSUE TITLE
Come up with checker versioning scheme

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#133]
So that other versions of say ACDD (1.2, 1.3) or CF (1.6, 2.x?!) can be checked using this software.  Extends #127

**Comment by mhidas** [comment]
This would also be very useful for IMOS.

**Comment by lukecampbell** [comment]
Any ideas? Like in the modules or something we'll need checkers for different versions. I'm frankly ok with like "acdd11.py" That's how OWSLib did it.

**Comment by mhidas** [comment]
@lukecampbell Given that a new version of a given convention will likely only update a fraction of its rules, it might be easiest to have the checker for the newer version to be subclass of the older one?

In terms of command-line interface, it would be good to be nice to have options, e.g.
 * `cchecker.py -t=cf-16 file.nc` to specify CF-1.6
 * `cchecker.py -t=cf file.nc` to use the latest version by default, or
 * choose the version specified in the `Conventions` global attribute.

**Comment by lukecampbell** [comment]
:+1:

**Comment by kknee** [comment]
Now that we're supporting plug-ins, do we need to worry about this?  Can we not just have an ACDD 1.2 plug-in, ACDD 1.3 plug-in, etc?

**Comment by daf** [comment]
That would mean we'd have to move the "core" checkers (ACDD/CF) out of the main package, which feels wrong - should come with some built in.

The only mechanism we'd have to distinguish with now is plugin name.  A "version" key would be good to have too as another first-order property.  (Version is likely not a good name to use as it implies software version, not spec version)

**Comment by lukecampbell** [comment]
for acdd and cf, I propose we just have modules named "cf17" and "acdd13".

**Comment by kknee** [comment]
that's what I was thinking, and was not trying to indicate that they would be coming out of the main CC package.

**Comment by daf** [comment]
Perhaps rename `cf -> cf16` and `acdd -> acdd12`, with an alias `cf` meaning latest?  Maybe a docker-like label scheme?  `cf:1.6`, `cf:1.7`, `cf:latest` with `:latest` implied if omitted?

**Comment by mhidas** [comment]
:+1:

**Comment by daf** [comment]
@kwilcox has suggested a way to run more than one from a "family", maybe a special token like `cf:all` or `cf:*`?  Maybe comma separated?  `cf:1.6,1.7`?

**Comment by kwilcox** [comment]
Once the checkers all implement `_cc_spec` and _cc_spec_version` attributes, how much effort to integrate this so we can just run `cf` checks and get output from all of them found?

**Comment by lukecampbell** [comment]
should be pretty easy, I would think. We'll need to tweak the command line args, and the CheckSuite class but should be really easy.

**Comment by DanielJMaher** [comment]
@daf @kwilcox @lukecampbell 

This never actually came to a final resolution.  It appears to be that -t <test>:<tag> is the command line argument  to be used, where <test> will map to the _cc_spec and <tag> will map to _cc_spec_version attributes.  

However, the comma separated/all portion seems odd to me... why would you run checks on 1.6 and 1.7?  I do like the -t cf meaning the most recent.

So this is the plan going forward?  Agreed?

**Comment by benjwadams** [comment]
Related to #186

**Comment by benjwadams** [comment]
Should be implemented now that #262 is merged. Closing.
