### ISSUE TITLE
CF valid units not in UDUNITS

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#137]
The [CF FAQ](http://cfconventions.org/faq.html#udunits_missing)) page says:

> There are two units acceptable to CF that are not in the UDUNITS library: **sverdrup**, and **decibel** or **dB**. These have been requested for inclusion in future versions of the UDUNITS library.

However, the checker only uses UDUNITS (via the cf_units package) to validate units. So currently it will fail for these units.

Is it worth considering a work-around (until these units are added to UDUNITS)?

**Comment by ocefpaf** [comment]
@mhidas Can you open an issue at https://github.com/SciTools/cf_units too?

**Comment by lukecampbell** [comment]
It may not be necessary to change the core library. udunits uses an XML system to define the units, we should be able to include an auxiliary XML definition for these units.

**Comment by lukecampbell** [comment]
https://github.com/ooici/ion-definitions/tree/master/res/config/units

**Comment by ocefpaf** [comment]
@lukecampbell even though it is easy for us to just nudge units in I think we should try to send that upstream (to UDUNITS).  That way all the projects derived from it will have those units. Once I get back home I will try to send a PR [there](https://github.com/Unidata/UDUNITS-2).

**Comment by mhidas** [comment]
@ocefpaf Logged: https://github.com/SciTools/cf_units/issues/30

**Comment by kknee** [comment]
this is a UDUNITS issue, closing
