### ISSUE TITLE
Latest Standard Names Table

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#150]
The current version of standard names table is 29, but we're using 25

**Comment by mbiddle-nodc** [comment]
I would recommend pulling the standard name table version from the file's global attribute "standard_name_vocabulary". See ACDD attribute http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery#standard_name_vocabulary. Then you can test against the appropriate standard name table.

**Comment by kknee** [comment]
this is complete, we're using 29.  @mbiddle-nodc we're not currently maintaining historical table lookups.

**Comment by daf** [comment]
As of b8ec477e6b9a9d8a9bb32f3c86d1b0e82de47069

**Comment by lukecampbell** [comment]
Thanks
