### ISSUE TITLE
Implement a command-line option to output the code version

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#159]
We would like to keep track of which files passed which version of the checker. The simplest way to do that would be if we could just call `cchecker.py --version`, and get back the current release number. Since the code is changing quite a bit between releases, it would also be helpful to include the last change date and commit id. Something like this:
```
IOOS Compliance Checker 1.1.1
Last modified 2015-08-25 at commit f09e5c362d908fe218eb93de71a5c40b76a21a84
```

**Comment by lukecampbell** [comment]
I won't be able to provide the commit id in the version string because it is circularly dependent but I can put the modified date.

**Comment by mhidas** [comment]
@lukecampbell Thanks, that would be helpful.

**Comment by mhidas** [comment]
This was provided in b1af5119
