### ISSUE TITLE
CF check_all_features_are_same_type gives no reasoning

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#169]
For [this file](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ABOS/Pulse/catalog.html?dataset=eMII/checker_test/ABOS/Pulse/IMOS_ABOS-SOTS_W_20150331T130000Z_Pulse_FV00_Pulse-11-MRU-Surface-wave-height-realtime_END-20150813T230000Z_C-20150821T022247ZZ.nc), the CF checker results include:
```
Name                             Priority:     Score:Reasoning
--------------------------------------------------------------------------------
all_features_are_same_type             :3:     0/ 1 :  
```
It would be helpful to provide a bit more detail to explain what "same type" means in this case.

**Comment by lukecampbell** [comment]
I reviewed the code for this and started to make the change but I'm not satisfied with how we're performing this check. I'd like to refactor a lot of the chapter 9 stuff.

**Comment by lukecampbell** [comment]
After merging my changes it will look like this

```
9.1 Feature Types are all the same     :3:     0/ 1 : At least one of the
                                                      variables has a different
                                                      feature type than the rest
                                                      of the variables.,
                                                      ACCEL_AVG(TIME) VAVH(TIME)
                                                      DISP(FREQ, TIME)
                                                      ACCEL_STDDEV(TIME)
```

**Comment by mhidas** [comment]
:+1:
