### ISSUE TITLE
CF check_flags: 'numpy.int8' object is not iterable

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#171]
Running the CF checker on [this file](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/SOOP/ASF/catalog.html?dataset=eMII/checker_test/SOOP/ASF/IMOS_SOOP-ASF_FMT_20150205T000200Z_ZMFR_FV02.nc), we get this exception:

```
cf.check_flags: 'numpy.int8' object is not iterable
```

This is another special case that can probably be considered incorrect according to CF, but in that case it should give a fail result, rather than an exception. The file has flag variables with only a single value in the `flag_values` attribute, rather than a list. [CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#flags) says it should be a list.

**Comment by daf** [comment]
Fixed in 90375ba

**Comment by daf** [comment]
@mhidas after applying your fix and testing on this file, I get a `UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 0: ordinal not in range(128)` when trying to format the results, but that's certainly a separate issue.

**Comment by mhidas** [comment]
@daf I get the same exception from versions before my fix was merged, e.g. try running https://github.com/ioos/compliance-checker/commit/db62cea9e3ba90843ea0961b734077628f444c70 
on the test file compliance_checker/tests/data/bad_region.nc 

There's also several slightly different but similar issues I've been seeing, since #167 was merged (see my comments https://github.com/ioos/compliance-checker/issues/154#issuecomment-147624951)
