### ISSUE TITLE
Pretty names for Checkers

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#186]
As a web developer, I would like to be able to have a list of pretty names for each checker and a detailed description so that I can include the names of the checker in the user interface(s). 

Example:
![screen shot 2015-11-03 at 2 41 56 pm](https://cloud.githubusercontent.com/assets/1155163/10919473/1331ec2c-8239-11e5-82d5-ff97c4b9ce93.png)

**Comment by lukecampbell** [comment]
This is sooooo low priority, it may even just get closed. This is really a presentation issue and as such, it's currently trivial to have the presentation layer (UI) deal with mapping pretty names to the tests, but in the longer scheme of things, it would be nice to be able to dynamically include new plugins, and have the UI automagically update.

**Comment by daf** [comment]
Could see this as additional `__` attributes on each Checker class.

Wants:
- Name
- Description
- URL
- Author
- Version

**Comment by mhidas** [comment]
:+1: :+1: I've been thinking about adding such attributes too. In particular
 * Name and version to be displayed by the `--version` option, and
 * URL (and description) could be added as a footnote to the checker output to point to further information about the conventions being checked.

**Comment by kwilcox** [comment]
How about these for optional attributes on any `Checker` class (with a fallback to something sane implemented in CC).

* `_cc_title`
* `_cc_description`
* `_cc_url`
* `_cc_author`
* `_cc_version`

**Comment by daf** [comment]
Version really has two components - one for spec version (CF **1.6**, ACDD **1.3**) etc, also one for checker internal version (semantic, of course @dpsnowden).  Probably two separate fields.

- `_cc_spec_version`
- `_cc_???_version` ?

**Comment by kwilcox** [comment]
Yes yes yes. I plan to release the `cc-plugin-sgrid` package with the same versions as the spec, but that won't always be the case!

* `_cc_checker_version`
* `_cc_spec_version`

?

**Comment by daf** [comment]
Those names are good.

See also #133 and #127 for similar discussions.  My proposal for a docker-inspired selection mechanism is [here](https://github.com/ioos/compliance-checker/issues/133#issuecomment-171378700).

**Comment by lukecampbell** [comment]
:+1:

**Comment by kwilcox** [comment]
Updated list of specials:

* `_cc_spec`  - `CF`, `ACDD`, `SGRID`. Formatted however, but consistent across all Checkers for this spec type.  CC can use this to group checks of the same spec together. See [this] (https://github.com/ioos/compliance-checker/issues/133#issuecomment-179303034).
* `_cc_spec_version` - Version of the spec: `1.6`, `1.7` for CF.
* `_cc_description`
* `_cc_url`
* `_cc_author`
* `_cc_checker_version` - internal version of the checker code

**Comment by lukecampbell** [comment]
@daf @kwilcox @DanielJMaher 
How do we sit with this?
https://github.com/ioos/cc-plugin-glider/compare/master...lukecampbell:pretty_names

I'd like to do something similar for the other checkers and integrate it into the web version.

**Comment by daf** [comment]
Nearly exactly what I had in mind, two quibbles -

- `_cc_version` should def be unlocked from main CC's version (minor revisions to glider dac plugin will desync this very quickly)
- `_cc_author` maybe rename to authors?  Or just comma separated list of name <email> pairs, the plural-ness of the attribute itself is unlikely to matter.

**Comment by lukecampbell** [comment]
I'm ok with that.

**Comment by lukecampbell** [comment]
Ok, I updated it to `_cc_authors` and then `_cc_checker_version` is set to `2.0.0`

**Comment by lukecampbell** [comment]
Also https://github.com/ioos/compliance-checker/wiki/Compliance-Checker-Meta-Attributes

**Comment by daf** [comment]
Hm - we've either forgotten one, or will repurpose the `_cc_spec` field - the name used to select the checker on the command line!

Building on the work done by @fxmzb123 in 0423657 (lol this sha1), we added a `name` field to all Checkers, and that's what's exposed on the command line.

Do we
- keep `name`
- rename `name` -> `_cc_name`
- use `_cc_spec` INSTEAD of `name`
- ???

**Comment by kwilcox** [comment]
`_cc_spec` won't work if someone just want to run `cf-1.6` checks (the `_cc_spec` would be just `cf`).

We could combine `_cc_spec` and `_cc_spec_version` to get a unique "thing" to run on the command line?

**Comment by daf** [comment]
With the docker-style resolving approach (discussed [here](https://github.com/ioos/compliance-checker/issues/133#issuecomment-171378700)), all you'd need would be `cf` though - possibly case-insensitive.

As long as `:latest` can be inferred by some sort of incremental versioning, semantic or linear...

To your example, if someone wanted to run `cf-1.6`, they could specify `cf:1.6`, `cf:latest`, or `cf`, with CC figuring out that 1.6 is the latest.

(this poses a question about an in development spec though, when does 1.7 become latest?)

**Comment by kwilcox** [comment]
So if I wanted to run all of the `cf` checks, I would do... `cf:all`?

**Comment by daf** [comment]
Yes, see [this](https://github.com/ioos/compliance-checker/issues/133#issuecomment-179303034)

**Comment by kwilcox** [comment]
OK, so :+1: using `_cc_spec` instead of `name`

**Comment by lukecampbell** [comment]
I dig it.

**Comment by benjwadams** [comment]
Why are we advocating `_cc_author` and `_cc_version` variables when individual checkers are already broken up into separate modules and we could use `__author__` and `__version__` respectively instead?  This seems like reinventing the wheel.

**Comment by daf** [comment]
@benjwadams, I'm assuming you're advocating for module-level variables named `__author__` and `__version__`, correct?  Is this a known/preferred spec somewhere?

There's no requirement for them to be broken into individual modules.  Consider smaller specs like ACDD, might be easier/more flexible to be implemented in the same module instead of imposing a restriction that they must be separate.

**Comment by benjwadams** [comment]
Yes, we'd be locked into module level versioning for the *code* for a particular spec.  So if you had multiple related checkers in the same module and wanted to version them they'd have to be a class variable or similar.

On the plus side, there does exist a PEP for `__version__` https://www.python.org/dev/peps/pep-0396/

**Comment by daf** [comment]
This PEP seems much more aligned for package level version information.  I wouldn't find it intuitive to look for a version there, then again it's not necessarily needed to be exposed to people.  I'd still prefer to stick to the class level attributes.

**Comment by benjwadams** [comment]
Should be implemented now that #262 is merged. Closing.
