### ISSUE TITLE
Review compliance score for USACE Dataset

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#188]
http://wisdata.erdc.dren.mil/thredds/dodsC/frf/oceanography/temperature/eop-temp/2013/FRF-ocean_temperature_eop-temp_201312.nc.html

This dataset really should have received a perfect score without any corrective actions (for CF at least). I need to identify why corrective actions show up and why the error is claiming a self-reference for the coordinates.

**Comment by mhidas** [comment]
@lukecampbell I've noticed incorrect self-referencing results on some of my files too. Looks like this issue was introduced in 35dd9ec3ef93b84f3dad58c8c7ea61ea383608d2

**Comment by DanielJMaher** [comment]
```(compliance-checker)➜  compliance-checker git:(master) compliance-checker -v -t cf -c strict http://wisdata.erdc.dren.mil/thredds/dodsC/frf/oceanography/temperature/eop-temp/2013/FRF-ocean_temperature_eop-temp_201312.nc
Running Compliance Checker on the dataset from: http://wisdata.erdc.dren.mil/thredds/dodsC/frf/oceanography/temperature/eop-temp/2013/FRF-ocean_temperature_eop-temp_201312.nc


--------------------------------------------------------------------------------
                     The dataset scored 82 out of 82 points
                              during the cf check
--------------------------------------------------------------------------------
```
