### ISSUE TITLE
Question about check_reduced_horizontal_grid in cf.py

### ISSUE THREAD

**Issue by ggalibert** [ioos/compliance-checker#195]
I can see that ```check_reduced_horizontal_grid``` is looping through variables that are not coordinate variables (in the CF meaning) and which have a ```coordinates``` variable attribute, so that then each of their variables listed in ```coordinates``` must have for dimension a coordinate variable (see [line 1589] (https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L1589)):
```
                    if dim_name not in coord_vars:
                        valid_coord = False
                        reasoning.append("Coordinate %s's dimension, %s, is not a coordinate variable" % (coord, dim_name))
                        continue
```

Could you please explain why this test on the dimension being a coordinate variable is implemented?

I have an [example here] (http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/demos/ACORN/monthly_gridded_1h-avg-current-map_non-QC/TURQ/2012/catalog.html?dataset=eMII/demos/ACORN/monthly_gridded_1h-avg-current-map_non-QC/TURQ/2012/IMOS_ACORN_V_20121001T000000Z_TURQ_FV00_monthly-1-hour-avg_END-20121029T180000Z_C-20121030T160000Z.nc.gz) with a dimension that is not a coordinate variable and hence fails this check.

**Comment by lukecampbell** [comment]
I think the reduced grid checks are a bit wonky at the moment and I'll need to revise them.

**Comment by lukecampbell** [comment]
I'll mark this as a bug to fix soon.

**Comment by lukecampbell** [comment]
This is part of #211

**Comment by DanielJMaher** [comment]
So, we fixed the issues with self-referencing coordinate variables and some of the issues with looping through the relationship between variables, dimensions and coordinates as defined by the `coordinates` attribute.

This dataset isn't entirely compliant with CF §5.3 Reduced horizontal grid in that the data variables don't have a dimension which is a reduced grid as defined by 5.3. 

It would need something like

```
dimensions:
	TIME = UNLIMITED ; // (1 currently)
	I = 55 ;
	J = 57 ;
        rgrid=3135;
int rgrid(rgrid);
        rgrid:compress = "I J"
double LATITUDE(rgrid);
...

double LONGITUDE(rgrid);
...
float UCUR(TIME, rgrid);
        UCUR:coordinates = "TIME LATITUDE LONGITUDE";
```

**Comment by mhidas** [comment]
@DanielJMaher I don't think the file @ggalibert referred to is intended to be a "reduced horizontal grid" file. It's more like §[5.2. Two-Dimensional Latitude, Longitude, Coordinate Variables](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#idp5559280). According to the example there, it should be something like
```
dimensions:
	I = 55 ;
	J = 57 ;
	TIME = 493 ;

variables:
    int I(I) ;
    int J(J) ;
    double LATITUDE(I, J) ;
    double LONGITUDE(I, J) ;
    ...
    float UCUR(TIME, I, J) ;
        UCUR:coordinates = "TIME LATITUDE LONGITUDE" ;
```
I tried this and the checker seems happy with it. It just seems a bit superfluous to add these coordinate variables (I & J) which have no real meaning in this case.
