### ISSUE TITLE
Question about data type for flag_masks

### ISSUE THREAD

**Issue by lbesnard** [ioos/compliance-checker#196]
Question about the data type allowed for a flag_masks variable.

See CF.py code 
```python 
        type_ok = v.dtype in [np.character,
                                      np.dtype('b'),
                                      np.dtype('i4'),
                                      np.int32]
```
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L811

is there a reason why int8 and int32 are allowed and int16 is not. I previously had a file
with a flag_masks variable of "short' type not passing the CF checker

Thanks

@mhidas FYI

**Comment by lukecampbell** [comment]
it should allow all integer types, I believe.

**Comment by lukecampbell** [comment]
@benjwadams could you take a look at this?

**Comment by kwilcox** [comment]
@lbesnard can you try out the `ints` branch to see if it fixes the problem? Better yet, if you post a file here that was causing you issues I will write a test for it. There are currently no tests for `flag_masks`.

**Comment by lbesnard** [comment]
@kwilcox Sorry for the late answer. Thanks for having a look at this. An example file can be found here 
http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/sst/ghrsst/L3S-1d/ngt/2015/catalog.html?dataset=sst/ghrsst/L3S-1d/ngt/2015/20151231152000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_night.nc
