### ISSUE TITLE
Test "dimension_order" with inconsistent results

### ISSUE THREAD

**Issue by ggalibert** [ioos/compliance-checker#200]
This [file](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/timeSeriesProfile/catalog.html?dataset=eMII/checker_test/ANMN/timeSeriesProfile/IMOS_ANMN-QLD_AETVZ_20110307T111900Z_GBRHIS_FV00_GBRHIS-1103-Workhorse-ADCP-model-Sentinel-or-Monitor-44_END-20110813T105900Z_C-20160203T040408Z.nc) and this [one](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/timeSeriesProfile/catalog.html?dataset=eMII/checker_test/ANMN/timeSeriesProfile/IMOS_ANMN-QLD_AETVZ_20110307T111900Z_GBRHIS_FV01_GBRHIS-1103-Workhorse-ADCP-model-Sentinel-or-Monitor-44_END-20110813T105900Z_C-20160203T040408Z.nc) both include VCUR or VCUR_MAG such as:

```
float VCUR(TIME, HEIGHT_ABOVE_SENSOR) ;
                VCUR:coordinates = "TIME LATITUDE LONGITUDE HEIGHT_ABOVE_SENSOR" ;
                VCUR:standard_name = "northward_sea_water_velocity" ;
                VCUR:long_name = "northward_sea_water_velocity" ;
                VCUR:units = "m s-1" ;
                VCUR:valid_min = -10.f ;
                VCUR:valid_max = 10.f ;
                VCUR:_FillValue = 999999.f ;
                VCUR:comment = "magneticDeclinationPP: data initially referring to magnetic North has been modified so that it now refers to true North, applying a computed magnetic declination of 9.7degrees. NOAA\'s Geomag v7.0 software + IGRF12 model have been used to compute this value at a latitude=-23.5136degrees North, longitude=151.9553degrees East, depth=44m (instrument nominal depth) and date=2011/05/25 (date in the middle of time_coverage_start and time_coverage_end)." ;
                VCUR:ancillary_variables = "VCUR_quality_control" ;
                VCUR:magnetic_declination = 9.7 ;
                VCUR:compass_correction_applied = 9.7 ;
```

with

```
double TIME(TIME) ;
		TIME:standard_name = "time" ;
		TIME:long_name = "time" ;
		TIME:units = "days since 1950-01-01 00:00:00 UTC" ;
		TIME:calendar = "gregorian" ;
		TIME:axis = "T" ;
		TIME:valid_min = 0. ;
		TIME:valid_max = 90000. ;
```

and

```
float HEIGHT_ABOVE_SENSOR(HEIGHT_ABOVE_SENSOR) ;
		HEIGHT_ABOVE_SENSOR:comment = "Data has been vertically bin-mapped using tilt information so that the cells have consistant heights above sensor in time." ;
		HEIGHT_ABOVE_SENSOR:long_name = "height_above_sensor" ;
		HEIGHT_ABOVE_SENSOR:units = "m" ;
		HEIGHT_ABOVE_SENSOR:axis = "Z" ;
		HEIGHT_ABOVE_SENSOR:positive = "up" ;
		HEIGHT_ABOVE_SENSOR:reference_datum = "sensor" ;
		HEIGHT_ABOVE_SENSOR:valid_min = -12000.f ;
		HEIGHT_ABOVE_SENSOR:valid_max = 12000.f 
```

However the first one passes the cf check while the second fails on the dimension_order test:

```
dimension_order                        :1:    82/126 : Variable VCUR has a non-
                                                      space-time dimension after
                                                      space-time-dimensions
```

And I don't think this message should output since HEIGHT_ABOVE_SENSOR is a space dimension.

**Comment by ggalibert** [comment]
@mhidas could you please label this issue for me please (bug/imos required)?

**Comment by DanielJMaher** [comment]
@ggalibert Looking into this, it appears that if a variable has multiple dimensions AND a coordinates attribute that is not in T, Z, X, Y order it fails.  

I need to do some more testing to figure out the TZXY ordering for the coordinates attribute to make sure this diagnosis is 100%.

Reading the excerpt from 2.4 (included on the bottom of this comment), it appears that you can have the coordinates in a different order, as long as the the dimensions of the variable are correct.  I need to discuss with @lukecampbell  and think about the interpretation, but my gut says the test should allow for these to pass.  



        2.4 If any or all of the dimensions of a variable have the interpretations of "date or time" (T), "height or depth" (Z),
        "latitude" (Y), or "longitude" (X) then we recommend, those dimensions to appear in the relative order T, then Z, then Y,
        then X in the CDL definition corresponding to the file. All other dimensions should, whenever possible, be placed to the
        left of the spatiotemporal dimensions.

**Comment by lukecampbell** [comment]
I think it should pass, it's T,Z.

**Comment by DanielJMaher** [comment]
@lukecampbell Even though the coordinates at TXYZ?

**Comment by lukecampbell** [comment]
oh, I see what you're saying the coordinates attribute should be

```
VCUR:coordinates = "TIME HEIGHT_ABOVE_SENSOR LATITUDE LONGITUDE" ;
```

Not 
```
VCUR:coordinates = "TIME LATITUDE LONGITUDE HEIGHT_ABOVE_SENSOR" ;
```

That's quite picky and I don't necessarily agree with CF on that one but, yeah that's right, I think.

**Comment by DanielJMaher** [comment]
I think this is an example of the CChecker running wild.  i dont think CF 1.6 meant to check the coordinates for 2.4  

Sound good if I fix this test to ignore the coordinates?

**Comment by lukecampbell** [comment]
yes please.

**Comment by DanielJMaher** [comment]
@lukecampbell I was wrong on the coordinates part, but as we discussed I have the path forward.  Will explain in PR (no time frame).

**Comment by DanielJMaher** [comment]
@lukecampbell PR is in

**Comment by ggalibert** [comment]
What worries me more is that the two files I mentioned above are almost identical and the CF check doesn't behave consistently. One file passes it while the other doesn't...

**Comment by kwilcox** [comment]
@rsigell-usgs mentioned to me a few months ago that the order of the `coordinates` is arbitrary.  I had assumed it followed the same conventions as the dimensions.  Still the case?

**Comment by DanielJMaher** [comment]
I'm not 100% sure. I think coordinate ordering is more of a "nice to have" but I'm not sure I can tell you though that 2.4 shouldn't deal with coordinates at all. It's dimensions only. 

I'll look into the coordinates thing though.

**Comment by ggalibert** [comment]
[CF 1.6](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#coordinate-system) says: 

> The value of the coordinates attribute is a blank separated list of the names of auxiliary coordinate variables . There is no restriction on the order in which the auxiliary coordinate variables appear in the coordinates attribute string

**Comment by ggalibert** [comment]
[Somewhere else in CF 1.6](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#dimensions) goes:

> If any or all of the dimensions of a variable have the interpretations of "date or time" ( T ), "height or depth" ( Z ), "latitude" ( Y ), or "longitude" ( X ) then we recommend, but do not require (see Section 1.4, “Relationship to the COARDS Conventions” ), those dimensions to appear in the relative order T , then Z , then Y , then X in the CDL definition corresponding to the file. All other dimensions should, whenever possible, be placed to the left of the spatiotemporal dimensions.

So I guess that's what the test "dimension_order" should be about.

**Comment by daf** [comment]
> What worries me more is that the two files I mentioned above are almost identical and the CF check doesn't behave consistently. One file passes it while the other doesn't...

@DanielJMaher can you look into @ggalibert's files to see what's going on?

**Comment by lukecampbell** [comment]
It's no longer an issue with the latest...

There are a lot of self referencing errors tho.

**Comment by daf** [comment]
> There are a lot of self referencing errors tho.

Can you elaborate?

**Comment by lukecampbell** [comment]
I'm looking into it now, at a glance the graph traversal algorithm has a recursion bug in it which causes a false fail for the 2-D horizontal grid check §5.2
