### ISSUE TITLE
Create a way to skip a check

### ISSUE THREAD

**Issue by DanielJMaher** [ioos/compliance-checker#202]
We could use some way to pass a test to prevent one failed test from having a trickle down effect causing more failures that aren't real.

Not time critical, but cam up in conversation.

**Comment by kwilcox** [comment]
Already ran into the need for this. My temp solution:

```python
def check1(self, ds):
    assert ds.Conventions.lower() == "cf-2.0"

def check2(self, ds):
    got, want = self.check1(ds).value
    if got != want:
        return None

    ... go about your test
```

Obviously not ideal if `check1` is intensive... but works. Without a dependency graph, this won't be easy.

**Comment by daf** [comment]
Dependency graph idea:

```python
@depends('check1')
def check2(self, ds):
    ....
```

CheckSuite would have to scan for checks as usual, find these deps, make a graph, figure out if the graph is traversable, then execute in correct order.  Also give warning/error out if unknown dep shows up.

**Comment by DanielJMaher** [comment]
The proper way to handle this is to split this into two tasks.  The first is to create a decorator for skipping tests.  The second is to create the dependency graph for each check/subcheck.  The second step is a very time intensive task and requires a certain level of domain knowledge.  The first is rather simple and can be set to a command line prompt for now.  After the dependency graph is created the skip decorator can be modified to work with the dependency graph.

For now we should just create the command line skip test functionality and table the dependency graph for another milestone.  Having the command line skip will provide a way to deal with data intensive checks (e.g. Missing _FillValue), which can be troublesome for some users.

**Comment by kwilcox** [comment]
The verbiage in this issue is confusing. We want to skip a `check` not a `test! :confused:

How would the decorator for skipping checks work? Would we decorate each check with a list of tags and have the ability to skip certain tags when running? Would we supply the actual check function names to skip when running?

**Comment by DanielJMaher** [comment]
something simple like:

compliance-checker -t cf --skip "3.1.2, 4.5, 2.2" <path to file>

Then the decorator just checks "is my check in the list of skips? yes, skip. no, check."

I made those check numbers up, so don't worry if those aren't checks.
also i edited my comment for the word test, but the content is still the same.

**Comment by kwilcox** [comment]
How would the skips be presented in the final score? A new "skips" section? Would each skip just reduce the "total number" of the suite?

**Comment by DanielJMaher** [comment]
I would lean towards reducing the total number.  The user knows they skipped the check and anyone reviewing the scoring should notice that some were skipped.

**Comment by daf** [comment]
Both should be done.  Skipped tests need to be shown, just like unittests would do.

**Comment by lukecampbell** [comment]
There's no need for a decorator. There's a loop in suite.py, add a simple condition, "if check name matches a user defined skip, don't execute". 

The command line argument is wrong as well, I'll post the correct version in a bit.

**Comment by daf** [comment]
Ideally you'd want more than just the ability to skip checks by name, though.  The decorator intent is to have a class of checks to skip:

```
@skippable('data_access')
def check_i_access_data_one(...)
...

@skippable('data_access')
def check_i_also_access_data(...)
...
```

The user shouldn't have to know which checks individually do data access - just skip them all in one shot.

**Comment by lukecampbell** [comment]
That's too complicated, anything more than a very simple name comparison will have to be documented in a subsequent issue and we'll evaluate need versus resources available to address it.

**Comment by lukecampbell** [comment]
If the user wants to skip, then he/she will have to do more work, that's all we can support at the moment.

**Comment by daf** [comment]
I don't think #301 fully addresses this issue, as I've stated, but feel free to create a subsequent issue if that makes more sense ("Advanced Skipping...")

**Comment by lukecampbell** [comment]
The title is to skip a test, which we accomplished and rely heavily on the user to use command line arguments to identify which tests to be skipped. The description of this issue and the concept of a dependency graph describing the checking functionality is significantly beyond the scope of what we can accomplish in a reasonable time frame. I am closing this issue and we can open an advanced skipping issue if this fix truly does not help users work through these concerns.
