### ISSUE TITLE
Improve documentation for web service landing page

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/compliance-checker#204]
I'm not sure this is the right place to report this, but on the landing page for the web service version of the compliance checker:
http://data.ioos.us/compliance/index.html
I think two modifications to the page text could improve the user experience:

1. Add the size limit for files uploaded from disk.  Is it 5MB?  All I know is that I tried a 6.5Mb file, and it failed with the message "too big".   So perhaps just change "Upload your dataset here:" to "Upload your dataset (max 5MB) here".

2. Indicate that for remote access, an OPeNDAP data URL needs to be provided.  When I saw "Or run on a remote dataset via HTTP", I thought maybe you were supposed to put a netcdf file in a WAF or something.   So perhaps just change "Or run on a remote dataset via HTTP" to "Or provide remote OPeNDAP Data URL here"

![2016-02-04_7-22-26](https://cloud.githubusercontent.com/assets/1872600/12814887/7c97688e-cb10-11e5-92c0-dc1c80fb052d.png)

**Comment by kknee** [comment]
@rsignell-usgs both good suggestions, thanks!

**Comment by lukecampbell** [comment]
I did this and I increased the size to 16MB

![screen shot 2016-02-04 at 10 21 01 am](https://cloud.githubusercontent.com/assets/1155163/12819410/0303931c-cb29-11e5-993f-bb5fd7a10aba.png)
