### ISSUE TITLE
RESTful syntax for compliance checker service?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/compliance-checker#205]
Could the compliance checker service be made restful, so that you could, for example request that an OPeNDAP endpoint by checked for CF compliance by issuing a command like:

http://data.ioos.us/compliance?request=CF&report_format=PDF&remote_url=http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/CAPE_COD_BAY/3051B-A.cdf

That would allow nice batch processing. 

Report format could be HTML, PDF, ...

**Comment by lukecampbell** [comment]
It's not restful in the REST sense but there is a public facing API that reads and returns JSON, and allows uploading of files.  Right now we have CSRF and a login preventing 3rd party access but we'll be removing those soon.

**Comment by lukecampbell** [comment]
I will add documentation for this service to the wiki, once we remove the login.

**Comment by rsignell-usgs** [comment]
Since you already have an API, it would be easy to make a RESTful service also, no?  
I still think it would be a nice addition.    Some people don't like to code.   :grinning:

**Comment by lukecampbell** [comment]
I could make it restful-ish for posting URLs but uploading files embedded in JSON is not restful and it's tedious for both the client and the server-side developer. 

Right now it would be something like 

```
curl --data "checker=cf&url=http%3A%2F%2Fgeoport-dev.whoi.edu%2Fthredds%2FdodsC%2Fusgs%2Fdata2%2Femontgomery%2Fstellwagen%2FCF-1.6%2FCAPE_COD_BAY%2F3051B-A.cdf" -XPOST http://localhost:3839/upload
```

For a file upload it would be 

```
curl --form "checker=cf" --form "file-0=@/Users/lcampbell/Downloads/ygnn6_20160204.nc;filename=ygnn6_20160204.nc" -XPOST http://localhost:3839/upload
```

If we forced this to be RESTful it would be a tad more complicated. Basically we'd embed JSON into form fields with a file upload. 

http://stackoverflow.com/questions/3938569/how-do-i-upload-a-file-with-metadata-using-a-rest-web-service

It's much simpler to stick with form fields if we're uploading files, I think.

**Comment by rsignell-usgs** [comment]
Version 1 of the REST interface could work only with DAP URLs, and you save the uploading files part for a future version (or never!).

**Comment by lukecampbell** [comment]
yeah, I could make a REST-like interface for DAP URLs.

**Comment by lukecampbell** [comment]
Hey folks, just a heads up. This was fixed in https://github.com/ioos/compliance-checker-web/pull/39/files

Once 2.3.0 release is complete we'll update the site which will include these changes.

**Comment by Bobfrat** [comment]
Some documentation here:
https://github.com/ioos/compliance-checker-web/wiki/API
