### ISSUE TITLE
Remove login from compliance checker web

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#207]
Several people, all within the span of 24 hours have asked me to remove the login requirement from the online compliance checker service.

**Comment by rsignell-usgs** [comment]
Make that 8.  :smile_cat:

**Comment by lukecampbell** [comment]
I've got the PR ready to go, just waiting for the "go-ahead" from the higher ups.

**Comment by rsignell-usgs** [comment]
like @dpsnowden ?
