### ISSUE TITLE
Self Referencing Coordinates Bug 

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#211]
http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/CAPE_COD_BAY/3051B-A.cdf

Running CF on this dataset results in a several `coordinates_reference_itself` for the §5.2 Check(s). Looking at the actual dataset, I cannot see any coordinates that reference themselves in a coordinates attribute. After looking and debugging minimally, I think the issue is in how we are building a graph structure for checking coordinates and references for §5.2

**Comment by lukecampbell** [comment]
Discovered from https://github.com/ioos/compliance-checker/issues/200

**Comment by kwilcox** [comment]
@lukecampbell I'm seeing either this bug, or another in the `TestCF.test_check_two_dimensional` test. It inconsistently passes and fails for me on the same dataset. @ggalibert

**Comment by kwilcox** [comment]
I fixed the bug in `check_two_dimensional` here: https://github.com/ioos/compliance-checker/commit/1eac74f591a5ae50ce600203bd565cd4b7026e6b

**Comment by lukecampbell** [comment]
![screen shot 2016-02-08 at 3 53 41 pm](https://cloud.githubusercontent.com/assets/1155163/12898728/288bd63e-ce7c-11e5-804b-d7cb909ee2aa.png)
