### ISSUE TITLE
get_safe method on DotDict does what?

### ISSUE THREAD

**Issue by kwilcox** [ioos/compliance-checker#212]
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/util.py#L143-L151

`get_safe` isn't going to be defined from within this class function. Do we need this method?  If its used anywhere it would be raising an exception.

`getattr(self, qual_key)` ?

**Comment by daf** [comment]
Was copypasta'd from OOI, here's what `get_safe` is supposed to be: [pyon/utils/containers.py](https://github.com/ooici/pyon/blob/122c629290d27f32f2f41dafd5c12469295e8acf/pyon/util/containers.py#L198-L211)

**Comment by kwilcox** [comment]
AH ok, we are just missing a higher scoped function of the same name.. I'll add.
