### ISSUE TITLE
4MB file results in "File is too large"

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/compliance-checker#221]
On the online compliance checker
http://data.ioos.us/compliance/index.html
it says the max size for a netcdf file to test is 16MB. 

When I try to upload this 4MB netcdf file
https://drive.google.com/a/usgs.gov/file/d/0B4Ftaivb4JbZUVpJUjhwUWZqaVk/view
however, I get "File is too large"

**Comment by lukecampbell** [comment]
Thanks, I'll try to get to this soon. That's rather embarassing.

**Comment by DanielJMaher** [comment]
@rsignell-usgs I downloaded your dataset and ran it in the online compliance checker.  Can you confirm it works so I can close?

**Comment by rsignell-usgs** [comment]
Yes, it now works!  Great!  Fixed in ???
