### ISSUE TITLE
CF check units attribute is required for crs

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker#223]
Is this true? Looking through CF documentation http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#appendix-grid-mappings, I don't see any reference to a units attribute for the crs variable. I received this error using the web-based checker on the file http://data.nodc.noaa.gov/thredds/catalog/testdata/mbiddle/catalog.html?dataset=testdata/mbiddle/gcoos_ioos_station_USF_COMPS_C10_2015_11_atm.nc.

**Comment by mbiddle-nodc** [comment]
This was an error in the file. crs was defined with a dimension of timeSeries. crs shouldn't have a dimension, so I think that's why I got this error. Just as an FYI I tested the same file using the CF checker at puma.nerc.ac.uk/cgi-bin/cf-checker.pl and got an error message "A grid mapping variable should have 0 dimensions", which was slightly more helpful...

**Comment by lukecampbell** [comment]
Ah, I think this is a bug. 
```
        int crs(timeSeries) ;                                                                                                                                                                      [161/672]
                crs:inverse_flattening = 298.257223563 ;
                crs:grid_mapping_name = "latitude_longitude" ;
                crs:epsg_code = "EPSG:4326" ;
                crs:semi_major_axis = 6378137 ;
                crs:_Netcdf4Dimid = 1
```

Our checker doesn't know how to identify that this is a metadata variable because it has a dimension.

**Comment by lukecampbell** [comment]
Although I feel like, crs shouldn't have a dimension in this case.

**Comment by mbiddle-nodc** [comment]
Yes, crs shouldn't have a dimension. However, should the checker know that for the crs variable there shouldn't be units (even if it's declared with a dimension)? I tested it with 
`        int crs ;
                crs:grid_mapping_name = "latitude_longitude" ;
                crs:epsg_code = "EPSG:4326" ;
                crs:semi_major_axis = 6378137 ;
                crs:inverse_flattening = 298.257223563 ;
`

And no longer received the error message.

**Comment by DanielJMaher** [comment]
@lukecampbell So do we want to put a catch in our check looking for the variable "crs"  if it exists and it has a dimension, throw a more helpful error message?

**Comment by kwilcox** [comment]
We should be looping over all variables and collecting the variable names that are identified in the `grid_mapping` attribute... and then ignoring all of those. The variable won't always be called `crs`!

**Comment by DanielJMaher** [comment]
@kwilcox Makes sense.  I'm wondering if we can wrap this into the "skip this test" functionality we've been discussing.  Dispatch multiple avians with singular compacted minerals.

**Comment by lukecampbell** [comment]
Yeah, I agree with @kwilcox we should update https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L161 to also include variables mentioned by the `grid_mapping` attribute.

**Comment by DanielJMaher** [comment]
@lukecampbell #229 was closed, should this one be as well?

**Comment by mbiddle-nodc** [comment]
With the web checker I'm still getting a similar error for missing units in a metadata variable. For example, I have a metadata variable instrument_1 and I get the following high priority error:

> 3.1 Variables contain units	3	units attribute is required for instrument_1

**Comment by lukecampbell** [comment]
I haven't updated the web service yet
