### ISSUE TITLE
Conventions includes CF-1.6

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker#224]
In CF testing this file http://data.nodc.noaa.gov/thredds/catalog/testdata/mbiddle/catalog.html?dataset=testdata/mbiddle/gcoos_ioos_station_USF_COMPS_C10_2015_11_atm.nc I receive an error 

> Conventions field is "CF-1.x (x in 0-6)"

 However, the global attribute is
`               :Conventions = "CF-1.6,ACDD-1.3" ;`

The NCEI recommendation is 

>         :Conventions = "CF-1.6, ACDD-1.3" ; //....A comma separated list of the conventions being followed. Always try to use latest version. (CF/ACDD)

According to CF:

> We recommend that netCDF files that follow these conventions indicate this by setting the NUG defined global attribute Conventions to the string value "CF-1.6".

According to ACDD:

> Conventions - A comma-separated list of the conventions that are followed by the dataset. For files that follow this version of ACDD, include the string 'ACDD-1.3'. (This attribute is described in the NetCDF Users Guide.)

So my question is, does this error occur because I am explicitly testing against CF, which doesn't describe the possibility of a comma separated list? Or, is there something else going on? I've tested with:
`                :Conventions = "CF-1.6" ;`
and get the same notice.

**Comment by daf** [comment]
@mbiddle-nodc what version/revision are you currently running?  I'm on current master (381ce45bdc5cf885106af2ba1ccd72e2553ceece) and don't receive an error about the Conventions for this file, it's passing.

**Comment by daf** [comment]
Ah I don't think you're on master as you don't have the changes introduced in 42de2e3f, which altered the error message that you are currently getting.

**Comment by mbiddle-nodc** [comment]
I was using the web checker at http://data.ioos.us/compliance/index.html. I am still having trouble installing locally.

**Comment by lukecampbell** [comment]
The web checker is using the previous release. I will update it once 2.1 is ready.

**Comment by mbiddle-nodc** [comment]
Any ideas as to when this update will happen? I'm still getting the same error.

**Comment by kknee** [comment]
@mbiddle-nodc 2.1 should be ready in two weeks, then @lukecampbell can update the web checker.

**Comment by benjwadams** [comment]
Version has been bumped, and error appears to have disappeared when referencing the netCDF dataset in question.  Closing for now.
