### ISSUE TITLE
List C/Non-Python Library dependencies in README

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#227]
README file should list any required C libraries, i.e. libxml, NetCDF, etc.

**Comment by DanielJMaher** [comment]
@benjwadams can you find some time to do this next week so we can look to close 2.2

**Comment by benjwadams** [comment]
Related: a useful question I asked on SO regarding a similar issue
http://stackoverflow.com/questions/32698846/retrieve-list-of-external-c-fortran-dependencies-for-python-libraries-within-a-v

**Comment by benjwadams** [comment]
NB:  This may not be an exhaustive list for all dependencies.  Some package managers may install Fortran dependencies, whereas others will not, so it's possible that BLAS/LAPACK etc, may be needed for installation on some systems.  If this is the case, feel free to reopen this issue.
