### ISSUE TITLE
Classify variables defined by `grid_mapping` attribute as aux or ancillary variables

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#229]
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L161

For each variable in the dataset find any and all attributes `grid_mapping` and see if there is a variable matching that name. If there is, it should be classified as an ancillary variable and not be checked for units or standard name.

**Comment by lukecampbell** [comment]
This will fix https://github.com/ioos/compliance-checker/issues/223#issuecomment-190780420

**Comment by daf** [comment]
Uh looks done already https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L186-L189

**Comment by lukecampbell** [comment]
in that case, we need to figure out why it's not working.

**Comment by daf** [comment]
It's working fine.  It's the `check_units` test that doesn't know it is supposed to skip them, see https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L530-L575

Or doesn't play by the rules (the dimensionless text?)

**Comment by lukecampbell** [comment]
Yeah but it should pick it up here:
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L551

which checks ancillary here:
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L204

Unless I'm missing something

**Comment by daf** [comment]
It checks ancillary and continues, aka doesn't add it to the list of metadata vars returned.  Either that's an omission or coded specifically this way, I don't remember.

**Comment by DanielJMaher** [comment]
I think that Dave has it on the head.  We aren't adding the mapping variables to the metadata var list, so we are acting as if they need to go through the full 3.1 check.  We should be adding it to the metadata var list and allowing them to skip this section.

Agreed?

**Comment by DanielJMaher** [comment]
to resolve adding ancillary here: https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L551

**Comment by daf** [comment]
aka here https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L204-L205 (why `continue`?)

**Comment by DanielJMaher** [comment]
@daf Because ancillary variables are not technically metadata variables.  Or at least that was the argument laid out by Luke.  

I think it is fine because of 2 things:  1) Maybe there is a check where ancillary shouldn't be grouped with other metadata variables.  2) by making the change i suggested we fix the issue without the fear of disrupting other checks down the line.

**Comment by daf** [comment]
Ok, I see what you mean now - you want to pull ancillary variables as a line after https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L551 and skip those in the `check_units`, right?

**Comment by DanielJMaher** [comment]
Correct.

**Comment by daf** [comment]
(this new github reactions thing is weird)
