### ISSUE TITLE
ACDD Test NetCDF file is not included in this repo

### ISSUE THREAD

**Issue by DanielJMaher** [ioos/compliance-checker#230]
The tests aren't very robust (read: only one test), but never the less it shouldn't be hardcoded like this.  That file should be included in the compliance_checker/tests/data folder and referenced from there.

**Comment by lukecampbell** [comment]
I agree. Also, something that I would like to see integrated with compliance checker at some point is not to include the netCDF files into the project but just the CDLs. 

For example:

https://github.com/ioos/cc-plugin-ncei/blob/master/cc_plugin_ncei/tests/resources.py

This module will compile a CDL file into a netCDF file if the .nc file doesn't exist, which would allow us to only have to commit the CDL files and not the binary netCDF files.
