### ISSUE TITLE
ACDD Check Bug

### ISSUE THREAD

**Issue by DanielJMaher** [ioos/compliance-checker#232]
[Dataset to Reproduce](https://www.dropbox.com/s/i5a4e2can4de5n7/20150210T1900_TO_20150225T1000.nc?dl=0) 

@kwilcox reported this bug previously:

I'm getting ACDD failures for every variable because they don't have a coverage_content_type attribute. Should this only be tested for "data" variables? It is failing on things like crs, time, and latitude.

Diving into it I found this additional bug for the ACDD.

```
WARNING: The following exceptions occured during the acdd checker (possibly indicate compliance checker issues):
acdd.check_time_extents: can't subtract offset-naive and offset-aware datetimes
  File "/Users/danielmaher/work/compliance-checker/compliance_checker/acdd.py", line 349, in check_time_extents
    t_min = (parse_dt(ds.time_coverage_start) - epoch).total_seconds()
```

I am not sure if they are related at this point, but we should look into it.

**Comment by lukecampbell** [comment]
Also we need to reuse the logic we use in CF to ignore ancillary/metadata variables like `platform_id` `crs` `station_id` etc. The algorithm to identify these is a bit tricky and is certainly far from perfect but it's the best we have so far.

**Comment by lukecampbell** [comment]
On that note it would be awesome to move these into a util module for the rest of the plugins to use
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L145-L317

**Comment by lukecampbell** [comment]
Fixed with the last release for ACDD

```
varattr                                :3:    11/13 :
    battery_voltage                    :3:     2/ 4 :
        coverage_content_type          :3:     0/ 1 : Var battery_voltage
                                                      missing attr
                                                      coverage_content_type
        var_std_name                   :3:     1/ 2 : Var battery_voltage
                                                      missing attr long_name
```

`battery_voltage` is a geophysical variable that would technically require `coverage_content_type`

But `instrument` doesn't require one, nor platform nor crs.
