### ISSUE TITLE
Package with compliant netCDF file(s)

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker#237]
I was curious if there was a plan to include a 100% compliant netCDF file as an example with the package. It could be something useful to data providers. I can assist in generating this, if it's something of interest.

**Comment by lukecampbell** [comment]
It would be good to generate some 100% compliant files for each of the major feature types CF supports:

- point
- timeSeries
- profile
- timeSeriesProfile
- trajectoryProfile

And a regular grid. Interestingly, I can't find any mention of gridded files in CF-1.6 other than dealing with grid-mappings, but I speculate that it's only reference to grid mappings pertain to points as part of a grid, not a dataset of a gridded feature type.

**Comment by DanielJMaher** [comment]
@lukecampbell @kknee  It would be amazing to have some help from the community with this.  Finding a 100% (or clsoe to it) compliant file is very difficult.  If the community had golden standard datasets it would greatly help our development of the checkers.  

Is there a good way to approach getting these files?

**Comment by mbiddle-nodc** [comment]
One thought that would help on two fronts, work with the GCOOS github repository for converting csv to nc https://github.com/GCOOS/csv2nc. This would fulfill the gold standard for timeSeries and would help with GCOOS archiving at NCEI. @fgayanilo

**Comment by kwilcox** [comment]
I wrote these an extremely long time ago but they are still valid:  https://github.com/asascience-open/CFPointConventions. You could take the CDLs and add metadata as needed.

**Comment by kwilcox** [comment]
There is also this for csv/pandas to NetCDF Timeseries/TimeseriesProfile:  https://github.com/axiom-data-science/pyaxiom/blob/master/README.md#creating-cf16-timeseries-files. You will have to look at the tests for additional examples, there isn't any documentation other than the README.

**Comment by mbiddle-nodc** [comment]
Keeping this updated, I'm close to having the "Gold standard" example files ready. Once they get the 'ok' from our working group, I will post them on our thredds to be picked up, and update this issue.

**Comment by lukecampbell** [comment]
I've already included them in the NCEI checker, but I'd like to include them as tests in the CF checker as well.

**Comment by mbiddle-nodc** [comment]
Just saw this old thread, figured I would include the new paths to the gold standard example data files:

http://data.nodc.noaa.gov/thredds/catalog/example/catalog.html
and
http://data.nodc.noaa.gov/ncei/example/data/netcdf/

Some documentation about running them through the checker is coming soon...
