### ISSUE TITLE
Strange encodings error with windows and python 3

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/compliance-checker#245]
When I try this test on win64, I get some strange "encodings" error:
```
[TEST] C:\Users\rsignell>conda create --name TEST --channel conda-forge python=3.4 compliance-checker

[TEST] C:\Users\rsignell>compliance-checker --test cf http://geoport.whoi.edu/thredds/dodsC/clay/usgs/users/jcwarner/Projects/Sandy/triple_nest/00_dir_NYB05.ncml

...
indexed_ragged_array                    :2:     0/0
missing_data                            :2:     0/0
orthogonal_multidim_array               :2:     0/0
                                 High Priority

--------------------------------------------------------------------------------

    Name                            :Priority: Score
Traceback (most recent call last):
  File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda2\envs\TEST\Scripts\c
ompliance-checker-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda2\envs\TEST\Scripts\c
checker.py", line 41, in main
    args.format)
  File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda2\envs\TEST\lib\site-
packages\compliance_checker\runner.py", line 44, in run_checker
    groups = cls.stdout_output(cs, score_groups, verbose, limit)
  File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda2\envs\TEST\lib\site-
packages\compliance_checker\runner.py", line 74, in stdout_output
    cs.non_verbose_output_generation(score_list, groups, limit, points, out_of)
  File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda2\envs\TEST\lib\site-
packages\compliance_checker\suite.py", line 311, in non_verbose_output_generatio
n
    print('%-40s:%s:%6s/%1s'  % (score_list[x][0][0:39], score_list[x][1], score
_list[x][2][0], score_list[x][2][1]))
  File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda2\envs\TEST\lib\encod
ings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xa7' in position 0:
 character maps to <undefined>

[TEST] C:\Users\rsignell>
```

**Comment by benjwadams** [comment]
@rsignell-usgs , I encountered some odd problems with "section"/§ symbols in CF when trying to support Python 2.  Although you're using 3 here, it looks to me that you are outputting to your terminal, which uses CP437 encoding, which does not include that character.  Unfortunately, I don't have a Windows box set up at the moment, but my suspicion is that it's due to the default character set Windows used in terminals.

**Comment by benjwadams** [comment]
OK, I got a working conda setup for compliance checker going.  Assuming you're running from `cmd.exe`, try running `set PYTHONIOENCODING=:replace` to replace the § signs with ? prior to running compliance checker.  See also the docs for `PYTHONIOENCODING` https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING .  Another possibility is to override the default `sys.stdout` and add error handlers to it.  Of course, if your terminal doesn't support the character in the first place, it's not going to be printed out, but I suppose this is a case of choosing the least of all evils.

**Comment by benjwadams** [comment]
Related: http://stackoverflow.com/questions/35863825/how-to-print-unsupported-unicode-characters-on-windows-cmd-as-e-g-instead-o

**Comment by daf** [comment]
We should likely just change the characters. Forcing Windows users to make
environmental changes or face runtime errors violates principle of least
surprise.

**Comment by lukecampbell** [comment]
Changing the § to Section is fine by me from a technical perspective but I don't want to cater to terminals or applications that can't support utf-8.

**Comment by lukecampbell** [comment]
http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500

**Comment by lukecampbell** [comment]
I deliberately, chose to use § symbol, and undergo an extreme pain in my ass so it would highlight ALL of the issues like this. I don't have a personal affinity towards it. 

netCDF and server-side content are free to use whatever encoding they want and the compliance checker will need to deal with it. So if someone uses for example é in a title or μ in a title, abstract or god forbid units, this issue as @rsignell-usgs sees, would still persist I think.

**Comment by lukecampbell** [comment]
Is this still an issue?
