### ISSUE TITLE
Mechanism for dynamically updating standard name table

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#247]
CF Standard Names table updates much faster than releases for compliance checker so we need a way to dynamically update the standard name table for the checker.

**Comment by mbiddle-nodc** [comment]
Not sure if this helps, but I parse the standard_name_table attribute for the table version. Then I use
`url = "http://cfconventions.org/Data/cf-standard-names/%s/src/cf-standard-name-table.xml"% std_version`
to get the xml document with the CF standard_name table for whatever version the file is using. For example, if the global attribute is
`                :standard_name_vocabulary = "CF Standard Name Table v30" ;`
Then, the url composed would be
`http://cfconventions.org/Data/cf-standard-names/30/src/cf-standard-name-table.xml`

This allows the CF standard_name testing to be a little bit more dynamic.

**Comment by lukecampbell** [comment]
That's an awesome idea!

**Comment by daf** [comment]
I'd recommend a base version be packaged, with a mechanism to download/cache this live one to `$XDG_HOME_CACHE` or similar (not sure what that is on Windows, expecting python to have this covered for us).  We should not have a connectivity requirement for testing local files.

**Comment by benjwadams** [comment]
This might come in handy, it generates a CSV from a standard name table version (v29 in the gist).  Since it uses pandas, we could easily output it to a Python data structure instead.

https://gist.github.com/benjwadams/2f9c4db1aa8db60128e7

**Comment by Bobfrat** [comment]
So is the consensus here to try to download the standard name table that's defined in ```:standard_name_vocabulary``` and if that fails, fall to the packaged version? 

It sounds like @lukecampbell wants the ability to update the packaged version as well. I could add a command line argument to update to the latest version.

**Comment by kwilcox** [comment]
You could just update the packaged file with a new version periodically

**Comment by lukecampbell** [comment]
Ok, the code is ready, now we just need to update the README and we can close this.

**Comment by daf** [comment]
I'd like it to print the current standard name table version (and if it came from local) on run if possible.  Will help future debugging sessions.

**Comment by lukecampbell** [comment]
actually yeah, that's pretty critical I think. Because it affects output results somewhat dramatically.
