### ISSUE TITLE
CF standard_name check

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker#248]
In the CF standard_name check there is an inherent assumption that the variable must contain a standard_name attribute. Would it be possible to implement a way to look at all the variables and make a note of which variables should have a standard_name attribute?

I've done this previously by looking for the attribute 'coordinates'. If the variable has an attribute of coordinates, it should have a standard_name attribute. This makes an assumption as well, but it's just a thought of how to implement such a check.

I bring this up in regards to this file: http://www.neracoos.org/thredds/catalog/UMO/CF16/TESTS/2016/UMO/catalog.html?dataset=CF16_TESTS/2016/UMO/F0150.waves.mstrain.cf16f.nc. 

All of the geophysical variables (eg. significant_wave_height_3) are missing standard_name attributes. In this case, it would be nice to have a warning message that says, the following variables are missing standard_name attributes...

I'm not sure if this is even feasible, but it would be nice.

**Comment by lukecampbell** [comment]
Fixed with https://github.com/ioos/compliance-checker/commit/c22729aa30f31ab8cec1a3a2d4748a68e7fca33b
