### ISSUE TITLE
lat/lon units are acceptable, but not recommended

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker#251]
Testing this file: http://www.neracoos.org/thredds/dodsC/UMO/CF16/TESTS/2016/UMO/catalog.html?dataset=CF16_TESTS/2016/UMO/F0150.sbe37.realtime.1m.cf16f.nc we get the following notification:
§4.1 Coordinates representing latitude	2	lat units are acceptable, but not recommended
§4.1 Coordinates representing longitude	2	lon units are acceptable, but not recommended

But in the file,
lat:units = "degree_north" ;
lon:units = "degree_east" ;

According to the CF standard name table v32:
"Latitude is positive northward; its units of degree_north (or equivalent) indicate this explicitly."
"Longitude is positive eastward; its units of degree_east (or equivalent) indicate this explicitly."

Any thoughts as to what the problem is?

**Comment by lukecampbell** [comment]
they should be degrees_north and degrees_east.  Plural, not singular.

§4.1
```
The recommended unit of latitude is degrees_north. 
```

§4.2
```
The recommended unit of longitude is degrees_east.
```

**Comment by mbiddle-nodc** [comment]
Ah, I forgot about that sentence in the CF documentation. Thanks.
