### ISSUE TITLE
Inconsistent messages from CLI and README.md.  tests removed?

### ISSUE THREAD

**Issue by dpsnowden** [ioos/compliance-checker#265]
`> cchecker.py --help`
 
output is inconsistent with the output on the README.md file.

README.md shows that `acdd|cf|ioos` are all builtin tests but the actual software only provides `ioos` as an option.  

Have the cf and acdd test suites been removed and placed in plugins?  As @mbarimike for more details if this ins't clear.

**Comment by benjwadams** [comment]
@dpsnowden, see if running `setup.py install` helps.  It should reload all the checkers.  There were a number of changes and refactors made to the codebase in order to support ACDD 1.3 and versioned checker numbers.  See #127, #186. As for your question, the CF and ACDD test suites have not been removed, and in fact the ACDD test suite has been updated.

**Comment by MBARIMike** [comment]
No joy after `python setup.py install`:

```
$ python setup.py install
(lots of output)
$ ./cchecker.py --help
Could not load acdd = compliance_checker.acdd:ACDDBaseCheck : python: undefined symbol: cv_convert_float
Could not load cf = compliance_checker.cf.cf:CFBaseCheck : cannot import name config
usage: cchecker.py [-h] [--test {ioos}] [--criteria [{lenient,normal,strict}]]
                   [--verbose] [-f {text,html,json}] [-o OUTPUT] [-V]
                   [dataset_location [dataset_location ...]]

positional arguments:
  dataset_location      Defines the location of the dataset to be checked.

optional arguments:
  -h, --help            show this help message and exit
  --test {ioos}, -t {ioos}, --test= {ioos}, -t= {ioos}
                        Select the Checks you want to perform.
  --criteria [{lenient,normal,strict}], -c [{lenient,normal,strict}]
                        Define the criteria for the checks. Either Strict,
                        Normal, or Lenient. Defaults to Normal.
  --verbose, -v         Increase output. May be specified up to three times.
  -f {text,html,json}, --format {text,html,json}
                        Output format
  -o OUTPUT, --output OUTPUT
                        Output filename
  -V, --version         Display the IOOS Compliance Checker version
                        information.
```

**Comment by benjwadams** [comment]
@MBARIMike, do you have the udunits2 C library installed in shared libraries?  The error reading

`undefined symbol: cv_convert_float`

might indicate something is amiss with udunits.

Please check using `ldconfig -p | grep udunits` or similar.

**Comment by ocefpaf** [comment]
> No joy after `python setup.py install`:

@MBARIMike there are not wheels (the new PyPI binary bundle format) for `compliance-checker` neither the install procedure will fetch and download all the dependencies, like the missing `udunits2` issue you are experiencing. I recommend you to, if possible, use [conda](http://conda.pydata.org/miniconda.html) to install software like\* compliance checker:

`conda install -c conda-forge compliance-checker `

That will fetch install `compliance-checker` with all its dependencies on any platform (Windows, OS X, Linux).

\* Python Software that depends on and/or are built against external libraries (like C).

**Comment by MBARIMike** [comment]
`ldconfig -p | grep udunits` returned nothing. Did `sudo yum install udunits2` and now get:

```
$ ./cchecker.py --help
usage: cchecker.py [-h] [--test {acdd,cf,ioos}]
                   [--criteria [{lenient,normal,strict}]] [--verbose]
                   [-f {text,html,json}] [-o OUTPUT] [-V]
                   [dataset_location [dataset_location ...]]

positional arguments:
  dataset_location      Defines the location of the dataset to be checked.

optional arguments:
  -h, --help            show this help message and exit
  --test {acdd,cf,ioos}, -t {acdd,cf,ioos}, --test= {acdd,cf,ioos}, -t= {acdd,cf,ioos}
                        Select the Checks you want to perform.
  --criteria [{lenient,normal,strict}], -c [{lenient,normal,strict}]
                        Define the criteria for the checks. Either Strict,
                        Normal, or Lenient. Defaults to Normal.
  --verbose, -v         Increase output. May be specified up to three times.
  -f {text,html,json}, --format {text,html,json}
                        Output format
  -o OUTPUT, --output OUTPUT
                        Output filename
  -V, --version         Display the IOOS Compliance Checker version
                        information.
```

**Comment by MBARIMike** [comment]
Ah, I see that you specify that udunits is a Non-Python dependency.

Thanks for the help!

**Comment by benjwadams** [comment]
Is this all set?  Can I close?

**Comment by MBARIMike** [comment]
All set. Okay to close.
