### ISSUE TITLE
Refactor feature detection in CF Checker

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#285]

**Comment by kwilcox** [comment]
@lukecambell I might have the code you need already, ping me when you start this.

**Comment by lukecampbell** [comment]
I have it as well:
https://github.com/ioos/cc-plugin-ncei/blob/master/cc_plugin_ncei/util.py

**Comment by lukecampbell** [comment]
I'd be curious to see what you have as well. I went through several iterations of this, where I looked at all mess of attributes to determine features. But, fundamentally, people just don't fill in metadata, and the compliance checker, which aims to fix that, needs to be able to do things like feature detection with as minimal information as possible.

I originally relied on things like cdm_data_type, cf_role attributes. But I realized after some real-world testing that we'd wind up with the same problem, mismatching of features. Things like time-series-incomplete or time-series-orthogonal would show up as grids if cf_role wasn't specified.


So, I took a vastly different approach and worked on defining features by the combination and order of dimensions/coordinate variables in variables. I feel like with this approach I make the least amount of assumptions and with my test datasets it had the highest feature detection success of the other methods I tried.

**Comment by daf** [comment]
Ideas: 

I still think it'd be beneficial to make the detection a percentage rather than a True/False only - "we meet 5/6 criteria for such and such", sort, choose best.  Tell folks the result of this testing: "It looks like you're trying to make a Trajectory, but ___ is missing" - closer to the original goals of the project.

Second, a command line switch to force testing of a particular type.

**Comment by mhidas** [comment]
I like @daf's suggestions. In addition, the option to skip all discrete sampling geometry checks could be helpful.

**Comment by lukecampbell** [comment]
This was done, but we still have a little bit more on Chapter 9.

I've read CF 1.6 start to finish countless times at this point. Chapter 4 and Chapter 5 pertain a lot to grids and supporting grid types. But grids are not listed anywhere in Chapter 9, which is all about discrete geometry. Grids are allowed, but they can't have the attribute `featureType` because only valid entries from §9.1 are allowed.

So right now if the feature type is a grid, you get all the usual checks, chapter 1-8, but no chapter 9 checks. If you define featureType and it's anything not in the §9.1 listing it will fail and complain. If it IS something in the §9.1 list but the dimensions and feature types of geophysical variables don't back that up, it will fail.

Unfortunately, a thorough verification of matching §9.1 featureTypes to implementations of discrete geometry may not be doable. It turns into a combinatorics problem with the introduction of the concepts of "complete vs incomplete" and "orthogonal vs ragged-array". In the interest of simplicity if the feature type is _easily_ discernible we will compare with the attribute otherwise the checker won't perform any other checks.

This allows for complex geometries like multi-dimensional-ragged-arrays to still pass and get a perfect score.
