### ISSUE TITLE
Errors loading checkers

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker#288]
Hey Folks - I installed the most recent compliance checker from conda-forge:

>> conda install -c conda-forge compliance-checker

Then I tried to follow the implementation code suggested in the README file and got the following errors:

```
: from compliance_checker.runner import ComplianceChecker, CheckSuite

## Load all available checker classes
check_suite = CheckSuite()
check_suite.load_all_available_checkers()

Could not load acdd:1.1 = compliance_checker.acdd:ACDD1_1Check : [UT_OPEN_ARG] Failed to open UDUNITS-2 XML unit database : "No such file or directory"
Could not load acdd:1.3 = compliance_checker.acdd:ACDD1_3Check : cannot import name config
Could not load acdd = compliance_checker.acdd:ACDD1_1Check : cannot import name config
Could not load cf = compliance_checker.cf.cf:CFBaseCheck : cannot import name config
```

What am I missing?

**Comment by lukecampbell** [comment]
I think this is from the udunits library... I'm not sure how to install it on windows boxes. @ocefpaf any ideas?

**Comment by lukecampbell** [comment]
We added a fix to the cf-units library which does a better job explaining the error than just "UT_OPEN_ARG" or whatever. Although, now that I think about it, isn't it usually something like CV_FLOAT.  This may be something to do with the XML file.

**Comment by ocefpaf** [comment]
`udunits2` should be present. Let me investigate this here and I will get back to you.

**Comment by jbosch-noaa** [comment]
If it helps, I forgot to mention that I did the install after activating the ioos environment.

**Comment by ocefpaf** [comment]
@jbosch-noaa can you copy and paste the result of `conda list` for me here?

**Comment by jbosch-noaa** [comment]
!conda list
# packages in environment at C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2:
#
alabaster                 0.7.8                    py27_0  
babel                     2.3.3                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
beautifulsoup4            4.4.1                    py27_0  
bokeh                     0.12.0                   py27_0  
bottleneck                1.0.0               np110py27_1  
bzip2                     1.0.6                     vc9_3  [vc9]
chest                     0.2.3                    py27_0  
cloudpickle               0.2.1                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.1.6                    py27_0  
conda-env                 2.5.1                    py27_0  
geos                      3.4.2                     vc9_2  [vc9]  conda-forge
pyproj                    1.9.5.1                  py27_0    conda-forge
pyshp                     1.2.3                    py27_0    conda-forge
configparser              3.5.0b2                  py27_1  
console_shortcut          0.1.1                    py27_1  
curl                      7.49.0                    vc9_0  [vc9]
cycler                    0.10.0                   py27_0  
dask                      0.10.0                   py27_0  
datashader                0.3.0                    py27_0  
datashape                 0.5.2                    py27_0  
decorator                 4.0.10                   py27_0  
docutils                  0.12                     py27_2  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
freetype                  2.5.5                     vc9_1  [vc9]
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
h5py                      2.6.0               np110py27_0  
hdf5                      1.8.15.1                  vc9_4  [vc9]
heapdict                  1.0.0                    py27_1  
html5lib                  0.999                    py27_0  
imagesize                 0.7.1                    py27_0  
basemap                   1.0.8.dev0          np110py27_1    ioos
cyordereddict             1.0.0                    py27_0    ioos
h5netcdf                  0.2.2                    py27_0    ioos
netcdf4                   1.2.4               np110py27_1    ioos
python-dateutil           2.4.2                    py27_1    ioos
xarray                    0.7.3.dev0               py27_0    ioos
ipykernel                 4.3.1                    py27_0  
ipython                   4.2.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
jedi                      0.9.0                    py27_1  
jinja2                    2.8                      py27_1  
jpeg                      8d                        vc9_0  [vc9]
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.3.0                    py27_0  
jupyter_console           4.1.1                    py27_0  
jupyter_core              4.1.0                    py27_0  
launcher                  1.0.0                         4  
libnetcdf                 4.3.3.1                   vc9_4  [vc9]
libpng                    1.6.22                    vc9_0  [vc9]
libtiff                   4.0.6                     vc9_2  [vc9]
llvmlite                  0.11.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.6.0                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.1               np110py27_0  
menuinst                  1.4.1                    py27_0  
mistune                   0.7.2                    py27_0  
mkl                       11.3.3                        1  
msvc_runtime              1.0.1                     vc9_0  [vc9]
multipledispatch          0.4.8                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.0.1                    py27_0  
networkx                  1.11                     py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_1  
notebook                  4.2.1                    py27_0  
numba                     0.26.0              np110py27_0  
numexpr                   2.5.2               np110py27_1  
numpy                     1.10.4                   py27_2  
odo                       0.5.0                    py27_1  
openssl                   1.0.2h                    vc9_0  [vc9]
pandas                    0.18.1              np110py27_0  
partd                     0.3.4                    py27_0  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pickleshare               0.7.2                    py27_0  
pillow                    3.2.0                    py27_1  
pip                       8.1.2                    py27_0  
psutil                    4.3.0                    py27_0  
pycosat                   0.6.1                    py27_1  
pycrypto                  2.6.1                    py27_4  
pyflakes                  1.2.3                    py27_0  
pygments                  2.1.3                    py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_6  
pyreadline                2.1                      py27_0  
pytables                  3.2.2               np110py27_2  
python                    2.7.12                        0  
pytz                      2016.4                   py27_0  
pyyaml                    3.11                     py27_4  
pyzmq                     15.2.0                   py27_0  
qt                        4.8.7                     vc9_8  [vc9]
qtconsole                 4.2.1                    py27_0  
requests                  2.10.0                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.7                   py27_0  
scipy                     0.17.1              np110py27_1  
setuptools                23.0.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_2  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sphinx                    1.4.1                    py27_0  
sphinx_rtd_theme          0.1.9                    py27_0  
spyder                    2.3.9                    py27_0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np110py27_1  
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.0                    py27_0  
tornado                   4.3                      py27_1  
traitlets                 4.2.1                    py27_0  
vs2008_runtime            9.00.30729.1                  2  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                     vc9_3  [vc9]

**Comment by ocefpaf** [comment]
@jbosch-noaa is that from the `IOOS` environment or the root env? I cannot see `compliace_checker` in there :confused: 

BTW @rsignell-usgs and I made a few changes in the environment file. Maybe you could try to remove the one you have and try it again. Get the new file from:

https://github.com/ioos/conda-recipes/blob/master/environment.yml

and then

```shell
conda env remove -n IOOS
conda env create -f environment.yml
activate IOOS
```

**Comment by jbosch-noaa** [comment]
Ok - so below is all the output from my anaconda prompt today.  I activated the ioos environment and then installed compliance checker. When I do a "conda list" there, compliance checker shows up.  What is strange is that when I do a "!conda list" from my Spyder ipython console it seem to not get compliance checker in the list.  This is particularly frustrating because I installed Spyder while in the ioos environment from the anaconda prompt.  I thought if I did that then the ioos environment would always be activated when I opened Spyder.  Wow this is confusing.  


(C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2) C:\Users\jennifer.b
osch>activate ioos

(ioos) C:\Users\jennifer.bosch>conda install compliance-checker
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\jennifer.bosch\AppData\Loc
al\Continuum\Miniconda2\envs\ioos:

The following NEW packages will be INSTALLED:

    cf_units:           1.1-py27_0    ioos
    compliance-checker: 2.1.0-py27_3  ioos
    expat:              2.1.0-vc9_1   ioos [vc9]
    owslib:             0.11.0-py27_0 ioos
    petulant-bear:      0.2.0-py27_0  ioos
    udunits2:           2.2.20-vc9_1  ioos [vc9]
    wicken:             0.2.0-py27_0  ioos

Proceed ([y]/n)? y

Linking packages ...
INFO:progress.update:('cf_units', 2)#                                    |  28%
INFO:progress.update:('owslib', 3)##########                             |  42%
INFO:progress.update:('petulant-bear', 4)##########                      |  57%
INFO:progress.update:('wicken', 5)########################               |  71%
INFO:progress.update:('compliance-checker', 6)###################        |  85%
[      COMPLETE      ]|##################################################| 100%
INFO:progress.stop:None

(ioos) C:\Users\jennifer.bosch>compliance-checker --help
Could not load acdd = compliance_checker.acdd:ACDDBaseCheck : [UT_OPEN_ARG] Fail
ed to open UDUNITS-2 XML unit database : "No such file or directory"
Could not load cf = compliance_checker.cf.cf:CFBaseCheck : cannot import name co
nfig
usage: compliance-checker-script.py [-h] [--test {ioos}]
                                    [--criteria [{lenient,normal,strict}]]
                                    [--verbose] [-f {text,html,json}]
                                    [-o OUTPUT] [-V]
                                    [dataset_location [dataset_location ...]]

positional arguments:
  dataset_location      Defines the location of the dataset to be checked.

optional arguments:
  -h, --help            show this help message and exit
  --test {ioos}, -t {ioos}, --test= {ioos}, -t= {ioos}
                        Select the Checks you want to perform.
  --criteria [{lenient,normal,strict}], -c [{lenient,normal,strict}]
                        Define the criteria for the checks. Either Strict,
                        Normal, or Lenient. Defaults to Normal.
  --verbose, -v         Increase output. May be specified up to three times.
  -f {text,html,json}, --format {text,html,json}
                        Output format
  -o OUTPUT, --output OUTPUT
                        Output filename
  -V, --version         Display the IOOS Compliance Checker version
                        information.

(ioos) C:\Users\jennifer.bosch>compliance-checker --test=acdd compliance_checker
/tests/data/ru07-20130824T170228_rt0.nc
Could not load acdd = compliance_checker.acdd:ACDDBaseCheck : [UT_OPEN_ARG] Fail
ed to open UDUNITS-2 XML unit database : "No such file or directory"
Could not load cf = compliance_checker.cf.cf:CFBaseCheck : cannot import name co
nfig
usage: compliance-checker-script.py [-h] [--test {ioos}]
                                    [--criteria [{lenient,normal,strict}]]
                                    [--verbose] [-f {text,html,json}]
                                    [-o OUTPUT] [-V]
                                    [dataset_location [dataset_location ...]]
compliance-checker-script.py: error: argument --test/-t/--test=/-t=: invalid cho
ice: 'acdd' (choose from 'ioos')

(ioos) C:\Users\jennifer.bosch>conda install -c conda-forge compliance-checker
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\jennifer.bosch\AppData\Loc
al\Continuum\Miniconda2\envs\ioos:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    isodate-0.5.4              |           py27_0          39 KB  conda-forge
    pygeoif-0.6                |           py27_1          31 KB  conda-forge
    compliance-checker-2.2.0   |           py27_1         589 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         660 KB

The following NEW packages will be INSTALLED:

    isodate:            0.5.4-py27_0 conda-forge
    pygeoif:            0.6-py27_1   conda-forge

The following packages will be UPDATED:

    compliance-checker: 2.1.0-py27_3 ioos        --> 2.2.0-py27_1 conda-forge

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
isodate-0.5.4- 100% |###############################| Time: 0:00:00   1.55 MB/s
pygeoif-0.6-py 100% |###############################| Time: 0:00:00   1.58 MB/s
compliance-che 100% |###############################| Time: 0:00:00   3.75 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

(ioos) C:\Users\jennifer.bosch>conda list
# packages in environment at C:\Users\jennifer.bosch\AppData\Local\Continuum\Min
iconda2\envs\ioos:
#
alabaster                 0.7.8                    py27_0
anaconda-client           1.4.0                    py27_0
babel                     2.3.3                    py27_0
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
beautifulsoup4            4.4.1                    py27_0
bokeh                     0.12.0                   py27_0
bottleneck                1.1.0               np111py27_0
bzip2                     1.0.6                     vc9_3  [vc9]
chest                     0.2.3                    py27_0
cloudpickle               0.2.1                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.7                    py27_0
basemap                   1.0.8.dev0          np111py27_1    conda-forge
compliance-checker        2.2.0                    py27_1    conda-forge
curl                      7.48.0                    vc9_2  [vc9]  conda-forge
geos                      3.4.2                     vc9_2  [vc9]  conda-forge
hdf4                      4.2.11                    vc9_0  [vc9]  conda-forge
isodate                   0.5.4                    py27_0    conda-forge
pygeoif                   0.6                      py27_1    conda-forge
pyproj                    1.9.5.1                  py27_0    conda-forge
pyshp                     1.2.3                    py27_0    conda-forge
thredds_crawler           1.4.0                    py27_0    conda-forge
configparser              3.5.0b2                  py27_1
cycler                    0.10.0                   py27_0
dask                      0.10.0                   py27_0
datashader                0.3.0                    py27_0
datashape                 0.5.2                    py27_0
decorator                 4.0.10                   py27_0
docutils                  0.12                     py27_2
entrypoints               0.2.2                    py27_0
enum34                    1.1.6                    py27_0
freetype                  2.5.5                     vc9_1  [vc9]
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
get_terminal_size         1.0.0                    py27_0
h5py                      2.6.0               np111py27_0
hdf5                      1.8.15.1                  vc9_4  [vc9]
heapdict                  1.0.0                    py27_1
holoviews                 1.5.0                    py27_0
html5lib                  0.999                    py27_0
imagesize                 0.7.1                    py27_0
cf_units                  1.1                      py27_0    ioos
cyordereddict             1.0.0                    py27_0    ioos
expat                     2.1.0                     vc9_1  [vc9]  ioos
h5netcdf                  0.2.2                    py27_0    ioos
owslib                    0.11.0                   py27_0    ioos
petulant-bear             0.2.0                    py27_0    ioos
protobuf                  3.0.0b2.post2        py27_vc9_3  [vc9]  ioos
python-dateutil           2.4.2                    py27_1    ioos
siphon                    0.4.0                    py27_0    ioos
udunits2                  2.2.20                    vc9_1  [vc9]  ioos
wicken                    0.2.0                    py27_0    ioos
xarray                    0.7.3.dev0               py27_0    ioos
ipykernel                 4.3.1                    py27_0
ipython                   4.2.0                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
jedi                      0.9.0                    py27_1
jinja2                    2.8                      py27_1
jpeg                      8d                        vc9_0  [vc9]
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.3.0                    py27_0
jupyter_console           4.1.1                    py27_0
jupyter_core              4.1.0                    py27_0
libnetcdf                 4.3.3.1                   vc9_4  [vc9]
libpng                    1.6.22                    vc9_0  [vc9]
libtiff                   4.0.6                     vc9_2  [vc9]
llvmlite                  0.12.1                   py27_0
locket                    0.2.0                    py27_1
lxml                      3.6.0                    py27_0
markupsafe                0.23                     py27_2
matplotlib                1.5.1               np111py27_0
menuinst                  1.4.1                    py27_0
mistune                   0.7.2                    py27_0
mkl                       11.3.3                        1
multipledispatch          0.4.8                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.0.1                    py27_0
netcdf4                   1.2.2               np111py27_0
networkx                  1.11                     py27_0
nose                      1.3.7                    py27_1
notebook                  4.2.1                    py27_0
numba                     0.27.0              np111py27_0
numexpr                   2.6.0               np111py27_0
numpy                     1.11.1                   py27_0
odo                       0.5.0                    py27_1
openssl                   1.0.2h                    vc9_0  [vc9]
pandas                    0.18.1              np111py27_0
param                     1.3.2                    py27_0
partd                     0.3.4                    py27_0
path.py                   8.2.1                    py27_0
pathlib2                  2.1.0                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
pickleshare               0.7.2                    py27_0
pillow                    3.2.0                    py27_1
pip                       8.1.2                    py27_0
psutil                    4.3.0                    py27_0
pyflakes                  1.2.3                    py27_0
pygments                  2.1.3                    py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      4.11.4                   py27_6
pyreadline                2.1                      py27_0
pytables                  3.2.2               np111py27_4
python                    2.7.12                        0
pytz                      2016.4                   py27_0
pyyaml                    3.11                     py27_4
pyzmq                     15.2.0                   py27_0
qt                        4.8.7                     vc9_8  [vc9]
qtconsole                 4.2.1                    py27_0
requests                  2.10.0                   py27_0
rope                      0.9.4                    py27_1
scipy                     0.17.1              np111py27_1
setuptools                23.0.0                   py27_0
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_2
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sphinx                    1.4.1                    py27_0
sphinx_rtd_theme          0.1.9                    py27_0
spyder                    2.3.9                    py27_0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.6.1               np111py27_1
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.0                    py27_0
tornado                   4.3                      py27_1
traitlets                 4.2.1                    py27_0
vs2008_runtime            9.00.30729.1                  2
wheel                     0.29.0                   py27_0
zlib                      1.2.8                     vc9_3  [vc9]

(ioos) C:\Users\jennifer.bosch>

**Comment by rsignell-usgs** [comment]
I just tried to build using this environment.yml and got the dreaded: 
```
Linking packages ...
Error: ERROR: placeholder 'C:/conda/envs/_build' too short in: hdf5-1.8.17-vc9_2
```

**Comment by jbosch-noaa** [comment]
For confirmation I double check what env I am in at my Spyder ipython prompt:

 !conda info --env
# conda environments:
#
IOOS                     C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\envs\IOOS
bokeh_tutorial           C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\envs\bokeh_tutorial
root                  *  C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2


Grrrrr....  I guess I am operating in the root env.

So I changed it.

!activate ioos

And it still doesn't see it!

!conda info --env
# conda environments:
#
IOOS                     C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\envs\IOOS
bokeh_tutorial           C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\envs\bokeh_tutorial
root                  *  C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2

**Comment by ocefpaf** [comment]
@jbosch-noaa I can see that `udunits2` is installed. So the issue is some sort of path confusion. Not sure what yet. Do you have two (or more) partitions by any chance? I do remember an issue on Windows where the `udunits2` data could not be accessed called from another disk partition.

I just tried:

```shell
conda env create -f environment.yml
activate I
compliance-checker --test=acdd sal.nc
```

Note that I had to shorten the env name b/c of the `hdf5` issue @rsignell-usgs mentioned. There is no solution for that right now as it is a mix of a bug in conda-build and how `conda-forge` is packaging `hdf5`. 

Read about it [here](https://github.com/conda-forge/geopandas-feedstock/issues/11) and complain about it [here](https://github.com/conda-forge/hdf5-feedstock/issues/27).

Everything worked for me on a Win32 machine, running from the same disk partition, and with the files: https://dl.dropboxusercontent.com/u/4411725/environment.yml and https://dl.dropboxusercontent.com/u/4411725/sal.nc


![cc](https://cloud.githubusercontent.com/assets/950575/17074932/e2839012-505a-11e6-9a7d-f22f7b5b282c.png)

**Comment by jbosch-noaa** [comment]
I installed the environment as you said and got the following error when I activated the environment but was still able to run the compliance checker:

(C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2) C:\Users\jennifer.bosch>activate I

(I) C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\envs\I\etc\conda\
activate.d>if not defined GDAL_DATA (
set GDAL_DATA="C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\envs\I
\etc\conda\activate.d\\..\..\..\Library\share\gdal"
 set _CONDA_SET_GDAL_DATA=1
)

**Comment by ocefpaf** [comment]
That is new. I am passing it along to the `gdal` maintainer in `conda-forge`.

At least `compliance-checker` is OK now :sweat_smile:

**Comment by ocefpaf** [comment]
@jbosch-noaa was that all you got in the screen? I am trying to reproduce that, but I cannot. It seems that `gdal` activation is echoing the commands on the screen and those seems like the correct commands there. I wonder if the error comes right after that.

**Comment by jbosch-noaa** [comment]
@ocefpaf  - yes,  that was everything. The error came right after I activated the environment.  I then tried to run the compliance checker anyway and it seemed to work.

(I) C:\Users\jennifer.bosch>compliance-checker --test=acdd sal.nc
Running Compliance Checker on the dataset from: sal.nc


--------------------------------------------------------------------------------

                     The dataset scored 23 out of 66 points

                             during the acdd check

--------------------------------------------------------------------------------

                               Scoring Breakdown:



                                 High Priority

--------------------------------------------------------------------------------

    Name                            :Priority: Score
Conventions                             :3:     1/2
keywords                                :3:     0/1
summary                                 :3:     0/1
title                                   :3:     1/1
varattr                                 :3:    20/28


                                Medium Priority

--------------------------------------------------------------------------------
.. blah blah blah

**Comment by ocefpaf** [comment]
@jbosch-noaa I believe that conda is jus echoing the commands it is issuing when activating the env vars for `gdal`. That is not an error.

**Comment by jbosch-noaa** [comment]
Ok @ocefpaf  and @lukecampbell  I'm reopening this issue because I still ran in to the problem - perhaps this is because of known issues with the conda update?  

So after I successfully set-up the new "I" environment and ran the compliance checker as instructed above, I decided to install Jupyter Notebook to continue working in this new "I" environment.  

conda install ipython-notebook --channel conda-forge

Then I recalled that there was this little bug where I couldn't move into a folder when I'm in the notebook.  I learned at SciPy that I just needed to update conda to fix the problem

conda update --all

At that point I thought I was totally set.  I started up the notebook, navigated to the notebook where I was trying to run the compliance checker on date from the NDBC HRF THREDDS and I got the same error.  GRRRR.  I then tried to re-run the compliance checker on the sal.nc file that Filipe had me download.  Here is my output.

(I) C:\Users\jennifer.bosch>compliance-checker --test=acdd sal.nc
Could not load acdd = compliance_checker.acdd:ACDDBaseCheck : [UT_OPEN_ARG] Fail
ed to open UDUNITS-2 XML unit database : "No such file or directory"
Could not load cf = compliance_checker.cf.cf:CFBaseCheck : cannot import name co
nfig
usage: compliance-checker-script.py [-h] [--test {gliderdac,ioos}]
                                    [--criteria [{lenient,normal,strict}]]
                                    [--verbose] [-f {text,html,json}]
                                    [-o OUTPUT] [-V]
                                    [dataset_location [dataset_location ...]]
compliance-checker-script.py: error: argument --test/-t/--test=/-t=: invalid cho
ice: 'acdd' (choose from 'gliderdac', 'ioos')

I am guessing that in order to run the compliance checker a  I can't update my conda.  That makes things a bit complicated.

**Comment by ocefpaf** [comment]
The problem was: `conda install ipython-notebook --channel conda-forge`

That probably caused lots of downgrades there. You should use `conda install jupyter --channel conda-forge`. That should give you all you need (including the `notebook` which is no longer called `ipython-notebook` :wink:).

BTW `jupyter` and the `notebook` should already be in the `env`.  You did not had the folder navigation when you called `jupyter notebook` right after the `env` creation? Let me know b/c we may need to update the recipe instead.

**Comment by jbosch-noaa** [comment]
Correct.  After installing the environment and calling jupyter notebook I did not have folder navigation.  That's what prompted me to update everything.

Thank you for correcting me on my vocabulary (notebook vs ipython-notebook). This is soooo confusing! :)

**Comment by ocefpaf** [comment]
> This is soooo confusing! :)

Oh yes... I am "in" this community and I am always confused.

I will look into it folder navigation and get back to you.

**Comment by ocefpaf** [comment]
> I did not have folder navigation. 

@jbosch-noaa I finally got my hands on a Windows computer to test this.

All the messages you are seeing are b/c of a change in latest miniconda on Windows that echos everything miniconda is doing (like a debug mode). Not sure why Continuum enabled made that by default, but it does not hurt to leave it there.

BTW here is how the folder navigation looks like in the `Jupyter notebook`:

![folder_navigation](https://cloud.githubusercontent.com/assets/950575/17263320/d0845f8e-55b6-11e6-9a93-39885ac7f5b2.png)

The first red circle is the home button and the other three are folders and you can click to enter. Like we mention at SciPy you cannot go into folders that are "parent" to the folder where you started the `jupyter notebook`. You can only forward from there. The "home" icon will always bring you back to the folder where you started.

Hope that helps!

PS: I just realized that maybe you are expecting a GUI interface. I am not sure if  JupyterLab will have that. (JupyterLab is still experimental and I have not tested it yet.)

http://jupyterlab-tutorial.readthedocs.io/en/latest/index.html

**Comment by jbosch-noaa** [comment]
Thanks @ocefpaf  for clarifying that it's miniconda updates.  I understand the navigation in jupyter.  The problem I was having was that when I activated the IOOS environment it would revert back to the old jupyter where you couldn't navigate.  I then updated jupyter and it fixed that problem for that session but it doesn't always seen to hold.  Additionally, I am having even more issues with activating the ioos env.  Like it not activating:





![ioos_env_problem](https://cloud.githubusercontent.com/assets/13106516/17264021/5756466c-55b2-11e6-8efb-d25e79a2222c.JPG)


So I'm getting a new laptop next week.  I will have to reinstall everything so lets see if I am still having these problems when I do a clean install.

**Comment by ocefpaf** [comment]
You are activating from an opened instance of the notebook, right? Not sure of that is supposed to work b/c the notebook cannot change the environment in place. (Unless we specify different kernels, but that is not a simple task!)

We can do the installation in the new laptop over a Skype session and try to sort out all the problems you are having.

**Comment by jbosch-noaa** [comment]
Ok. I didn't realize I couldn't activate an environment in a notebook.

So I am scheduled to get my new laptop on Thursday of this week.  Perhaps Friday afternoon we can install miniconda.  FYI - For better or worse, my new laptop will be running Windows 10.

**Comment by ocefpaf** [comment]
> Perhaps Friday afternoon we can install 

Sounds good to me.

> For better or worse, my new laptop will be running Windows 10.

Better! Soon Windows 10 will have a built in `bash`!!

**Comment by lukecampbell** [comment]
Did this get resolved?

**Comment by jbosch-noaa** [comment]
Yes @lukecampbell .  Filipe and I sorted it out.
