### ISSUE TITLE
Save text output

### ISSUE THREAD

**Issue by ocefpaf** [ioos/compliance-checker#290]
@lukecampbell and @daf I am helping @jbosch-noaa with some notebooks in

https://github.com/ioos/notebooks_demos/pull/21

and I noticed that simple text outputs are only redirected to `stdout`. There is on API to save it to a file.
Correct me if I am wrong but I could not see it [here](https://github.com/ioos/compliance-checker/blob/7276abba102e2ef6cb390d49ba0c38726f625913/compliance_checker/runner.py#L43-L50
).

I do know that in CLI interface it is easy to redirect to a file but it would be nice to be able to do that from class method too. Not also that the docs give the idea that this is possible and the error message [here](https://github.com/ioos/compliance-checker/blob/7276abba102e2ef6cb390d49ba0c38726f625913/compliance_checker/runner.py#L53) is not very helpful.

**Comment by lukecampbell** [comment]
It looks like it only outputs the plain text to stdout. That's probably not completely desirable.

**Comment by jbosch-noaa** [comment]
@lukecampbell  - For some of us, the output doesn't have to be pretty.  Plain text is ok.  I just need it to go to a file instead of printing on screen.  With that said, if it is easier to output to an HTML file, that's fine also.  Either way, the directions in the readme file is misleading and confusing.

**Comment by ocefpaf** [comment]
@lukecampbell or @daf are either of you working on this? If not I may try it next week but I want o avoid duplicating efforts here.

**Comment by lukecampbell** [comment]
I probably won't have time for it this week but it's definitely on my radar. If you could tackle it, that would be a big help!
