### ISSUE TITLE
What does "NCEI Time Series Incomplete" mean?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/compliance-checker#291]
When I checked out the online compliance checker at
http://data.ioos.us/compliance/index.html
I see a bunch of new tests that can be run.

So as a user, I'm wondering what things like  "NCEI Time Series Incomplete" means?

Could there be links to some docs or some more descriptive text to explain these tests on the online tool?

**Comment by abirger** [comment]
@rsignell-usgs , I believe you may find the descriptions [here ](https://www.nodc.noaa.gov/data/formats/netcdf/v1.1/), or [here](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/).

**Comment by lukecampbell** [comment]
@rsignell-usgs we wrapped up the implementation, you'll see the effects when we wrap up 2.3 and update the site.

![screen shot 2016-09-13 at 10 48 17 am](https://cloud.githubusercontent.com/assets/1155163/18478550/ae0ae15a-799f-11e6-8ca4-a78dcd93e9b3.png)
