### ISSUE TITLE
Documentation on installation.

### ISSUE THREAD

**Issue by dpsnowden** [ioos/compliance-checker#302]
#300 was closed with a note that a new release was issued.  I see the [release notes here](https://github.com/ioos/compliance-checker/releases/tag/2.2.1) but I don't see an indication on the notes about where to get the install.  There is some outdated info on the README.md about binstar etc (or at least I think it's outdated).  

Shane recently announced a new i52N release on [ioos_tech](https://groups.google.com/forum/#!topic/ioos_tech/u57ztLpo3N0).  Which had a good write up with pointers to relevant docs.  Can we get something similar for compliance checker (and all releases)?  I'd like to start announcing our releases more widely but I think we need to include a little more hand holding.  Question is, where does it belong?  README.md?  github.io?  Other?

**Comment by ocefpaf** [comment]
I just read the README and that is dangerously outdated. Fixing it now...

**Comment by jbosch-noaa** [comment]
Thanks for noting this @dpsnowden .  This release just came out yesterday and with the quick pack-up  of our office I did not have a chance to follow up with @lukecampbell and @kknee about it.

@ocefpaf  - Should ASA be updating this README file? They released the update.

**Comment by ocefpaf** [comment]
> @ocefpaf - Should ASA be updating this README file? They released the update.

I think I should update the `conda` install instruction first. Then @lukecampbell can review and take care of the rest :wink:

**Comment by jbosch-noaa** [comment]
Thanks @ocefpaf .  Once @lukecampbell is finished with his review, the release can be announced over [ioos_tech](https://groups.google.com/forum/#!topic/ioos_tech/u57ztLpo3N0).  

Kelly mentioned @Bobfrat was working on the V. 2.3 release.  We should probably loop him in to this thread also.  When V 2.3 comes out in October we will need to have a well documented set of release notes and an email out to  [ioos_tech](https://groups.google.com/forum/#!topic/ioos_tech/u57ztLpo3N0) as well.

**Comment by kknee** [comment]
@jbosch-noaa copy that, we'll make sure to formalize the release for 2.3.

This past one was pretty small and sudden, thus the lack of fanfare.

**Comment by kknee** [comment]
@jbosch-noaa @dpsnowden  - see IOOS Tech email sent out by @lukecampbell and duplicated here: https://github.com/ioos/compliance-checker/releases
