### ISSUE TITLE
output in several formats on one run

### ISSUE THREAD

**Issue by cehbrecht** [ioos/compliance-checker#313]
i'm using the compliance-checker as a process in a Web Processing Service.  Currently you can set only one output format (`json`, `html` or `text`). It would be nice if i could have multiple output formats on the same run (like `[json, html]`). 

Are the `text` and `html` formats generated from the `json` format?

**Comment by lukecampbell** [comment]
They're all generated from an internal structure that looks very much like the json.

**Comment by benjwadams** [comment]
This would get pretty confusing.  How would one invoke compliance checker to do this from the command line, for example?

**Comment by cehbrecht** [comment]
One could add a list of wanted output formats on the command line:
```
$ cchecker --format html,csv
```

https://docs.python.org/3.5/library/argparse.html#nargs

I would see the json output as the essential result document of the compliance-checker. Other formats are more optional and for display (HTML). If one could produce the other output formats (HTML) from the json (or yaml) document then it would not be necessary to run the checks again just to have another format.

**Comment by Bobfrat** [comment]
@cehbrecht i'm a little confused. Are you saying if you can produce the other formats from JSON then we can close this issue? One can produce the other formats from JSON. Here's how we do that in the web version:

[Text](https://github.com/ioos/compliance-checker-web/blob/master/cchecker_web/processing.py#L46-L78) that we produce for text downloads

[HTML](https://github.com/ioos/compliance-checker-web/blob/master/cchecker_web/static/js/partials/Report.html) that we render

We do something similar with the HTML in this repo using [jinja2 templates](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/data/templates/ccheck.html.j2)
