### ISSUE TITLE
check report for several files

### ISSUE THREAD

**Issue by cehbrecht** [ioos/compliance-checker#315]
currently the compliance checker generates a check report for a single input file only (text, json ,html). 

Usually i need to run the checker on many files and it would be nice if i could return a combined report. In case of text one could concatenate the reports (with the filename), in case of json one would have a dictionary of reports, and in case of html there is more to do ...

**Comment by Bobfrat** [comment]
I think this is a valuable feature but updating the JSON output to support it would break backwards compatibility. I know some folks have applications that use the json output so they would need to be  adjust accordingly, including the compliance checker web application. As part of the scoring overhaul I was hoping not to break backwards compatibility but I don't see anyway around it if we were to include this feature. 

Here's an example JSON output (truncated severely for brevity):

```
{
  "cf:1.6": {
    "scored_points": 119, 
    "low_count": 0, 
    "high_priorities": [
      {
        "weight": 3, 
        "children": [], 
        "msgs": [], 
        "value": [
          5, 
          5
        ], 
        "name": "§2.2 Valid netCDF data types"
      },
    ],
    "medium_priorities": [
      {
        "weight": 2, 
        "children": [], 
        "msgs": [], 
        "value": [
          20, 
          20
        ], 
        "name": "§2.3 Naming Conventions for attributes"
      },
    ], 
    "medium_count": 3, 
    "source_name": "compliance_checker/tests/data/2d-regular-grid.nc", 
    "high_count": 0
  }
}
```

So we could update this JSON output structure to be a list containing the datasets that were run. 

Right now [we do have the ability to run multiple datasets](https://github.com/ioos/compliance-checker/pull/547), but the results aren't concatenated, you must specify as many output files as input datasets. @cehbrecht Is this sufficient? 

The output structure is starting to get very complicated as we've had requests to support running multiple checks on a single dataset (this is done and results are concatenated into a single file), multiple datasets (done but doesn't concatenate) and also [multiple output formats](https://github.com/ioos/compliance-checker/issues/313). If a user asks for multiple checks and multiple output formats for multiple datasets, what does the output look like and what does the command look like? Do we give users the option to concatenate OR specify multiple output files on multiple datasets?  

@kwilcox @daf @jbosch-noaa @benjwadams @brianmckenna @abirger @mhidas @mwengren  thoughts?

**Comment by cehbrecht** [comment]
@Bobfrat 
Thanks for looking into this :) I lost a bit the focus because I'm just partly involved in compliance checking of our climate data (CMIP5, CMIP6, ...). @agstephens is working on the "next generation" compliance checker (... CMIP7) based on the IOOS one (which has a good and understandable design). Ag may have more appropriate comments on this.

So, here are the uses case I'm aware of:
* run on a single file (dataset) -> single json output (or other formats).
* run on a single dataset consisting of multiple files -> single json output.
* run on several datasets given on command line -> an output file per dataset + a single summary json document.
* run on a directory structure containing netcdf files, crawl the directory, filter input netcdf files -> an output file per dataset + a single summary json document.

I understand you can't change the current ioos compliance checker use case working on single files. But one could add a wrapper to handle multiple datasets which calls the real compliance checker. It would be nice to have a common wrapper ... otherwise we may do duplicate work.

**Comment by agstephens** [comment]
Hi @Bobfrat and @cehbrecht, I agree with the set of use cases above. We have thought about this issue but we haven't written any code. 

One way to break down the problem could be:
 - If you need a summary of results (for multiple *datasets*):
   - you must select JSON output
   - the summary tool/option will always read in a set of JSON records and generate the summary from that.

That would rule out managing lots of different ways of generating summaries. You could request a summary in two ways:
 1. As part of the initial checker run (i.e. check all datasets and then summarise)
 2. By pointing the checker at a set of JSON output files and using `--summary`

**Comment by benjwadams** [comment]
#555 implements the ability to run compliance checker reports for multiple files with input to one output source for the 'text', 'html', and 'json_new' (new) formats.  It's not supported for 'json' format at the moment as it would break the expected output for clients using the format as part of a program.  Going to close this issue since the features requested have been added.
