### ISSUE TITLE
ACDD check in conflict with CF-1.6

### ISSUE THREAD

**Issue by castelao** [ioos/compliance-checker#319]
According to CF-1.6, coordinate variables shouldn't have the attribute _FillValue, but acdd.check_vertical_extents() requires it.

**Comment by lukecampbell** [comment]
Currently the ACDD check doesn't have the logic necessary for differentiating between geophysical variables and coordinate variables. In our 3.0 milestone, I aim to integrate the logic needed to identify all the types of variables, and features into the core of the project to improve the checks across the board.

**Comment by castelao** [comment]
Hi @lukecampbell , that sounds great. For now, is it necessary to explicitly create a masked array using the _FillValue? Otherwise, would my patch be fine for pre-3.0? Shall I open a pull request?

**Comment by lukecampbell** [comment]
If you could make a pull-request to the master branch we could review it and test it for integration.

**Comment by lukecampbell** [comment]
I have fix for this shortly, it'll probably be integrated early next week.

**Comment by lukecampbell** [comment]
@castelao could you post a sample dataset that you were using where you identified the issue? I think I solved it with the refactor of ACDD.
