### ISSUE TITLE
JSON output to a filename overwrites for each check group

### ISSUE THREAD

**Issue by kwilcox** [ioos/compliance-checker#322]
```
import json
imoprt tempfile
from compliance_checker.runner import ComplianceChecker, CheckSuite

_, outfile = tempfile.mkstemp()
return_value, errors = ComplianceChecker.run_checker(
    ds_loc=netcdf_file,
    checker_names=['acdd', 'cf'],
    verbose=True,
    criteria='normal',
    output_format='json',
    output_filename=outfile
)
```

The file is overwritten for each check: https://github.com/ioos/compliance-checker/blob/master/compliance_checker/runner.py#L145. We can't just make that open in append mode because then the file wouldn't be valid JSON.

I was thinking about adding a top level dictionary to the JSON output with the test name, ie.

```
{
    'cf' : [cf group output],
    'acdd' : [acdd group output]
}
```

@lukecampbell @daf @ocefpaf Thoughts?  Will PR so it makes it into next release if we can agree on an output format.

**Comment by lukecampbell** [comment]
Yeah, I like that idea. I'll need to patch compliance checker web for the change in format.

**Comment by kwilcox** [comment]
What needs to be updated? I assumed CC-web used the HTML output?

https://github.com/ioos/compliance-checker-web/search?utf8=%E2%9C%93&q=json

**Comment by kwilcox** [comment]
Looks like it uses its own output format: https://github.com/ioos/compliance-checker-web/blob/master/cchecker_web/processing.py#L22-L39

**Comment by ocefpaf** [comment]
> I was thinking about adding a top level dictionary to the JSON output with the test name, ie.

:+1:

**Comment by kwilcox** [comment]
Fix here: https://github.com/ioos/compliance-checker/pull/323
