### ISSUE TITLE
CF: "boundary variables" don't need coordinates

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#325]
I have received a file that has:

```
dimensions:
        TIME = 21 ;
        nv = 2 ;
variables:
        double TIME(TIME) ;
                ...
                TIME:bounds = "TIME_bnds" ;
        double TIME_bnds(TIME, nv) ;
```

According to [CF section 7.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#cell-boundaries) this is correct, and the `TIME_bnds` variable doesn't need to have "attributes such as `long_name` and `units`". Presumably that includes the `coordinates` attribute too.
However, the CF checker complains:

```
§9.5 Discrete Geometry                 :2:    10/11 :  
    TIME_bnds                          :2:     0/ 1 :  
        check_coordinates              :2:     0/ 1 : The variable TIME_bnds
                                                      does not have associated
                                                      coordinates
```

**Comment by lukecampbell** [comment]
The CF Checker doesn't deal with gridded data very well just yet. This should be taken care of in the 3.0 release.

**Comment by lukecampbell** [comment]
@benjwadams this should be fixes as part of #349

**Comment by benjwadams** [comment]
Did we merge something to fix this?  With all the PR activity I've sort of lost track.

**Comment by lukecampbell** [comment]
@mhidas do you have a sample dataset?

**Comment by benjwadams** [comment]
This wasn't fixed as part of #349 as that dealt with implementation of the `bounds` attribute.   I will make a separate branch to fix this issue.

**Comment by benjwadams** [comment]
@mhidas, I tried reproducing this by taking the `tests/data/grid-boundaries` CDL and removing units from the bounds variables, but was unable to reproduce the behavior you mentioned against the current master branch.  If you have another dataset I could test against it'd be helpful as well.

**Comment by mhidas** [comment]
@benjwadams I'm a bit confused. I just re-ran the CF checker on the file in question and now it passes all checks! Even when I go back to version 2.2.0, which is what we were using at the time.

However, I did manage to construct a simple example that shows the original issue:
```
netcdf test {
dimensions:
    time = 2;
    nv = 2;
variables:
    double time(time);
        time:standard_name = "time";
        time:axis = "T";
        time:units = "seconds since 1970-01-01T00:00:00Z";
        time:calendar = "gregorian";
        time:bounds = "time_bnds";
    double time_bnds(time, nv);
    float lat;
        lat:standard_name = "latitude";
        lat:units = "degrees_north";
        lat:axis = "Y";
    float lon;
        lon:standard_name = "longitude";
        lon:units = "degrees_east";
        lon:axis = "X";
    float temperature(time);
        temperature:standard_name = "sea_water_temperature";
        temperature:units = "deg_C";
        temperature:coordinates = "time lat lon";

// global attributes:
        :featureType = "timeSeries" ;
        :Conventions = "CF-1.6" ;
}
```
Up to the bugfix version 2.3.1, this gives:
```
§3.1 Variables contain valid CF Units  :3:     0/ 1 : unknown units type (None)
                                                      for time_bnds
§9.5 Discrete Geometry                 :2:     1/ 3 :  
    ...
    time_bnds                          :2:     0/ 1 :  
        check_coordinates              :2:     0/ 1 : The variable time_bnds
                                                      does not have associated
                                                      coordinates
```

But these do go away when I do the check using the current master branch. So I guess we can close this.
