### ISSUE TITLE
Check for ugrid compliance

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/compliance-checker#33]
Eventually it would be nice to check for UGRID 0.9 compliance
https://github.com/ugrid-conventions/ugrid-conventions/blob/v0.9.0/ugrid-conventions.md
perhaps using some code from pyugrid
https://github.com/pyugrid/pyugrid

Is that on the roadmap?

**Comment by kwilcox** [comment]
@lukecampbell are you working on this? Can it please be an external library simliar to https://github.com/ioos/cc-plugin-sgrid so we can track the standard outside of compliance-checker?

**Comment by daf** [comment]
This issue was created before plugins were a thing, it should absolutely be a plugin.

**Comment by daf** [comment]
Btw with the way plugins are implemented, you could feasibly ship a CC plugin in pyugrid/pysgrid instead of a separate project, if that makes more sense for the project.

**Comment by ocefpaf** [comment]
> pyugrid/pysgrid instead of a separate project

:+1: to that.

ping @rsignell-usgs

**Comment by kwilcox** [comment]
@daf true, shipping the `Checker` classes along with `pysgrid` and `pyugrid` would be slick. I was concerned about adding a ton of dependencies to projects that only needed the checkers. I'll do it as a separate repo for now and blame someone else for the decision if it ends up being a bad one.

**Comment by daf** [comment]
It would have to be done as an "optional" style thing, which I have no idea how to do properly in python packaging.

**Comment by lukecampbell** [comment]
Yeah it would be a new plugin cc-plugin-ugrid. It's part of our 2.1 release plan.

**Comment by kwilcox** [comment]
@lukecampbell Is it planned for a future milestone? I don't see it in 2.1 or 3.0.

**Comment by lukecampbell** [comment]
Not that I know of.

**Comment by dpsnowden** [comment]
I think it should be on the roadmap but I'm not sure when it can actually get assigned to a milestone or the relative priority.  SGRID too.  It looks like it was on the 2.1 release plan but was removed.  Not sure of the relative priority of this vice other new features.

What was the discussion on whether it was better implemented as part of a pyugrid/pysgrid vice CC plugin?

**Comment by lukecampbell** [comment]
It's certainly still a goal of the compliance-checker and is very likely the next milestone we tackle, but I can't comment on a name for this milestone or begin to make assumptions about when it can be tackled. 

If I recall correctly, we came to a fork at the conclusion of 2.1, whether we should pursue ugrid/sgrid checkers or if we should tackle several of the core issues in compliance-checker, namely with CF. My argument in favor of refactoring CF was that once it was complete, as it is now in 3.0, we can leverage all of those capabilities in subsequent plugins. Things like feature detection, discrete geometry descriptions, etc.

Now that the work has been done to improve CF and integrate powerful code that can accurately reason about arbitrary datasets, creating additional plugins will be easier and more consistent.

**Comment by kknee** [comment]
UGRID actually one of the last outstanding tasks on our current roadmap, but it is not currently part of a release plan.  It kept getting bumped for other priorities, but as @lukecampbell we're in a good place now to move forward if a UGRID plugin is helpful to the community.

@kwilcox looks like you started a SGRID plug-in last winter.  What's the status of that?

**Comment by dpsnowden** [comment]
@kwilcox @rsignell-usgs It looks like this is scheduled again in Release 3.1.  Can you tell me the status of the SGRID checker?  Are those two things both mature enough to include in the same release or is SGRID somehow less mature?  

ping @Bobfrat @kknee @jbosch-noaa

**Comment by kwilcox** [comment]
I implemented (6) SGRID checks in the initial plugin and hoped someone would find it useful enough to add the rest. I haven't needed it and thus haven't dedicated any additional spare time to it.

The architecture of compliance-checker allows plugins (ugrid/sgrid/glider/etc) to release on different schedules and carry different versions from this repo. Releasing compliance-checker won't affect the plugins unless it breaks backwards compatibility and releasing plugins won't affect compliance-checker. If you are talking "Release 3.1" as a project management milestone and not a software version then I would lean towards not including SGRID unless you have the cycles for someone to work on it a bit more.

**Comment by lukecampbell** [comment]
I can't remember exactly but I thought we were waiting on a formal review or approval of the standards UGRID/SGRID before finishing plugins for them. It's been a while so I can't recall if that's entirely accurate.

**Comment by daf** [comment]
Also my previous comment still stands:

> with the way plugins are implemented, you could feasibly ship a CC plugin in pyugrid/pysgrid instead of a separate project, if that makes more sense for the project.

Meaning it's not necessary to ship them alongside the base compliance-checker itself, unless it makes more sense here.  I see arguments on both sides.

**Comment by brianmckenna** [comment]
Initial version checking required topology attributes.

We need to aquire or define datasets with "optionally required" attributes to push forward on additional checks.

https://github.com/ioos/cc-checker-ugrid

**Comment by benjwadams** [comment]
@rsignell-usgs, we're going to move further UGRID related issues to the repo above: https://github.com/ioos/cc-plugin-ugrid
