### ISSUE TITLE
Refactor check_convention_globals

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#339]
Right now the check only ensures that the global attributes are strings. The CF (and COARDS+NUG) don't say they are required but they are _recommended_ which means we should award points for having these global attributes.

**Comment by lukecampbell** [comment]
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_attributes

The text does not use specific language like _"We recommend these global attributes be defined"_ but only say:

> For backwards compatibility with COARDS none of these global attributes is required.

I think it's safe to say that even though it's not explicitly mentioned as recommended, they are in fact recommended attributes. My reasoning, if they weren't recommended why would they be listed with examples and conventions for how to define them?

**Comment by lukecampbell** [comment]
@rsignell-usgs @mbiddle-nodc

Would you like to weigh in on your recommendations here? This is quite debatable and up to interpretation since explicit language in CF §2.6.2 wasn't used.

**Comment by mbiddle-nodc** [comment]
I would say treat these as recommended.

According to http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_overview

> The general description of a file’s contents should be contained in the following attributes: title , history , institution , source , comment and references ( Section 2.6.2, "Description of file contents" ). For backwards compatibility with COARDS none of these attributes is required, but their use is recommended to provide human readable documentation of the file contents.

**Comment by lukecampbell** [comment]
Yeah, I just now noticed that it says _contents **should** be contained in the following_
