### ISSUE TITLE
Section 9 Checks

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#346]
Our assumptions about section 9 are incorrect and the checkers have unique logic for reasoning about feature types within a dataset. This should be refactored so that it shares the reasoning logic with the entire project.

**All checks in all plugins should use similar reasoning logic**

For example, the majority of the body of `check_all_features_are_same_type` has complex logic to reason about a variable's feature type. This logic is completely and fully unique to this check and is not used ANYWHERE else.

**Comment by benjwadams** [comment]
Related: #335
