### ISSUE TITLE
IOOS netCDF profile check

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker#358]
@lukecampbell and @kknee ,

Are the differences [Alex outlined](https://ioos.github.io/ioos-netcdf/ioos-netcdf-metadata-description/) between the 2 NCEI netCDF templates and the IOOS profile recommendations being built in to the compliance checker v3.0?  Are they part of the NCEI plugin?

I know at the bottom of the [issue#69 ](https://github.com/ioos/compliance-checker/issues/69) discussion there was talk of making an IOOS plugin. Where does that stand?  After speaking with Alex, it doesn't sound like a bad idea.  We want a way for RAs to check if their files meet all of the IOOS recommendations that supersede either of the NCEI templates.

**Comment by abirger** [comment]
@jbosch-noaa , @lukecampbell , @kknee , I had a talk with Derrick yesterday, and he agreed to switch completely to the NCEI Template 2.0 and ACDD 1.3. I will update the IOOS NetCDF Profile description accordingly either today or first thing next week.

**Comment by jbosch-noaa** [comment]
@kknee  - Where do we stand here?

**Comment by kknee** [comment]
@jbosch-noaa based on Alex's post, I think we're good.  We already have an ACDD 1.3 check and NCEI 2.0 will be out this week.   Can you close if you agree and clarify the question if not?

**Comment by jbosch-noaa** [comment]
@kknee , @lukecampbell , and @abirger 

I see that you have the ACDD 1.3 check and the NCEI 2.0 check.  I still have one question, though.  Is there a way for a data provider to check if they have all of the IOOS specific attributes that are listed in the table found [ here](https://ioos.github.io/ioos-netcdf/ioos-netcdf-metadata-description-v1_1/) ?

**Comment by kknee** [comment]
@jbosch-noaa there is an IOOS specific check, but its specific to metadata in SOS responses.  We would need to make a new check to address the IOOS netCDF metadata attributes.  

We've got our hands full with the 3.0 milestone.  Mind if we pull this one out for a (near) future release?

**Comment by jbosch-noaa** [comment]
@kknee  - That's fine.  I just don't want us to forget about them.  Thanks.

**Comment by Bobfrat** [comment]
@jbosch-noaa are you aware of any "gold standard" example files for the IOOS profile 1.1 recommendations? I have a checker in place but would like a 100% compliant dataset to test on.

**Comment by jbosch-noaa** [comment]
@Bobfrat - You should have an invite to the site.  You can also access the templates for both v2.0 and v1.1 [here](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/).

**Comment by Bobfrat** [comment]
@jbosch-noaa I see the ncei gold standard templates and files in there, but are there any IOOS examples? This IOOS netcdf profile checker I'm implementing is based off [this document](https://ioos.github.io/ioos-netcdf/ioos-netcdf-metadata-description-v1-1.html#ioos-netcdf-metadata-profile-attributes) which is similar to NCEI 2.0 but has some differences.

**Comment by jbosch-noaa** [comment]
@mbiddle-bcodmo  - Do you have an idea? What RA has v1.1 example files that would be good for Bob to use.

**Comment by mbiddle-bcodmo** [comment]
Have a look at https://data.nodc.noaa.gov/thredds/dodsC/ioos/glos/45028/glos_45028_2015_10_26/45028_air_pressure.nc.html. I don't recall if it was 100% compliant, but they are using v1.1 of the templates.

**Comment by mbiddle-bcodmo** [comment]
No data in that file, how about this one https://data.nodc.noaa.gov/thredds/dodsC/ioos/glos/leorgn/glos_leorgn_2017_09_01/leorgn_ysi_blue_green_algae.nc.html

**Comment by mbiddle-bcodmo** [comment]
You can also find the example template files at https://data.nodc.noaa.gov/thredds/catalog/example/catalog.html.

**Comment by Bobfrat** [comment]
Thank you @mbiddle-bcodmo

**Comment by Bobfrat** [comment]
This checker has been added in this PR: https://github.com/ioos/compliance-checker/pull/526
