### ISSUE TITLE
Refactor unitless standard_name detection

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#393]
Right now it's using a static list, we should refactor it to use the same dynamic structure that the main cf module uses.

**Comment by lukecampbell** [comment]
Also there is at least one entry, `region`, where the units are None.

**Comment by benjwadams** [comment]
I assume you mean `cfutil.get_unitless_standard_names()`?

**Comment by lukecampbell** [comment]
yes! We need to refactor it to take advantage of the Standard Name Table we download. Right now, if the standard name table updates, we won't accurately find unitless standard_names because we're using a static JSON document. 

Also, there's some standard names that have null units like `region`.

**Comment by benjwadams** [comment]
OK to close?
