### ISSUE TITLE
Gather complete dataset tests

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#397]
We need a large cross section of datasets from various catalogs. From there we can add thorough integration tests that performs the entire CF check and we can lock in the result messages.

The CF standard has a lot of recommendations and assertions all over, it's hard to know if you've covered all the requirements unless you look at dataset checks as a whole.

**Comment by benjwadams** [comment]
Related: #237

**Comment by lukecampbell** [comment]
So far:
- HYCOM (Regular Grid)
- OCOS (ROMS)
- l01-met (Time Series)
- USGS DEM (Regular Grid)

**Comment by lukecampbell** [comment]
- Trajectory Profile

**Comment by lukecampbell** [comment]
- Profile
