### ISSUE TITLE
Bugfix release 2.3.1?

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#409]
Since version 2.3.0, there have been a couple of small bug fixes that have not yet been released. In particular, the fix added in #331 (+ unit tests in #334) are needed for some of our data streams at [IMOS](http://imos.org.au/). I know you're focusing on v3.0, but in the meantime, would it be a big task to make a quick bugfix release including these?

I'd be happy to prepare a PR for it, but I'm not sure what else needs to happen at your end to make it happen.

**Comment by kknee** [comment]
@jbosch-noaa a minor release this week is fine with us if it's okay with you

**Comment by jbosch-noaa** [comment]
@kknee - that's fine.

**Comment by lukecampbell** [comment]
@mhidas We released a 3.0.0-rc.1 today

**Comment by jbosch-noaa** [comment]
@lukecampbell, @Bobfrat , and @kknee 
I'm getting confused here.  Why can't we just to a bug fix of v 2.3?  I don't like releasing an unstable release candidate for a version that isn't released yet.

**Comment by lukecampbell** [comment]
It can't be version 2.3 or 2.4 because the interface has changed and is no longer backwards compatible. The only legal version increment is to 3.0. But we don't want this to be the final 3.0 release, so we release it as a release candidate, 3.0.0-rc.1

http://semver.org/

**Comment by ocefpaf** [comment]
@lukecampbell you mean you cannot backport #331 and #334? are those only 3.0 compatible?

**Comment by ocefpaf** [comment]
> @lukecampbell you mean you cannot backport #331 and #334?

Seems that backporting is easy as that change is compatible with the next and the previous version. All that is to pull those commits into a `2.3.1`. Here is a patch release with that fix BTW:

https://github.com/conda-forge/compliance-checker-feedstock/pull/7

**Comment by mhidas** [comment]
@ocefpaf Yes, that's what I had in mind. If it helps, I've put together the required commits on this branch: https://github.com/ioos/compliance-checker/tree/bugfix_release_2_3_1

**Comment by mhidas** [comment]
But if a release with just those fixes (without all the other changes) is not possible now, we may as well wait for 3.0. I see that [milestone](https://github.com/ioos/compliance-checker/milestone/8) due date is not too far away. Is it looking likely to be out by around then?

**Comment by ocefpaf** [comment]
> But if a release with just those fixes (without all the other changes) is not possible now, we may as well wait for 3.0. I see that milestone due date is not too far away. Is it looking likely to be out by around then?

Still, since 3.0 contains breaking changes, a bugfix release is important.

**Comment by lukecampbell** [comment]
Guys I'll look into it later today.

**Comment by benjwadams** [comment]
Used @mhidas's commit as the basis for 2.3.1.

https://github.com/ioos/compliance-checker/releases/tag/2.3.1

Also uploaded to PyPi.

@ocefpaf, could you update the contents of conda-forge?

**Comment by ocefpaf** [comment]
> @ocefpaf, could you update the contents of conda-forge?

Just updated the same PR: https://github.com/conda-forge/compliance-checker-feedstock/pull/7

**Comment by ocefpaf** [comment]
The binaries are in the channel. Closing this. Thanks for the release @benjwadams!

**Comment by mhidas** [comment]
Thank you! That's helpful.
