### ISSUE TITLE
Relase 3.0.0-rc.1 conda forge

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#413]
Hey @ocefpaf could you push the latest release to conda?

**Comment by ocefpaf** [comment]
@lukecampbell  we usually do not package `rc`s in the main channel. We place them in a `main/rc`, for example. But that makes it inaccessible for those not familiar with conda channels. So in this case I will make an exception and place this release in the `main` channel, as I believe this is more like a bug-fix release, no?

**Comment by lukecampbell** [comment]
Ok then let's hold off on releasing it on conda. 

And no it's not a bugfix release because there have been major non-backwards-compatible changes. 

http://semver.org/

So, I'll leave it an RC1 and hopefully the next release is just 3.0

**Comment by lukecampbell** [comment]
The RC isn't complete because there are parts of CF 1.6 Chapter 6-9 that need to be refactored to be consistent with the rest of the project, so this is truly a RC.

**Comment by ocefpaf** [comment]
Fine with me. But I guess the goal of #409 is a bugfix release. Let me know if you make a release of that.
