### ISSUE TITLE
string as a valid data type

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#444]
[04249000_20161115.nc.zip](https://github.com/ioos/compliance-checker/files/592525/04249000_20161115.nc.zip)

§2.2 Valid netCDF data types The variable station_name failed because the datatype is : string type.

I think this is from newer versions of the netCDF library. In older formats strings were shown as char arrays of some max length. I think in the newer versions it has a new type string, which we need to check for and allow as a valid type.

**Comment by benjwadams** [comment]
From the CF 1.7 spec:

> 2.2. Data Types
> 
> The netCDF data types char, byte, short, int, float or real, and double are all acceptable. The char type is not intended for numeric data. One byte numeric data should be stored using the byte data type. All integer types are treated by the netCDF interface as signed. It is possible to treat the byte type as unsigned by using the NUG convention of indicating the unsigned range using the valid_min, valid_max, or valid_range attributes.
> 
> NetCDF does not support a character string type, so these must be represented as character arrays. In this document, a one dimensional array of character data is simply referred to as a "string". An n-dimensional array of strings must be implemented as a character array of dimension (n,max_string_length), with the last (most rapidly varying) dimension declared large enough to contain the longest string in the array. All the strings in a given array are therefore defined to be equal in length. For example, an array of strings containing the names of the months would be dimensioned (12,9) in order to accommodate "September", the month with the longest name.

I'm confused because netCDF4 definitely does support variable length types, the most commonly used of which appears to be variable length strings.  I don't know where CF stands on their usage, but informally I have seen many files using these types.

**Comment by Bobfrat** [comment]
@lukecampbell is the thinking here that string wasn't an accepted type in CF1.6 (or 1.7) because  NetCDF did not support string datatypes, but now it does, so we should accept it?

In my opinion it's ok to fail on this. I think (don't hold me to this) some services like ncSOS require station name as an array of characters based on this data type spec.

**Comment by lukecampbell** [comment]
Could someone output the ncdump?

**Comment by Bobfrat** [comment]
```
netcdf \04249000_20161115 {
dimensions:
	time = 60 ;
variables:
	double time(time) ;
		time:validMin = 500860800. ;
		time:long_name = "time of observation" ;
		time:standard_name = "time" ;
		time:validMax = 500913900. ;
		time:units = "seconds since 2001-1-1 0:0:0" ;
		time:axis = "T" ;
	string station_name ;
		station_name:cf_role = "timeseries_id" ;
	double lat ;
		lat:units = "degrees_north" ;
		lat:long_name = "station latitude" ;
		lat:standard_name = "latitude" ;
		lat:axis = "Y" ;
	double lon ;
		lon:units = "degrees_east" ;
		lon:long_name = "station longitude" ;
		lon:standard_name = "longitude" ;
		lon:axis = "X" ;
	double depth ;
		depth:standard_name = "depth" ;
		depth:axis = "Z" ;
	double pH(time) ;
		pH:_FillValue = -9999. ;
		pH:description = "pH, water, unfiltered, field, standard units" ;
		pH:validMin = 7.8 ;
		pH:coordinates = "time lat lon depth" ;
		pH:long_name = "pH, water, unfiltered, field, standard units" ;
		pH:standard_name = "00400" ;
		pH:validMax = 7.9 ;
		pH:units = "std units" ;
	double Turbidity(time) ;
		Turbidity:_FillValue = -9999. ;
		Turbidity:description = "Turbidity, water, unfiltered, monochrome near infra-red LED light, 780-900 nm, detection angle 90 +-2.5 degrees, formazin nephelometric units (FNU)" ;
		Turbidity:validMin = 4.2 ;
		Turbidity:coordinates = "time lat lon depth" ;
		Turbidity:long_name = "Turbidity, water, unfiltered, monochrome near infra-red LED light, 780-900 nm, detection angle 90 &#177;2.5&#176;, formazin nephelometric units (FNU)" ;
		Turbidity:standard_name = "63680" ;
		Turbidity:validMax = 7.7 ;
		Turbidity:units = "FNU" ;
	double Specific\ conductance(time) ;
		Specific\ conductance:_FillValue = -9999. ;
		Specific\ conductance:description = "Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius" ;
		Specific\ conductance:validMin = 583. ;
		Specific\ conductance:coordinates = "time lat lon depth" ;
		Specific\ conductance:long_name = "Specific conductance, water, unfiltered, microsiemens per centimeter at 25&#176;C" ;
		Specific\ conductance:standard_name = "00095" ;
		Specific\ conductance:validMax = 634. ;
		Specific\ conductance:units = "uS/cm @25C" ;
	double Temperature(time) ;
		Temperature:_FillValue = -9999. ;
		Temperature:description = "Temperature, water, degrees Celsius" ;
		Temperature:validMin = 8.2 ;
		Temperature:coordinates = "time lat lon depth" ;
		Temperature:long_name = "Temperature, water, &#176;C" ;
		Temperature:standard_name = "00010" ;
		Temperature:validMax = 8.6 ;
		Temperature:units = "deg C" ;
	double Dissolved\ oxygen(time) ;
		Dissolved\ oxygen:_FillValue = -9999. ;
		Dissolved\ oxygen:description = "Dissolved oxygen, water, unfiltered, milligrams per liter" ;
		Dissolved\ oxygen:validMin = 11.1 ;
		Dissolved\ oxygen:coordinates = "time lat lon depth" ;
		Dissolved\ oxygen:long_name = "Dissolved oxygen, water, unfiltered, mg/L" ;
		Dissolved\ oxygen:standard_name = "00300" ;
		Dissolved\ oxygen:validMax = 12. ;
		Dissolved\ oxygen:units = "mg/l" ;
	double Gage\ height(time) ;
		Gage\ height:_FillValue = -9999. ;
		Gage\ height:description = "Gage height, feet" ;
		Gage\ height:validMin = 2.57 ;
		Gage\ height:coordinates = "time lat lon depth" ;
		Gage\ height:long_name = "Gage height, ft" ;
		Gage\ height:standard_name = "00065" ;
		Gage\ height:validMax = 3.5 ;
		Gage\ height:units = "ft" ;
	double Streamflow(time) ;
		Streamflow:_FillValue = -9999. ;
		Streamflow:description = "Discharge, cubic feet per second" ;
		Streamflow:validMin = 1240. ;
		Streamflow:coordinates = "time lat lon depth" ;
		Streamflow:long_name = "Streamflow, ft&#179;/s" ;
		Streamflow:standard_name = "00060" ;
		Streamflow:validMax = 2830. ;
		Streamflow:units = "ft3/s" ;

// global attributes:
		:featureType = "timeSeries" ;
		:source = "http://waterservices.usgs.gov/" ;
		:title = "OSWEGO RIVER AT LOCK 7, OSWEGO NY" ;
		:Conventions = "CF-1.6" ;
		:cdm_data_type = "Station" ;
		:Metadata_Conventions = "Unidata Dataset Discovery v1.0" ;
		:id = "04249000" ;
		:nodc_template_version = "NODC_NetCDF_TimeSeries_Orthogonal_Template_v1.1" ;
}
```

**Comment by lukecampbell** [comment]
Ah yes, now I remember. `string` is not a valid data type for CF. `string` is a netCDF4 feature and CF-1.6 is targeting netCDFv3. That's why you don't see groups supported by CF, or variable length arrays. Underneath the covers string is a vlen char array in HDF5, or it might be something else these days. 

If a data type is shown as a string, it should fail a CF check as the data type is invalid, and it should be a char array of explicit length.

```
dimensions:
  station_name_len = 24;
variables:
char station_name(station_name_len);
```

**Comment by Bobfrat** [comment]
Ok can this issue be closed then? Compliance checker will catch and throw an error for string datatypes:

```
§2.2 Valid netCDF data types           :3:    11/12 : The variable station_name
                                                      failed because the
                                                      datatype is <type 'netCDF4
                                                      ._netCDF4.VLType'>: string
                                                      type
```
