### ISSUE TITLE
Better documentation web site

### ISSUE THREAD

**Issue by dpsnowden** [ioos/compliance-checker#447]
We need a better overview description of the compliance checker that is appropriate for more general audiences.  It should describe:

- Who is the primary audience and why do they need this?
- How do they get it? 
- How should they use it?  (links to demos)
- What are plugins and why should I care?  How should I think about versions of the master cc relative to versions of plugins.  It's confusing to send out announcements of new versions of plugins without updates to the main cc.  Brings up many questions.
- What is the relationship between the command line version and the web version?  What should it be?

The readme.md is a good start, but it just needs to be updated to reflect current reality.  Also the wiki has some information that could probably be combined with the readme.md and published at ioos.github.io/compliance-checker.  Then clean up garbage.

Update the readme.md table at the top of the page.  
- It's incomplete
- Change IOOS Asset Concept to something more descriptive.  I think it's the same as the thing we're calling [IOOS Metadata Profile for NetCDF](https://ioos.github.io/ioos-netcdf/ioos-netcdf-metadata-description-v1_1/)

@mwengren did you know about the SOS/Describe Sensor checks in the compliance checker?  I think it's orphaned but maybe it's useful in your [sensorml to iso converters](https://github.com/mwengren/sensorml2iso).

**Comment by daf** [comment]
> @mwengren did you know about the SOS/Describe Sensor checks in the compliance checker? I think it's orphaned but maybe it's useful in your sensorml to iso converters.

The metamap file for the "IOOS Accept Concept" checker vs DescribeSensor/GetCapabilities can still be extracted [1] [2] and used with [Wicken](http://github.com/ioos/Wicken) - that was Wicken's primary goal.  Load them here: [ioos.py@be0a7fba25b5c1e32:12](https://github.com/ioos/compliance-checker/blob/be0a7fba25b5c1e325ab0b3a085d1d0630e2587a/compliance_checker/ioos.py#L12-L17)

[1] https://github.com/ioos/compliance-checker/blob/be0a7fba25b5c1e325ab0b3a085d1d0630e2587a/compliance_checker/data/ioos-metamap-sos-ds.json
[2] https://github.com/ioos/compliance-checker/blob/be0a7fba25b5c1e325ab0b3a085d1d0630e2587a/compliance_checker/data/ioos-metamap-sos-gc.json

**Comment by jbosch-noaa** [comment]
Once that documentation has been updated. @ocefpaf and I can put together a notebook for our data usage blog : https://github.com/ioos/notebooks_demos/issues/93

**Comment by jbosch-noaa** [comment]
I am drafting new documentation on both the compliance checker and the compliance checker web tool.  My plan is to direct users to this github repo for the python/command line usage instructions and elaborate on the web tool. Looking at the Wiki, these installation instructions are very out of date and don't really match the README file:

https://github.com/ioos/compliance-checker/wiki/Installation

It would be helpful if I could direct people to these installation instructions in my documentation.

**Comment by Bobfrat** [comment]
New documentation is available in the project [README](https://github.com/ioos/compliance-checker) and the complementary [Installation wiki](https://github.com/ioos/compliance-checker/wiki/Installation). I welcome any feedback anyone has.

**Comment by Bobfrat** [comment]
@jbosch-noaa do you have any comments/suggestions for new README? Otherwise I'll close this.

**Comment by jbosch-noaa** [comment]
@Bobfrat  - This README file looks good, however, I have gotten some feedback on the Compliance Checker Web documentation.  I will take that up in that repo.

**Comment by Bobfrat** [comment]
Sounds good, I'll close this one then
