### ISSUE TITLE
Test errors using conda

### ISSUE THREAD

**Issue by kwilcox** [ioos/compliance-checker#451]
When trying to run the tests using a `conda` env there are 4 error that pass when using `pip`:
https://gist.github.com/kwilcox/1a42e95c178af529b9f468fac2050ee5

**Comment by lukecampbell** [comment]
Is this linux python 3.5?

**Comment by kwilcox** [comment]
Yup!

**Comment by lukecampbell** [comment]
@ocefpaf have you seen any issues with the builds for linux 3.5 ? I remember when we were updating the release there were a few broken builds.

**Comment by ocefpaf** [comment]
Issue with the build? No. Let me check @kwilcox gist to see if that is a packaging issue. Hold on...

**Comment by lukecampbell** [comment]
@ocefpaf It's been a while since I followed up on this, are there any updates?

**Comment by ocefpaf** [comment]
We do run the test suite in [Travis-CI with conda and Python 3.6](https://github.com/ioos/compliance-checker/blob/master/.travis.yml#L8) and everything is green. @kwilcox are you still seeing those errors?

**Comment by kwilcox** [comment]
I still get errors. The tests are using `pip` to install the dependencies and I'm obviously using `conda`. That is most likely the difference.

**Comment by ocefpaf** [comment]
I did not see the pip install below :-(
@lukecampbell I would start be using only conda in Travis-CI to debug this.

**Comment by lukecampbell** [comment]
Ok, it's probably going to be a while before I can get to this, but I'll try to debug it when I can.

**Comment by ocefpaf** [comment]
See #479
