### ISSUE TITLE
cmd_data_type values

### ISSUE THREAD

**Issue by jpotemra** [ioos/compliance-checker#457]
Hi all,

I was wondering if you can expand the acceptable list of cmd_data_type to include "Timeseries"?  The checker seems to accept the following: ([u'Grid', u'Image', u'Point', u'Radial', u'Station', u'Swath', u'Trajectory']).  However, ERDDAP throws an error with cmd_data_type = Station.  Instead it wants "TimeSeries".  The valid cmd_data_type values for ERDDAP are: Grid, MovingGrid, Other, Point, Profile, RadialSweep, TimeSeries, TimeSeriesProfile, Swath, Trajectory, TrajectoryProfile.

BTW, ncSOS seems to be happy with either Station or TimeSeries.

Thanks,

Jim

**Comment by lukecampbell** [comment]
Unfortunately the only allowed values are those that we check:
https://github.com/Unidata/thredds/issues/72

As per the authors and the THREDDS source code. I wish it was a little bit more clear in documentation for ACDD and CF where these are defined but the values don't include the values you mention.

**Comment by lukecampbell** [comment]
I would like to reach out to @kwilcox @daf @brianmckenna @mbiddle-nodc for their input on this. Should we change the ACDD and CF checkers that check the attribute `cdm_data_type` to include additional enumerated values that are leveraged by other community driven software like ERDDAP?

**Comment by lukecampbell** [comment]
I'm at the Winter 2017 ESIP Conference now, I'll ask about this at the netCDF session.

**Comment by lukecampbell** [comment]
I think I'll remove this from the ACDD checks.

**Comment by lukecampbell** [comment]
Just an update, I need to do a release of compliance checker including this patch sometime this or next week.

**Comment by lukecampbell** [comment]
Just a continuation, I didn't forget about this, but I wanted to batch all these changes together with some of the recent fixes and the Glider DAC changes.

**Comment by daf** [comment]
This was [released in 3.0.1](https://github.com/ioos/compliance-checker/releases/tag/3.0.1)
