### ISSUE TITLE
Case sensitivity for attribute values

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#461]
Verify that the standards are case insensitive for explicit attribute values, for example `featureType`.

If they are case sensitive, note it, if not patch the code to be insensitive in the checks.

**Comment by lukecampbell** [comment]
@mhidas reports

> According to CF ([9.4](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#featureType)) the value of the `featureType` global attribute is case-insensitive. This was allowed for in version 2.3, but in 3.0 it is not. So e.g. `featureType = "timeseries"` is no longer allowed, but it should be.

**Comment by benjwadams** [comment]
I'm going to make this for featureType only and close this issue.  If there are other places where case insensitivity is needed, then new issues should be opened for those individual cases.
