### ISSUE TITLE
broken link to IOOS on GitHub homepage

### ISSUE THREAD

**Issue by pacioos** [ioos/compliance-checker#466]
Under "Available Test Suites", the GitHub homepage for this compliance-checker lists "IOOS" with the following broken link:

http://www.ioos.noaa.gov/data/contribute_data.html

In looking at the IOOS data page, I see that the new URL is the following:

http://ioos.noaa.gov/data/contribute-data/

However, this link does not sufficiently steer the user to what conventions are being tested by the compliance-checker. Where on the above website are the IOOS metadata conventions listed?

**Comment by lukecampbell** [comment]
@jbosch-noaa could we add some descriptions and links to the metadata standards and some reference material for people?  I recently dug up a bunch of links for the IOOS Vocabulary standards:

- https://ioos.github.io/#netcdf-and-or-opendap-guidelines:6083a88ee3411b0d17ce02d738f69d47
- https://ioos.github.io/ioos-netcdf/ioos-netcdf-metadata-description-v1_1/
- https://ioos.github.io/conventions-for-observing-asset-identifiers/ioos_assets_v1.0/
- (Link to the NetCDF-to-SOS Mappings_clean_2016-04-07 google doc)

**Comment by lukecampbell** [comment]
I can update the URL on the web checker.

**Comment by jbosch-noaa** [comment]
@pacioos  - Thanks for bringing this to our attention.  The links Luke mentioned above should help but I can see that they also could use some updating.  @abirger and I will work on getting those updates sorted out. 

@lukecampbell - I recently shared with you a google doc on compliance checker documentation updates.
