### ISSUE TITLE
Roll up NCEI checks into just two checks, 1.1 and 2.0

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#467]
With the feature detection code from the 3.0 release we are able to remove all the individual feature type checks and just have two checks and dynamically figure out the feature type to use.

@mbiddle-nodc heads up

**Comment by benjwadams** [comment]
Extended discussion should occur on the repo for the NCEI plugin checks: https://github.com/ioos/cc-plugin-ncei

Maybe related: https://github.com/ioos/cc-plugin-ncei/issues/37

Going to close and the issue/discussion can continue on that repo.
