### ISSUE TITLE
Create check to verify valid_min valid_max data type

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#468]
For some datasets the `valid_min` and `valid_max` variable attribute has a mismatched data type from the parent variable.

**Comment by benjwadams** [comment]
I'm assuming `valid_range` also falls under this same category, as well as the `actual_min`, `actual_max`, and `actual_range` attributes added in CF-1.7.

**Comment by lukecampbell** [comment]
`valid_range` is an array attribute but the data type of the array should match the parent variable. 

Example:
```
float temperature(time);
    temperature:standard_name = "air_temperature";
    temperature:units = "deg_C";
    temperature:valid_range = -20.0f, 50.0f
```

**Comment by benjwadams** [comment]
Appears to be already handled by https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L3036-L3056

I need to check the tests as well as with some files that have this issue.

**Comment by mhidas** [comment]
>  Appears to be already handled by https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L3036-L3056

Yes, but that's only within `check_packed_data`. This check  should apply to all variables.

And it should also apply to the `_FillValue` attribute (http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#missing-data).

**Comment by benjwadams** [comment]
Whoops, my omission.
