### ISSUE TITLE
Improve clarity and understanding that the priority values correspond to high, med, low

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#477]
> Also, some feedback on the compliance checker, it wasn’t completely obvious that High Priority attributes are given Priority 3 in the Corrective Actions table.  If you could add a legend that would help.

**Comment by Bobfrat** [comment]
Corrective Actions table is separated into High, Medium, and Low Priority tables [here](https://github.com/ioos/compliance-checker-web/pull/66)

**Comment by mhidas** [comment]
Would it be even more helpful to use similar terminology to (some of) the conventions documents, e.g. "required", "recommended" and "suggested", instead of "high", "med", "low"?

**Comment by mhidas** [comment]
That might help with other issues, like #510

**Comment by benjwadams** [comment]
I can't assign @daltonkell to this issue (maybe because he's not in IOOS org, which I also can't add people to), but he's handling this issue.

**Comment by Bobfrat** [comment]
@mhidas I like that suggestion but do you think by getting close to the same terminology it will confuse users more? 

For example, ACDD uses Highly Recommended, Recommended, and Suggested, while NCEI uses the terminology you are referencing. I imagine someones going to report a bug saying that we're calling ACDD Highly Recommended attributes Required.

Anyone else have an opinion? I suppose the best solution would be to keep track and use the terminology that each of the standards use when reporting.

**Comment by mhidas** [comment]
@Bobfrat Yes, I suppose using similar but not quite the same terms could could be confusing for some. I agree the best solution would be to use the right terminology for each check suite.

I guess the high/med/low values defined within the `BaseCheck` class could remain as defaults. You could add another class attribute (dict) to store to store names for these levels to be used in results. This could then be overridden in other check classes to use different names.

**Comment by Bobfrat** [comment]
That’s what I was thinking too so we’ll give it a go. Thanks for the input @mhidas.

**Comment by Bobfrat** [comment]
Addressed here:
https://github.com/ioos/compliance-checker/pull/556
