### ISSUE TITLE
3.0.3 Release on Conda Forge

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#490]
Hey Filipe, could you do a release on conda-forge for compliance-checker? I think you made some changes to the build meta so I don't know that I know how to bundle that into an appropriate conda release.

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/compliance-checker-feedstock/pull/16

**Comment by lukecampbell** [comment]
... I have no words

**Comment by ocefpaf** [comment]
(Don't tell anyone but I have a few bots working for me :wink:)

**Comment by ocefpaf** [comment]
I guess it is safe to close this one: https://anaconda.org/conda-forge/compliance-checker/files
