### ISSUE TITLE
CF check on number of cf_role variables has been removed in v3

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#491]
CF ([section 9.5](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#coordinates-metadata), second paragraph) says:
>CF files that contain timeSeries, profile or trajectory featureTypes, should include only a single occurrence of a `cf_role` attribute; CF files that contain timeSeriesProfile or trajectoryProfile may contain two occurrences

Until v2.3, the CF checker used to check this. In v3 this got refactored. It still checks the values of the `cf_role` attribute, but doesn't check the number of variables that have it.

**Comment by Bobfrat** [comment]
Closing, addressed in #503
