### ISSUE TITLE
Tight requirements are checked at load time and break compliance-checker 

### ISSUE THREAD

**Issue by ocefpaf** [ioos/compliance-checker#493]
The two tight constraints in `compliance-checker`,  `isodate==0.5.4` and `pygeoif==0.6`, are checked at load time and prevent `compliance-checker` from running. Are those really needed? Both `conda` and `pip` will constantly break `compliance-checker` when updating envs because of that.

@daf and @lukecampbell I propose to use at least a `>=` constraint. We can improve the test coverage, if that is needed, to catch any possible issues with the updated versions.

```
Could not load acdd-1.1 = compliance_checker.acdd:ACDD1_1Check : (pygeoif 0.7 (lib/python3.6/site-packages), Requirement.parse('pygeoif==0.6'))
Could not load acdd-1.3 = compliance_checker.acdd:ACDD1_3Check : (pygeoif 0.7 (/lib/python3.6/site-packages), Requirement.parse('pygeoif==0.6'))
Could not load cf = compliance_checker.cf.cf:CFBaseCheck : (pygeoif 0.7 (/lib/python3.6/site-packages), Requirement.parse('pygeoif==0.6'))
Could not load ioos = compliance_checker.ioos:IOOSBaseCheck : (pygeoif 0.7 (/lib/python3.6/site-packages), Requirement.parse('pygeoif==0.6'))
```

**Comment by daf** [comment]
I'm all for relaxing requirements, but why would updating envs break this?  The requirements state the dep, the package manager should respect that.  Looking at the conda recipe, it seems those requirement versions aren't replicated there, so I can see this breaking from a conda point of view.

**Comment by ocefpaf** [comment]
> the package manager should respect tha

Even if we specify, which I tried, updating always break the pinning b/c conda does not know about each individual pinning. That works only in a new installation. I believe that `pip` does the same but I am not sure.

**Comment by daf** [comment]
I think pip handles this, but I'm fine with relaxing them.  I'm not sure why they got locked, though, so maybe we need more eyeballs on this.

**Comment by ocefpaf** [comment]
> we need more eyeballs on this.

No problem. I can use the pinning for now. I guess that only a `conda update --all` will break things.
