### ISSUE TITLE
CFBaseCheck::check_cell_measures() failing

### ISSUE THREAD

**Issue by piotrflorek** [ioos/compliance-checker#495]
Hi,

There are 2 small bugs in the CF suite (`check_cell_measure()` method), which eluded detection because corresponding [unit test](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/tests/test_cf.py#L352) doesn't really test the right thing.

1. netcdf4's [get_variables_by_attributes](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L2579) returns a list of variables, not just their names, so they cannot be used for indexing of ds.variables

Something along these lines should fix it

```python
tested_vars = ds.get_variables_by_attributes(cell_measures=lambda c: c is not None)
for tested_var in tested_vars:
    var_name = tested_var.name
        var = ds.variables[var_name]
```
2. Also, a few lines below, `search_res.groups[0]` will fail because `groups` in `re.MatchObject` is a method, not an attribute (unlike in `re.RegexObject`)

**Comment by lukecampbell** [comment]
Thanks for the catch, I have a PR in that should fix this and adds a unit test to check it.

**Comment by daf** [comment]
I noticed a code issue when running the test script from #497 about variables used before they are assigned.  I've got the code fix, but the new tests fail, so I'm investigating/fixing those.  This is not quite finished.
