### ISSUE TITLE
CF checker treats omission of both standard and long name as an error

### ISSUE THREAD

**Issue by Bobfrat** [ioos/compliance-checker#506]
Originally part of https://github.com/ioos/compliance-checker/issues/501

(4) IOOS records the omission of both a standard name and long name for a variable as an error, the CF standard states that use of at least one of these as “highly recommended” (the IOOS error message give the wrong section for this: 3.3 instead of 3.2)

**Comment by lukecampbell** [comment]
The only issue I here is the incorrect reference.

If the standard labels "at least one of them as highly recommended", the checker looks for at least one, if it can't find at least one it creates a message indicating as such. This check is priority 3 because of the language "highly recommended".

**Comment by Bobfrat** [comment]
addressed in #523
