### ISSUE TITLE
Need more automated way to get updates to the web version

### ISSUE THREAD

**Issue by Bobfrat** [ioos/compliance-checker#512]
A recommendation from @daf.
The web version shouldn't lag behind this repo. We could implement continuous integration to deploy new web version on pushes to master.

**Comment by lukecampbell** [comment]
If you want to take a shot at using Jenkins for it, it would be good. Just make sure the build versions use snapshot or dev or some suffix to indicate that it's not a formal tested release, just a snapshot build.

**Comment by lukecampbell** [comment]
If you patch the Dockerfile on the web project to use an environment variable for the compliance-checker version, it should be automatable.

The build workflow would look something like this:

1. clone ioos/compliance-checker
2. clone ioos/compliance-checker-web
3. install ioos/compliance-checker (pip or whatever)
4. install py.test
5. Run compliance-checker tests
6. Go to compliance-checker-web directory.
7. set environment variable for compliance checker version to master
8. Run docker build
9. Run docker push

**Comment by lukecampbell** [comment]
My recommendation for the semantic versioning is that builds be labeled as `3.x.x-NIGHTLY` or something like that.

**Comment by ocefpaf** [comment]
Question: from @Bobfrat comments I had the impression that only tagged releases would be pushed. But from @lukecampbell's comments it seems that a latest master version would be pushed. If the former I am 100% in agreement, if the latter than the website itself need to be labeled as "unstable/unreleased" or something similar and we should maintain two endpoints, one with the unstable and another one with the latest release.

**Comment by lukecampbell** [comment]
I am just referring to the docker build. The website should only reflect actual releases.

**Comment by benjwadams** [comment]
This is a tooling issue on third party services, not a code issue, and should be dealt with using the appropriate web hooks for DockerHub, etc.  I'm going to close this and we can discuss elsewhere.
