### ISSUE TITLE
Create a checker for the CF 1.7 release

### ISSUE THREAD

**Issue by Bobfrat** [ioos/compliance-checker#515]
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html

**Comment by lukecampbell** [comment]
oh, look at that. 1.7 is no longer in draft phase. I guess all of that knowledge I accumulated in 1.6 is now useless -_-.

**Comment by benjwadams** [comment]
This really isn't suited for just a single issue -- perhaps it should be a milestone instead?

**Comment by benjwadams** [comment]
The revision list added to the new CF document would probably be the best place to start picking out updates.
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#revhistory

**Comment by daltonkell** [comment]
The current updates to the checker reside on the [cf_1_7 branch](https://github.com/ioos/compliance-checker/blob/cf_1_7_dev) (it'll have to be rebased before merging).

There are two changes I am unsure about:

1. Ticket 87: After reviewing, I believe that the change indicated on [Ticket 87](https://cf-trac.llnl.gov/trac/ticket/87) is already accounted for here https://github.com/ioos/compliance-checker/blob/cf_1_7_dev/compliance_checker/cf/cf.py#L889.

2. Ticket 118: Regarding [Ticket 118](https://cf-trac.llnl.gov/trac/ticket/118), I think we'd first need to create a check for the optional `crs_wkt` attribute (info [here](https://cf-trac.llnl.gov/trac/ticket/69)) of a `grid_mapping` variable, which would encompass `geoid_name` and `geopotential_datum_name`. The `geoid_name` and `geopotential_datum_name` are intended to be supplemental to the `grid_mapping` attribute, and to my knowledge, this is not yet implemented. Please advise on how to proceed.

@Bobfrat @benjwadams

**Comment by daltonkell** [comment]
Listed here are the changes to the CF Standard from versions 1.6 to 1.7; a checked box indicates the change has been implemented in the [new branch](https://github.com/ioos/compliance-checker/tree/cf_1_7_dev_rebase) (tickets and changes for errata are not included, only substantial changes requiring modifying existing checks or creating new logic):

- [x] Adding an attribute for `actual_range` , see [Section 2.5.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#missing-data)
- [ ] Ticket 118, Add geoid_name and geopotential_datum_name to the list of Grid Mapping Attributes. see [Table F1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#table-grid-mapping-attributes) 
- [x] Ticket 148, Added maximum_absolute_value, minimum_absolute_value and mean_absolute_value to cell methods in [Appendix E ](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#appendix-cell-methods)
- [x] Ticket 77, Add sinusoidal projection [here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_sinusoidal)
- [x] Ticket 92, Add oblique mercator projection, see [here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_oblique_mercator)
- [x] Ticket 72, Adding the [geostationary projection](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_geostationary_projection)
- [x] Ticket 102, additional cell_methods, changes in Appendix E and section 7.3; see [here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#appendix-cell-methods)

@benjwadams is currently working on the `geoid_name` implementation
