### ISSUE TITLE
Running checker w/o glider QC flags

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker#524]
A request of GCOOS regarding running glider data through the Compliance Checker before submitting files to the Glider DAC without QC flags:

From Matt Howard and @fgayanilo:
Can Compliance Checker be tweaked to accommodate lack of QC flags present in netCDF files per the Glider DAC SOP to only perform QC on data if no QC flags already present?  Perhaps by including a flag to disable checks for QC attributes in a compliance score.  

--

**Comment by Bobfrat** [comment]
I think this has been addressed in this PR: https://github.com/ioos/cc-plugin-glider/pull/14
