### ISSUE TITLE
Compliance Checker REST API

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker#525]
GCOOS requested if it is possible to provide a REST API that would allow RA websites to link to CC score reports directly from dataset landing pages.  

@fgayanilo - I think this warrants discussion here.  Do you want to do this for all your files or just example files? We are working on refining the functionality to export reports from the command line compliance checker and the compliance checker website.

**Comment by fgayanilo** [comment]
Thanks for all efforts to expand the features of CC; and yes, the CC is very useful to us -- great utility to have. I hope you can expand that to accommodate data bigger than 16MB to start with. Average monthly data for a station with the QA/QC flags is about 30MB.

As we receive data from various sources and reformat these collections to be in compliance with community standards, we can automate the checking process (from our end) of data generated if a RESTful API for CC is available. The return can be an XML file equivalent to the scorecard that we can parse. 

Example: https://data.ioos.us/compliance/index.html?testType=ACDD_1.1&file=http://data.gcoos.org/data/waf/nc_by_platform/ocn/ldn/2008/gcoos_ioos_station_SCCF_12_2008_01_ocn.nc

should return the results of the compliance to ACDD 1.1 analyses of the netCDF file (http://data.gcoos.org/data/waf/nc_by_platform/ocn/ldn/2008/gcoos_ioos_station_SCCF_12_2008_01_ocn.nc)

Indeed, the return can also be used as part of the landing page, if one is available.

**Comment by Bobfrat** [comment]
We do have an API for compliance checker web as documented here:

https://github.com/ioos/compliance-checker-web/wiki/API

I just tried using it but I'm getting timeout errors, so I'll troubleshoot why it's not working as advertised.

**Comment by fgayanilo** [comment]
This is great! Thanks a lot and I never knew about this URL to the API .

**Comment by jbosch-noaa** [comment]
I didn't either!  Thanks guys.  :)

**Comment by lukecampbell** [comment]
The CHL example didn't work because CHL's THREDDS is usually inaccessible.

**Comment by lukecampbell** [comment]
It's worth mentioning that the API has the same limitations that the web checker has in terms of database size and processing timeout. I don't recall the limits off the top of my head, but if an external source takes longer than 60s I believe it will just error out.

**Comment by fgayanilo** [comment]
Are there plans to host this on bigger and faster servers to overcome the (resource) limitations? Overcoming the 16MB file size limit will be a big plus!

**Comment by Bobfrat** [comment]
@fgayanilo that is something we are looking into. Will keep you posted.
