### ISSUE TITLE
Accessing OpenDAP on ESGF thredds services

### ISSUE THREAD

**Issue by cehbrecht** [ioos/compliance-checker#539]
I want to use the compliance-checker to run CF checks on ESGF data services using the OpenDAP protocol. ESGF services are access restricted with X509 certificates ... but if you configure an `.dodsrc` file the NetCDF library will handle the authentication ... so, the compliance-checker will work for ESGF/OpenDAP. 

But ... the ESGF OpenDAP service needs to be recognized. 

This issue was fixed in a previous version: #456 

But the fix disappeared ;) 

I have made a monkey-patch to overwrite `compliance_checker.protocols.is_opendap` ... not nice, but it works:

```
def patched_is_opendap(url):
        '''
        Returns True if the URL is a valid OPeNDAP URL
        :param str url: URL for a remote OPeNDAP endpoint
        '''
        # If the server replies to a Data Attribute Structure request
        das_url = url + '.das'
        response = requests.get(das_url, allow_redirects=True)
        if 'xdods-server' in response.headers:
            return True
        # Check if it is an access restricted ESGF thredds service
        if response.status_code == 401 and \
            'text/html' in response.headers['content-type'] and \
                'The following URL requires authentication:' in response.text:
            return True
        return False
```

Maybe you have a better idea for the ESGF OpenDAP "discovery" code.

Here is a notebook with examples on how to use ESGF OpenDAP access:
https://github.com/cehbrecht/demo-notebooks/blob/master/esgf-opendap.ipynb

**Comment by Bobfrat** [comment]
Your suggestion passes all the tests... I agree it's not the prettiest. I'll see if I can come up with something else but otherwise I'll implement your solution

**Comment by Bobfrat** [comment]
@cehbrecht how can I test that this works on one of those endpoints? Can I get access?

**Comment by cehbrecht** [comment]
@Bobfrat To make a real test you need an ESGF account. You can get one for example at DKRZ:
https://esgf-data.dkrz.de/   (look for register)

To be able to download a file from ESGF you also need to register for a specific group. For example if you want to have CORDEX files then you need to register for the CORDEX group. The simplest way is to download a file and you will be directed to the group registration:

[Download CORDEX file](http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/EUR-44/MPI-CSC/MPI-M-MPI-ESM-LR/historical/r1i1p1/MPI-CSC-REMO2009/v1/mon/tas/v20150609/tas_EUR-44_MPI-M-MPI-ESM-LR_historical_r1i1p1_MPI-CSC-REMO2009_v1_mon_200101-200512.nc)

Now you need to prepare the `.dodsrc` file with the credentials. A more convenient way to do this is with the [esgf-pylient](http://esgf-pyclient.readthedocs.io/en/latest/). See this [IPython notebook](https://github.com/cehbrecht/demo-notebooks/blob/master/esgf-opendap.ipynb) on how to use it.

If you have everything in place (`.docsrc` must be in your home or the current directory) then you can try an OpenDAP URL to access the same CORDEX file, for example:

[OpendDAP for CORDEX dataset](http://esgf1.dkrz.de/thredds/dodsC/cordex/cordex/output/EUR-44/MPI-CSC/MPI-M-MPI-ESM-LR/historical/r1i1p1/MPI-CSC-REMO2009/v1/mon/tas/v20150609/tas_EUR-44_MPI-M-MPI-ESM-LR_historical_r1i1p1_MPI-CSC-REMO2009_v1_mon_200101-200512.nc.dods)

A long way ... sorry.

**Comment by Bobfrat** [comment]
@cehbrecht I was able to get an ESGF account, download the CORDEX file in your example and get all the way through the iPython notebook until this line:
```
ds = Dataset(agg.opendap_url, 'r')
```
where I still get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
IOError: [Errno -78] NetCDF: Authorization failure: 'http://esgf1.dkrz.de/thredds/dodsC/cordex.output.EUR-11.MPI-CSC.MPI-M-MPI-ESM-LR.historical.r1i1p1.REMO2009.v1.day.tasmax.tasmax.20160419.aggregation
```
I have what seems like a valid .dodsrc file in my home directory. 

Can I make the pull request and have you test it out? I'm just going to add what we had in the previous version that worked.

**Comment by cehbrecht** [comment]
@Bobfrat 
I will review your PR tomorrow. Thanks for adding this.

**Comment by cehbrecht** [comment]
@Bobfrat I have reviewed your PR and it works on my side. 

I haven't checked issues with the ipython notebook ... you only need the "esgf logon" which prepares a `.dodsrc`  file. Then you can run `cchecker --test cf "opendap_url"`
