### ISSUE TITLE
Moving to Python3

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#557]
Back when compliance checker was first written, scientific library support was rather mixed for Python 3.  Nowadays, almost all (or maybe all?) the libraries used by compliance checker have Python 3 support.  We currently support Python 2.x series, but it is a major nuisance in some categories, i.e. shoehorning unicode support and all the differences between how 2 and 3 handle unicode.  There are also other features that are supported in Python 3 which would probably be desirable for compliance checker, such as type annotations and type checking support.   This issue is intended to discuss moving away from Python 2 to solely 3, advantages, potential pitfalls, etc.

Cc: @Bobfrat, @kwilcox, @daf

**Comment by MBARIMike** [comment]
I'm running compliance-checker in Python 3.6 and haven't see any issues. So maybe all is O.K. ?

One of the other features is asyncio which could greatly improve the speed of walking large OPeNDAP directories. Is there any comment on the possibility of asyncio working with compliance-checker?

**Comment by kwilcox** [comment]
Hey Mike - have you tried using xarray/dask to crawl a large directory of datasets? I usually crawl though a nested directory structure for netCDF files like so but would be interested in some comparisons if you have an `asyncio` or `concurrent.futures` (https://docs.python.org/3.6/library/concurrent.futures.html) solution implemented.

```
import xarray
from pathlib import Path
from dask.distributed import Client
from dask.diagnostics import ProgressBar

client = Client()
ncpath = Path('/mnt/store/data/packrat/cordc/east_gulf_coast_1km/processed/')
globfiles = sorted(list(ncpath.glob('**/*.nc')))
with ProgressBar():
    ds = xarray.open_mfdataset(
        globfiles,
        parallel=True,
        compat='broadcast_equals',
        data_vars='all',
        coords='minimal',
        chunks={}
    )
```

**Comment by benjwadams** [comment]
I should open a milestone instead.

**Comment by benjwadams** [comment]
@giumas: this is less about compatibility with Python 2 and 3 and more about moving to just Python 3 in some new compliance checker version.  In particular, handling Unicode in Python 2 has been fairly painful.

I think it'd be good to revisit this sometime after the CF 1.7 milestone is completed.

**Comment by giumas** [comment]
@benjwadams got it! Given the coming [Py2 EOF](https://pythonclock.org/), it makes total sense.

**Comment by benjwadams** [comment]
Going to close this out as keeping the issue open doesn't really assist with anything.  With the upcoming Python 2 EOL, I'll say that for future major versions, Python 2 will be unlikely to be supported.
