### ISSUE TITLE
CF duplicate axis check fails incorrectly

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#562]
For a file with the following structure:
```
dimensions:
        TIME = 26577 ;
        HEIGHT_ABOVE_SENSOR = 25 ;
        DIST_ALONG_BEAMS = 25 ;

variables:
        double TIME(TIME) ;
                TIME:axis = "T" ;
        double LATITUDE ;
                LATITUDE:axis = "Y" ;
        double LONGITUDE ;
                LONGITUDE:axis = "X" ;
        float HEIGHT_ABOVE_SENSOR(HEIGHT_ABOVE_SENSOR) ;
                HEIGHT_ABOVE_SENSOR:axis = "Z" ;
        float NOMINAL_DEPTH ;
                NOMINAL_DEPTH:axis = "Z" ;
        float DIST_ALONG_BEAMS(DIST_ALONG_BEAMS) ;
                // no axis attribute (this is not strictly a depth/height coordinate)

        float ABSIC1(TIME, DIST_ALONG_BEAMS) ;
                ABSIC1:coordinates = "TIME LATITUDE LONGITUDE DIST_ALONG_BEAMS" ;
                ABSIC1:_FillValue = 999999.f ;
                ABSIC1:long_name = "backscatter_intensity_from_acoustic_beam_1" ;
                ABSIC1:units = "count" ;
```
I get a failing CF check with the message:
```
§5.0 Variable ABSIC1 does not contain d:3:     5/ 6 : duplicate axis Z defined
                                                      by NOMINAL_DEPTH
```
This is referring to the section of [CF](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#coordinate-system) (6th paragraph) that says:
> it is not permissible for a data variable to have both a coordinate variable and an auxiliary coordinate variable, or more than one of either type of variable, having an axis attribute with any given value

However in this case the `ABSIC1` variable has _no_ associated coordinate variables of either kind that define an axis="Z" attribute, so I think the checker is wrong.

It's true that there are two variables int he file that have axis="Z" (`HEIGHT_ABOVE_SENSOR` and `NOMINAL_DEPTH`), but I think this is allowed, as long as no other variable names _both_ of them as associated coordinate variables, which is the case in this file.

**Comment by mhidas** [comment]
Here is a sample of the file demonstrating this issue: [imos_duplicate_axis.zip](https://github.com/ioos/compliance-checker/files/1805568/imos_duplicate_axis.zip)

**Comment by Bobfrat** [comment]
Makes sense to me. The file doesn't get flagged for this in the [UK Met office CF checker](http://puma.nerc.ac.uk/cgi-bin/cf-checker.pl) either.

@lukecampbell FYI

**Comment by Bobfrat** [comment]
Interestingly I get the same error message when I run the CF checker from [NASA](https://podaac-uat.jpl.nasa.gov/mcc/):

```
duplicate axis Z defined by NOMINAL_DEPTH
```

I wonder if the leveraged this code base or made the same assumptions.

**Comment by mhidas** [comment]
Thanks @Bobfrat !
