### ISSUE TITLE
CF integration tests failing

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#570]
All of the tests in [test_cf_integration.py](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/tests/test_cf_integration.py) are failing. Are they supposed to be passing? Are they just out of date?

**Comment by benjwadams** [comment]
A lot of these have to do with the old deprecated scoring -- certain parts of the checks changed and the "scored/out of" ratios changed.  We're doing away with the numeric scores and opting instead to report failing tests, so it's pretty likely we'll remove the checks for score in the integration tests as well.

**Comment by Bobfrat** [comment]
Yeah we should update those in the next minor release

**Comment by daltonkell** [comment]
With the merge of #599, is it now appropriate to close this issue?
