### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#571]
Just wondering if there is a plan to release a new version sometime soon?

How frequent are future releases likely to be?

We ([IMOS/AODN](http://imos.org.au/facilities/aodn/)) are using the compliance checker as part of our automated data publication software. We have been running it off our own fork of the repo. We are finally moving towards installing it straight off PyPI. However, there are a few outstanding bugs we need to fix before we can switch completely to the 3.x versions (e.g. #461, #535, #562). I plan to work on fixing these in the coming weeks, but we won't see the benefits until they're included in a release.

**Comment by Bobfrat** [comment]
@mhidas glad to here you guys are using the compliance checker. We were planning on a release in the next 2-4 weeks. We've been working on the [scoring overhaul](https://github.com/ioos/compliance-checker/milestone/11) in the refactor-scoring branch and were hoping to get some feedback over the next few weeks. I will work on the bugs you mentioned above so those can get into the next release as well.

We usually try to get a release every 3 months or so.

**Comment by mhidas** [comment]
:+1: Thank you!

**Comment by Bobfrat** [comment]
Just released [4.0.0](https://github.com/ioos/compliance-checker/releases/tag/4.0.0)

https://pypi.python.org/pypi/compliance-checker/4.0.0
