### ISSUE TITLE
Compliance Checker v4; CF -> _Netcdf4Dimid att warning

### ISSUE THREAD

**Issue by lbesnard** [ioos/compliance-checker#577]
Hi

I'm testing today the new version of the checker with the CF (latest) convention.

The checker, with following tested file:
```
compliance-checker --test=cf http://opendap.bom.gov.au:8080/thredds/dodsC/ramssa_l4_gds2/2018/20180101120000-ABOM-L4_GHRSST-SSTfnd-RAMSSA-09km-AUS-v02.0-fv01.0.nc
```

complained about ```_Netcdf4Dimid should begin with a letter and be composed of letters, digits, and underscores```.  I have struggled to find what this attribute is really about, however, I found many references of it online, such as this page
https://github.com/IOOSProfilingGliders/Real-Time-File-Format/wiki/Real-Time-File-Description
Which make me think this probably could be a valid variable attribute.

**Comment by Bobfrat** [comment]
@lbesnard I'll do a little research on this. It's failing the ```check_naming_conventions``` check from this interpretation: 

```
Variable, dimension and attribute names should begin with a letter
        and be composed of letters, digits, and underscores.
```

But we do have exceptions to this rule such as _FillValue. I could add _Netcdf4Dimid to the exceptions if needed.

**Comment by mhidas** [comment]
Thanks @kwilcox. @lbesnard was accessing a THREDDS server that is beyond our control.
In any case, it's not a checker problem, so this issue can be closed.
