### ISSUE TITLE
Time Out Error

### ISSUE THREAD

**Issue by fgayanilo** [ioos/compliance-checker#586]
I get 'Error while processing the job. Job Timed Out' error when I submit a small netCDF file (e.g. http://data.gcoos.org/data/waf/nc_by_platform/atm/ldn/2017/gcoos_ioos_station_DISL_PPTA_2017_09_atm.nc) on the web version.

**Comment by Bobfrat** [comment]
@fgayanilo Are you pasting that URL into the "provide a remote OPeNDAP Data URL here" form or browsing to that file in your local file system? The file processes fine, but the url doesnt appear to be an OPeNDAP url so it will timeout if you try to process it like that.

**Comment by benjwadams** [comment]
Nonetheless, the error ought to be a little clearer if it's not a proper OPeNDAP endpoint and should throw an error more quickly to the aforementioned effect, rather than taking a long time to time out and returning a timeout error.

**Comment by daltonkell** [comment]
Closing this issue as PR #70 fixes the time-out error
