### ISSUE TITLE
No option to skip only medium/low-level checks within a check method

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#589]
Sometimes a file will fail a specific check and it isn't practical or doesn't make sense to "fix" the file. Conveniently, the `skip_checks` option allows a specific check method to be skipped, allowing such a file to still pass the checker overall.

However, many check methods apply several individual checks, and in particular some return results with different weight/priority levels. For example the CF `check_latitude` method returns one result with HIGH priority, two with MEDIUM priority, and one LOW.

Could we make it possible to skip (or ignore the results from) the LOW and MEDIUM checks in that method, but still insist on the HIGH-priority check to pass?

**Comment by mhidas** [comment]
Possible solutions:
1. Provide an alternative `allow_fail` option, which could specify a check method _and_ a maximum priority level of failing checks (within that method) to allow (unlike `skip_checks`, the method would be executed, but the results filtered on output);
1. Break up such complex check methods so that each method only returns results and a single priority level (would need re-writing of many checks);
1. Provide a way to identify specific check results within a check method, and accept these as arguments to the `skip_checks` option (seems complex and would require all checks to be updated).

The first of these is probably the most practical, but still not very elegant. Just wondering if anyone has other ideas?

Of course there is also the option of running _all_ the checks, getting the json output and then writing my own code to filter the results as I please. But if this functionality is useful to more than just me (and IMOS/AODN), it could be worth implementing something in the core checker.

**Comment by benjwadams** [comment]
I'm not entirely clear on this issue.  I believe the `-c`/`--criteria` option already does this to some extent.
'lenient' corresponds to printing/failing only on HIGH priority checks,
'normal' on HIGH-MEDIUM
'strict' on HIGH-LOW

See also: 
https://github.com/ioos/compliance-checker/blob/833de218609179d7d23160381989170041144a1b/compliance_checker/runner.py#L78-L83
and
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/base.py#L38-L48

**Comment by mhidas** [comment]
Yes, that is useful, but it only allows you to ignore _all_ LOW and/or MEDIUM checks. We have some cases where we need finer control than that.

For example, if I generally want to apply `strict` criteria, but for whatever reason have a file with latitude  units set to "degree_n" instead of "degrees_north", this file would fail [`check_latitude`](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L1478) with low priority.  There's no way for me to skip/ignore _only_ that check for latitude units = "degrees_north". I can skip _all_ low-priority checks, or _all_ checks within `check_latitude`, including the high-priority one.

**Comment by benjwadams** [comment]
I might propose -A (all) instead of -H for high to make clear that all tests are skipped

**Comment by mhidas** [comment]
:+1: That sounds good to me, from the usage perspective.
`:L` to skip low-priority checks,
`:M` to skip medium _and low_,
`:A` to skip all.
Leaving the letter off should be equivalent to `:A`, for backwards compatibility, and because that will likely be the most common use case.

In terms of implementation, the complication is that currently any method specified in `sckip_checks` is not actually executed. This functionality could be useful to retain (e.g. if a patricular method takes too long to run on some files). Making the `:L` and `:M` options possible would require filtering the results after executing the full "skipped" method.

Otherwise the best alternative I can think of is to re-write the multi-prioirty-level  check methods into smaller ones that only return single priority levels, in which case the `check_method` option would not need altering.
