### ISSUE TITLE
Checker Result Disclaimer Needed

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/compliance-checker#595]
While the latest version of the compliance checker replaced the High, medium and low priority warnings with the terminology from each of the standards, the warning message simply means you haven’t met our interpretation of that check.  A disclaimer is needed in the documentation letting users know that the warnings are the IOOS (via RPS) interpretations of the standards.   Perhaps in future iterations we could implement a Pass/Fail system that answers the question,  “Is the file still considered to be following standards, if these messages are ignored”.

**Comment by benjwadams** [comment]
Would you be OK with the disclaimer being added to the README file?
Could you expound a bit upon the last sentence?  A lot of folks complained if we nominally considered some aspect of their metadata "failing" through the checker.  The recent overhaul of the scoring concept is supposed to show where possible issues are, as opposed to creating a scoring system.

**Comment by Bobfrat** [comment]
Disclaimer has been added to the README in this repo and also to the About page on the web version:
https://compliance.ioos.us/about
