### ISSUE TITLE
Plugin system for checkers

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#60]
This is a future issue.

Checkers should be done in a manner to allow independent authoring.  Typical Python approach to this is namespace packages, but caused me so much grief during initial packaging that I don't really want to revisit (nor is it a perfect solution anyway).

This looks like a great alternative: https://github.com/mitsuhiko/pluginbase

**Comment by danfruehauf** [comment]
:+1: for that. This is highly needed.

**Comment by mhidas** [comment]
We need this to be able to plug in our IMOS ckecks. @fxmzb123 will take a look at some possible options in the next couple of weeks.

**Comment by fxmzb123** [comment]
I had a look at the code and it seems that all checkers are derived from a few Base Classes. 

My thought for a simple plugin implementation:

1) For those checker classes required to register in ComplianceCheckerCheckSuite.checker, it must have two attributes: name and register_checker. The name is the key in the dict and register_checker is the flag to indicate whether it is registered in the dict.

2) Find all checker subclasses derived from the base class, then populate the ComplianceCheckerCheckSuite.checker according to the name and register checker attributes. subclasses without these 2 attribute are skipped.

3)  Add the name and register_checker attributes to four existing  checkers: CFBaseCheck, ACDDBaseCheck, IOOSBaseCheck, GliderCheck

For any new checkers to be used, it just needs to have a base class as its parent class and name and register_checker attributes.

**Comment by mhidas** [comment]
PR #99 waiting for review.

**Comment by daf** [comment]
Finally introduced in #173
