### ISSUE TITLE
Release 4.1.0 Proposal

### ISSUE THREAD

**Issue by daltonkell** [ioos/compliance-checker#602]
After merging PR #600, I think it's appropriate for a new minor release to 4.1.0 with the following description:
# Compliance Checker 4.1.0
### Functionality
Pull Request #600 enhances compliance checker speed with the use of an lru-cache (Least Recently Used) from `functools`. It also allows backwards-compatibility with the lru-cache for python2.7 via the [`functools32`](https://pypi.org/project/functools32/) backport module. 

PR #599 updates the Climate and Forecasting integration tests.

PR #598 puts reference links to metadata schemas into the compliance-checker output.

### Bug Fixes
Fixes the TravisCI build failures in `conda` environments found which initially caused #598 and #599 to fail.

---
@'ing @Bobfrat and @benjwadams , but if anyone has input on this it would be great to hear

**Comment by benjwadams** [comment]
Overall looks good, but should fix the error message which occurs when the memoized subclass of `netCDF4.Dataset` is deleted.

**Comment by mhidas** [comment]
Could you please also include PR #603 in this release?

**Comment by Bobfrat** [comment]
@mhidas yes, everything in master to date will get in this next release.

**Comment by benjwadams** [comment]
Could you create a milestone instead?

**Comment by Bobfrat** [comment]
New release is on PyPi
https://pypi.org/project/compliance-checker/
