### ISSUE TITLE
Installation problems on windows

### ISSUE THREAD

**Issue by duncombe** [ioos/compliance-checker#61]
I'm trying to test compliance-checker under windows with anaconda. `pip install compliance-checker` is freaking out with: 
```
HDF5_DIR environment variable not set, checking some standard locations ..
checking C:\Users\christopher.rae ...
checking /usr/local ...
checking /sw ...
checking /opt ...
checking /opt/local ...
checking /usr ...
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File  c:\users\christopher.rae\appdata\local\temp\1\pip_build_Christopher.Rae\netCDF4\setup.py", line 208, in <module>
    raise ValueError('did not find HDF5 headers')
ValueError: did not find HDF5 headers
```
@dpsnowden suggests it's probably related to the way PyTables or netcdf4-python were installed in conda for windows, and that @rsignell-usgs may have insight having installed related packages on windows.

**Comment by abirger** [comment]
@rsignell-usgs , @daf , @lukecampbell : Any news from the Windows battle-front? Should I invest time into squeezing my way through the countless problems with Windows native installation, or rather spend it on Linux virtual machine?..

**Comment by kknee** [comment]
@abirger - I would continue to stick with Linux at this point.

**Comment by rsignell-usgs** [comment]
The one hurdle for running the compliance checker on Windows is the dependence on the [udunitspy](https://github.com/blazetopher/udunitspy).    Although the udunits2 library is available on Windows, the udunitpy build script uses unix-like syntax that doesn't work on windows.   See this issue: https://github.com/Unidata/UDUNITS-2/issues/3#issuecomment-72639479

**Comment by rsignell-usgs** [comment]
@kknee, I bet if we had 30 min of @blazetopher time we could fix this.  Let me know if that's posssible.

**Comment by kknee** [comment]
@rsignell-usgs,  @blazetopher chatted about this a while back and my impression was that it would take more than 30 min.  

@blazetopher - please chime in if I misunderstood.

**Comment by rsignell-usgs** [comment]
@blazetopher tells me @lukecampbell is our man.

**Comment by abirger** [comment]
@rsignell-usgs , will it help if I have MinGW/msys installed, and can run Unix command in Bash scripts?..

**Comment by rsignell-usgs** [comment]
@abirger, we could hack it that way, but Cmake would be a better route for the future.  For someone who knows Cmake, I think it would take 30 min.   For someone who doesn't, substantially more time, as @kknee noted.

**Comment by lukecampbell** [comment]
@lukecampbell says that udunitspy right now is not compatible with Windows. Getting udunitspy to be compatible with windows isn't in the scope of compliance checker right now. Cmake isn't the issue I think. udunitspy uses swig to create the bindings compile either a (.dll, .so or .dylib) which allows the python interpreter to call udunits methods. I don't know what the level of effort is to update our setup.py and/or swig interface definitions (since DLL's have dramatically different binding types than .so or .dylib). 

I would actually be considerably more in favor of removing udunitspy from compliance checker and replacing it with an in-line units module.

**Comment by daf** [comment]
(pssst: #62)

**Comment by lukecampbell** [comment]
Yeah, that's from my recommendations early on.

**Comment by rsignell-usgs** [comment]
Sure, it's Swig.  But basically isn't it just taking the lib and include requirements from here
https://github.com/blazetopher/udunitspy/blob/master/setup.py#L34-L70
and putting it into the CMake config file?
http://www.swig.org/Doc1.3/Introduction.html#Introduction_build_system

So when I said 30 min, I meant 30 min for someone who knew Swig working with someone who knew CMake (could be the same person, could be two people).    I was kind of interested in this conversion process for reasons beyond just the compliance-checker.

**Comment by rsignell-usgs** [comment]
Here's an example of a conda-recipe that uses Cmake for Mac, Linux and Windows:
https://github.com/conda/conda-recipes/tree/master/libdynd

**Comment by carmelortiz** [comment]
@abirger Will document steps required to use VirtualBox and update documentation accordingly!
