### ISSUE TITLE
External checker plugins without either cc_spec and cc_spec_version attributes hidden from checker listing

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#610]
e.g. cc-plugin-glider, which does not yet implement `_cc_spec` attributes (but does have `_cc_spec_version`, see ioos/cc-plugin-glider#26)

Logic intended to keep `...:latest` version checkers from showing in the non-verbose list also squelches plugins that haven't switched to the latest name/version attr spec.  Verbose listing will show them.

**Comment by daltonkell** [comment]
Is this good to close as [ioos/cc-plugin-glider#26] (https://github.com/ioos/cc-plugin-glider/pull/26) has been merged?

**Comment by benjwadams** [comment]
^ We should list those checkers anyways, but going forward prefer that a version number is supplied.

**Comment by benjwadams** [comment]
Implemented by #659, closing.
