### ISSUE TITLE
Climatology Check and Test

### ISSUE THREAD

**Issue by daltonkell** [ioos/compliance-checker#619]
The `check_climatolological_statistics` [check](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L2929) in `cf.py` has a return statement in the middle of the function, cutting off the code underneath:

```
        # catchall
        return ret_val

        # otherwise match the following values with for variable with
        # `cell_methods` attributes
        # time: method1 within years time: method2 over years
        # time: method1 within days time: method2 over days

        ...
```
Additionally, the [test](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/tests/test_cf.py) for this check doesn't actually test anything:
```
    def test_climatology(self):
        dataset = self.load_dataset(STATIC_FILES['climatology'])
        results = self.cf.check_climatological_statistics(dataset)
        score, out_of, messages = self.get_results(results)
```

@benjwadams I know you have written a lot for this--if you'd like me to take a crack at it, I can

**Comment by benjwadams** [comment]
Addressed by #621
