### ISSUE TITLE
Alternative to udunitspy

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#62]
The udunitspy library is a swig wrapper (hard to install) around udunits, and udunits does not work/install on Windows properly.

@dpsnowden suggests perhaps making a pure python port (one may already exist) - I briefly looked and it seemed reasonable.

@abirger suggests perhaps a udunits webservice that can be optionally hit from the compliance-checker.  We could make udunitspy an optional dependency and react to import failure in code properly.

**Comment by dpsnowden** [comment]
FWIW  this exists http://coastwatch.pfeg.noaa.gov/erddap/convert/units.html

**Comment by daf** [comment]
Webservice?  Awesome!

**Comment by ocefpaf** [comment]
@daf I went ahead and made a ["iris_units"](https://github.com/ocefpaf/units/tree/master/units) module from the iris package as discussed in #81.  It is light weight and depends only on udunits2 and netcdf4-python, no swig!  The installation is easy and works on windows, see our conda [package](https://github.com/ioos/conda-recipes/pull/114/files).


However, I do not recommend using this yet.  There will be some changes to avoid fork-fragmentation.

Meanwhile, here is an example comparing `udunitspy` and `iris-units`:

http://nbviewer.ipython.org/gist/ocefpaf/60ecac928612f5ae8fed

All that is required for compliance-checker is covered there.

**Comment by dpsnowden** [comment]
@ocefpaf please add the best repo for the units module you're working on to this issue thread so that the team can look into integrating it.  Is it SciTools/cf_units or ocefpaf/cf_units ?

**Comment by ocefpaf** [comment]
https://github.com/ocefpaf/cf_units is my working fork of the **official** https://github.com/SciTools/cf_units.

The transition should be smooth (brave last words).  I think I got almost of all of `udunitspy` functionality, used in compliance-checker, in the example [here](http://nbviewer.ipython.org/gist/ocefpaf/60ecac928612f5ae8fed).  However, I recommend waiting a little bit for a release.  Here is our roadmap for the next days: https://github.com/SciTools/cf_units/issues/15#issuecomment-82898719

**Comment by lukecampbell** [comment]
My only issues with this approach are:

1. The library referenced still depends on the udunits shared library being installed.
2. ctypes is extremely prone to crashes. Due to the nature of using a duck-typed interpreted language of Python trying to call a strongly typed compiled language at runtime, there are lot's of chances to crash the application. My personal preference is Cython over both swig, ctypes and other binding supports.

I'm working on a lighter pure python implementation for udunits, but I don't have any idea when it will be done; but it will work on Windows and requires no compiled libraries (including XML).

**Comment by ocefpaf** [comment]
> 1. The library referenced still depends on the udunits shared library being installed.

Yes, but I disagree that this is a bad thing. Having a well established and widely used library (that is maintained by UNIDATA!) as a dependencies is a :+1: and not a :-1: .  Also, by depending on udunits you remove the burden of maintaining/copying the definitions to a new library.   

> 2. ctypes is extremely prone to crashes.

Can't comment on that, never had that issue before.  All I can say is that `cf_untis` is used inside iris it is well test.  Besides, better ctypes, that is in the python standard library, than swig.

The swig wrapper around udunitspy does not work on Windows at the moment.  And I do believe that `cf_units` is the shortest path to get compliance-checker on windows (with a tiny PR in fact).

All that said:

> I'm working on a lighter pure python implementation for udunits

Hey, I am all for it! :+1:

**Comment by ocefpaf** [comment]
> My personal preference is Cython over both swig, ctypes and other binding supports.

Hey, and here is the advantage of join forces with big groups supporting open source libraries:

https://github.com/SciTools/cf_units/issues/18

**Comment by daf** [comment]
This was resolved in #110/#114
