### ISSUE TITLE
check_climatological_statistics applied to non-climatology variables

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#626]
I'm just  testing the latest release (4.2.0) and getting warnings about climatological variables for a dataset that doesn't have any!

For example, [this file](http://thredds.aodn.org.au/thredds/catalog/IMOS/ABOS/SOTS/Pulse/real-time/catalog.html?dataset=IMOS/ABOS/SOTS/Pulse/real-time/IMOS_ABOS-SOTS_W_20150325T110000Z_Pulse_FV00_Pulse-11-2015-MRU-Surface-wave-height-realtime.nc) has (subset of CDL):
```
dimensions:
        TIME = 8526 ;
variables:
        double TIME(TIME) ;
                TIME:standard_name = "time" ;
                TIME:units = "days since 1950-01-01 00:00:00 UTC" ;
         float ACCEL_STDDEV(TIME) ;
                ACCEL_STDDEV:cell_methods = "TIME: standard_deviation (interval: 10 min)" ;
                ACCEL_STDDEV:coordinates = "TIME LATITUDE LONGITUDE" ;
                ACCEL_STDDEV:units = "metres second-2" ;
        float ACCEL_AVG(TIME) ;
                ACCEL_AVG:cell_methods = "TIME: mean (interval: 10 min)" ;
                ACCEL_AVG:coordinates = "TIME LATITUDE LONGITUDE" ;
                ACCEL_AVG:units = "metres second-2" ;
```
As far as I can tell this is perfectly valid use of the `cell_methods` attribute, and they are **not** climatological variables. However, when I run the checker v4.2.0 on it, I get:
```
                                    Warnings                                    
--------------------------------------------------------------------------------
§7.4 Climatological Statistics
* The "time: method within years/days over years/days" format is not correct in variable ACCEL_STDDEV.
* The "time: method within years/days over years/days" format is not correct in variable ACCEL_AVG.
* The "time: method within years/days over years/days" format is not correct in variable ACCEL_STDDEV.
* The "time: method within years/days over years/days" format is not correct in variable ACCEL_AVG.
```

**Comment by mhidas** [comment]
It looks like the problem is [here](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L2970), applying the climatology-specific regex to _all_ `cell_methods` attributes, not just those of identified climatology data variables.

I also note that there's a `get_climatology_variable` function in [cfutil.py](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cfutil.py#L657), and a `_find_clim_vars` method in the CF check suite, but this doesn't seem to be used in the relevant check methods.

**Comment by daltonkell** [comment]
From the [CF 1.7 Standards](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#climatological-statistics), here's an example they give of a dataset with compliant climatology attributes:
```
dimensions:
  time=4;
  nv=2;
variables:
  float temperature(time,lat,lon);
    temperature:long_name="surface air temperature";
    temperature:cell_methods="time: minimum within years time: mean over years";  // <--- adjusted cell_methods
    temperature:units="K";
  double time(time);
    time:climatology="climatology_bounds";  // <--- variable with climatology attr
    time:units="days since 1960-1-1";
  double climatology_bounds(time,nv);
data:  // time coordinates translated to date/time format
  time="1960-4-16", "1960-7-16", "1960-10-16", "1961-1-16" ;
  climatology_bounds="1960-3-1",  "1990-6-1",
                     "1960-6-1",  "1990-9-1",
                     "1960-9-1",  "1990-12-1",
                     "1960-12-1", "1991-3-1" ;
```
My understanding is that, if a dataset has a variable with the `climatology` attribute, *only then* should the `cell_methods` attributes of any of the variables be checked to conform to
```
time: method1 within years   time: method2 over years  
time: method1 within days    time: method2 over days
time: method1 within days    time: method2 over days   time: method3
```
Simply indenting the code block [here](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L2970) to fall under the `if` on line 2909 above seems to resolve this particular issue, and I think it's more accurate according to the standard.

Running the CF check again on that same dataset yields:
```
--------------------------------------------------------------------------------
                         IOOS Compliance Checker Report                         
                                     cf:1.7                                     
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html
--------------------------------------------------------------------------------
                               Corrective Actions                               
IMOS_ABOS-SOTS_W_20150325T110000Z_Pulse_FV00_Pulse-11-2015-MRU-Surface-wave-height-realtime.nc has 1 potential issue


                                     Errors                                     
--------------------------------------------------------------------------------
§3.3 Standard Name
* standard_name modifier  for variable VAVH is not a valid modifier according to appendix C
```

All the tests pass with no changes. If this makes sense, this can be implemented in the next PR.

@mhidas @benjwadams @Bobfrat

**Comment by mhidas** [comment]
:+1: Thanks!
(Apologies for the late review)
