### ISSUE TITLE
CF-1.6 numpy error

### ISSUE THREAD

**Issue by christensenmichael0** [ioos/compliance-checker#650]
When upload a .nc file (using CF-1.6) I'm seeing this error:

Error while processing the job.

AttributeError: 'numpy.ndarray' object has no attribute 'lower'

**Comment by benjwadams** [comment]
Could you provide a file and run compliance checker with the `-v` argument so we can see where this error is occurring?

**Comment by benjwadams** [comment]
This was due to non-string attributes being passed into the `standard_name_vocabulary` global attribute and subsequently trying to call `.lower()` on the attribute, which was obviously not implemented.

**Comment by benjwadams** [comment]
Fixed by #651, closing.
