### ISSUE TITLE
`wmo_platform_code` check

### ISSUE THREAD

**Issue by daltonkell** [ioos/compliance-checker#653]
The IOOS Metadata Profile, v1.2 defines a new global variable in `wmo_platform_code` in the `platform` [section](https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#platform). If the dataset uses a platform where a WMO code is appropriate, the `wmo_platform_code` is a required global attribute. Otherwise, it's not required.

Since the Compliance-Checker has no real way to discern applicability, I believe the check should be skipped if the attribute is not present; if it is present, we can check how well the string is formed.

@mwengren would you mind weighing in on this?

**Comment by mwengren** [comment]
@daltonkell Makes sense to me.  Stations are not required to have a `wmo_platform_code`, but if it exists we want to ensure it meets formatting requirements.  I believe it's a 5 digit numerical value.

cc @kbailey-noaa @kevin-obrien Can you confirm what is expected to be in a WMO identifier?

**Comment by kevin-obrien** [comment]
Yes, in most cases, WMO platform codes are 5 or 7 digit numbers.   There some exceptions to this rule (notably, ship call signs), but I don't think that should be an issue with IOOS platforms...

**Comment by kbailey-noaa** [comment]
There are also shore-based stations that are part of this data pipeline to the GTS that have 5-digit alphanumeric IDs.  Those IDs are technically NWS Location Identifiers, not WMO platform codes, but NDBC delivers the data to the GTS under those IDs, so they have somewhat the same purpose.  e.g. an NOS water level station, a c-man station, basically any station on a pier would qualify, as opposed to buoys or gliders.

**Comment by daltonkell** [comment]
Great, I'll write this one in and check it off the list. Thanks @mwengren @kbailey-noaa @kevin-obrien

**Comment by daltonkell** [comment]
Addressed by #766

**Comment by mwengren** [comment]
Two-for-one issue closing, nice!
