### ISSUE TITLE
Add remote ERDDAP examples to README

### ISSUE THREAD

**Issue by Bobfrat** [ioos/compliance-checker#673]
For example:
compliance-checker -t gliderdac "https://gliders.ioos.us/erddap/tabledap/bios_jack-20170920T1928"

**Comment by ocefpaf** [comment]
@Bobfrat if compliance-checker can take a remote netCDF file we can support the sliced `.nc` response too. However, I'm not sure I would like to support that b/c we never really know the size of the file users will try to inspect. Maybe that only makes sense if we add a metadata only test (`.cdl`) to cc.

**Comment by daltonkell** [comment]
I'm a bit confused about this. Whenever I use an ERDDAP URL (e.g. from TableDap), I get an error like this:

```
$ python cchecker.py -t ioos https://pae-paha.pacioos.hawaii.edu/erddap/tabledap/AWS-HIMB.nc

Running Compliance Checker on the datasets from: ['https://pae-paha.pacioos.hawaii.edu/erddap/tabledap/AWS-HIMB.nc']
syntax error, unexpected $end, expecting ';'
context: Error { code=404; message="Not Found: Currently unknown datasetID=AWS-HIMB.nc";}^
Traceback (most recent call last):
  File "cchecker.py", line 228, in <module>
    sys.exit(main())
  File "cchecker.py", line 202, in main
    options=options_dict)
  File "/home/dalton/compliance-checker/compliance_checker/runner.py", line 65, in run_checker
    ds = cs.load_dataset(loc)
  File "/home/dalton/compliance-checker/compliance_checker/suite.py", line 716, in load_dataset
    return self.load_remote_dataset(ds_str)
  File "/home/dalton/compliance-checker/compliance_checker/suite.py", line 727, in load_remote_dataset
    return Dataset(ds_str)
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -90] NetCDF: file not found: b'https://pae-paha.pacioos.hawaii.edu/erddap/tabledap/AWS-HIMB.nc'
```

Am I doing something wrong?

**Comment by mwengren** [comment]
Hi @daltonkell.  I asked @Bobfrat this same question not too long ago when I couldn't remember myself what to do.  

The answer is to leave out the format part of the request:
```
 python cchecker.py -t ioos https://pae-paha.pacioos.hawaii.edu/erddap/tabledap/AWS-HIMB
```
will work. 

This is good because it give the flexibility to pick what format to request from ERDDAP for a particular test.  We may need this for IOOS 1.2 checks, but stay tuned.

**Comment by daltonkell** [comment]
Closing with the merging of #778
