### ISSUE TITLE
Amount of data within file affects run time

### ISSUE THREAD

**Issue by mbiddle-bcodmo** [ioos/compliance-checker#70]
This isn't an error but more of a question. What is actually causing the script to run soo slow when the data within the file is increased? For example, I have one file that is 325MB, which has been reduced down to 41KB by clearing out some (a lot) of the data points. All of the variables and attributes have stayed exactly the same, only the dimensions and amount of data has changed. When I run the CF check on the smaller (41KB) file, it completes in a matter of seconds. However, when I run the CF check on the larger (325MB) file, it takes forever to run (I'm on hour two of runtime right now). Does the checker actually need to pull in each individual data point within the file? Isn't it just checking variable attributes and global attributes? FYI, I'm running with both files on my local system...

**Comment by danfruehauf** [comment]
We are encountering the same problem with gridded files. It takes a while to load a ~100MB file into memory. Depending on filesystem IO it can be ~1-2 minutes per file. In other words - too slow.

I would suggest to add a command line argument which will load only attributes and variables without the whole data. This can imply that checks that rely on testing all the points in a data set will not run. On the other hand, it'll be much quicker for 80% of the tests (at least for us) which just verify existence of attributes and variables.

@lbesnard

**Comment by mhidas** [comment]
@fxmzb123 is looking into this issue.

**Comment by mhidas** [comment]
@fxmzb123 The two files in [this catalog](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/SRS/SST/catalog.html) are an example of this issue.

The first is 66Mb gridded dataset. The CF checker takes almost 2 mintues to check it.
The other has exactly the same attributes and structure, just  much less data. CF checker runs in just over a second.

**Comment by daf** [comment]
This is not exclusive to CF checks, ACDD confirms that time extent metadata matches the actual variable data which involves a min/max check on the time variable.

**Comment by DanielJMaher** [comment]
@daf @lukecampbell @kwilcox 

Do we want to wrap this up into #202 and make a more intensive system for skipping tests and not accessing datasets during tests?

**Comment by daf** [comment]
It could be a similar solution to what I proposed in #202 with a decorator:

```python
@accesses_remote_data()
def check_some_remote_data_stuff(self, ds):
...
```

and control the running of those via command line flags (`--allow-remote-data=True` or similar).  It should probably produce skips in the output a la unit tests.

**Comment by lukecampbell** [comment]
yeah that would be good!

**Comment by kwilcox** [comment]
@DanielJMaher can you point me to a test that reads a bunch of data? I just looked through the CF checks and nothing stood out.

**Comment by kwilcox** [comment]
@daf linked me to the ACDD checks that put the coordinate axis in memory. Any others?

**Comment by benjwadams** [comment]
May be worthwhile to profile the code execution for these larger datasets where there is a problem.  There should, to my knowledge, only be attribute access and possibly checking the first/last element of variable data.

**Comment by benjwadams** [comment]
@mbiddle-bcodmo @mhidas, I've revisitied this issue with a > 1GB glider file and am getting about a 5 second maximum runtime on the ACDD checker.  Further investigation with `cProfile` reveals that the bulk of the runtime was for `check_lon_extents` and `check_lat_extents`, both of which ran data access against the lon and lat min/max respectively.  Running the CF checker took 1.34 seconds.

One major change that has been made recently is that  #600 memoized a lot of repeated function calls so they didn't have to be called over and over again, and this sped up a lot of operations.

Please see if you have the same issues.  Ideally, if you find you are still having issues with a particular file, link to a THREDDS dataset endpoint or `.nc` file so that I can profile the code execution and see where possible bottlenecks may lie.

**Comment by mhidas** [comment]
Thanks @benjwadams . I haven't encountered any such issues in a while. I have also just done a quick CF & ACDD check on a few  1+ Gb files and they all ran in a couple of seconds. So as far as I'm concerned, this issue can be closed.

**Comment by mbiddle-bcodmo** [comment]
This is great! Thanks @benjwadams! Unfortunately I haven't used the check in quite a while. But, I just tested it with a 2.4 GB gridded file from NCEI (https://www.ngdc.noaa.gov/thredds/catalog/regional/catalog.html?dataset=regionalDatasetScan/chesapeake_bay_M130_2017.nc) and it ran in seconds. This performance is much better.
