### ISSUE TITLE
Fixing AppVeyor failures

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#705]
Looks like there are a couple AppVeyor failures:

On `master`, a couple packages seem to be conflicting when Conda attempts to build compliance checker:
Excerpt from https://ci.appveyor.com/project/ocefpaf/compliance-checker/builds/28942286:
```
cf-units[version='>=2'] -> antlr-python-runtime=4.7.2
Package python-dateutil conflicts for:
pendulum[version='>=1.2.4'] -> python-dateutil[version='>=2.6,<3.0']
Note that strict channel priority may have removed packages required for satisfiability.
```
On the `cf_1_7_dev_rebase` branch, changes introduced by the [CF Appendix A checks](https://github.com/ioos/compliance-checker/pull/694) caused issues in the `test_multi_checker_return_value` test:
https://ci.appveyor.com/project/ocefpaf/compliance-checker/builds/28942286
```
================================== FAILURES ===================================
___________________ TestCLI.test_multi_checker_return_value ___________________
self = test_multi_checker_return_value (compliance_checker.tests.test_cli.TestCLI)
    def test_multi_checker_return_value(self):
        '''
        Tests that any failure for multiple checkers results in a failure return
        status
        '''
        # CF should pass here
        return_value, errors = ComplianceChecker.run_checker(
            ds_loc=STATIC_FILES['ncei_gold_point_1'],
            verbose=0,
            criteria='strict',
            checker_names=['cf:1.6'],
            output_filename=self.path,
            output_format='text'
        )
>       self.assertTrue(return_value)
E       AssertionError: False is not true
compliance_checker\tests\test_cli.py:227: AssertionError
```
As mentioned in the referenced pull request for this issue, @Bobfrat attempted to build using Conda against the PR branch and was unable to reproduce the test failures.  Any information on how to better reproduce the test environment would be appreciated.

**Comment by benjwadams** [comment]
I tried again using Conda and was able to replicate some of the build/test failures this time around.  It looks like the first issue may be related to versioning conflicts when building the environment under Python 2.7.  My ken at updating conda recipes is somewhat limited, so I don't immediately know how I might fix these specifications.

The second issue appears to be due to endianness comparisons for numeric types, which I've been bitten by in the past.  I'll fix that one.

**Comment by benjwadams** [comment]
Related: 820006c43f3f0babfa42cb7909261d2fbda67f7d
Relaxes endianness checking on numeric types.

**Comment by ocefpaf** [comment]
> It looks like the first issue may be related to versioning conflicts when building the environment under Python 2.7. 

Looking into that.

**Comment by benjwadams** [comment]
Thanks @ocefpaf.  I'll take care of the remaining failure on the CF 1.7 feature branch and then we should be hopefully be good to go for merging this in.

**Comment by benjwadams** [comment]
Looks like a regression occurred with respect to the AppVeyor runs under 2.7.  I can't figure out why -- it looks like build script changes introduced by #707 are still there.

**Comment by benjwadams** [comment]
Possibly due to PyProj dependency?  Looks like the pinned versions under Conda only support Python 3.  The Travis builds completed and my local Python 2.7 runs of the tests work fine though.

**Comment by ocefpaf** [comment]
> Possibly due to PyProj dependency? Looks like the pinned versions under Conda only support Python 3. The Travis builds completed and my local Python 2.7 runs of the tests work fine though.

In #707 `pyproj` is not specified. That is a legit issue due to https://github.com/ioos/compliance-checker/commit/c39bed1cf4c839fd7d47f772246b2c6181c484a0

If that version is really needed we should drop Python 2.7 support.

**Comment by benjwadams** [comment]
Thanks, I'll have a look tomorrow and come to a decision and make a release.  I've unassigned you since this was an issue brought about by a change I pushed. The updated PyProj versions were for consistent handling of the Proj4 database, which I determined was the simplest way to determine various CRS-related names.  I tried, but could not find ways to check if the CRS was valid without resorting to querying the PyProj database.  I'll see if it's possible to squeak by with an earlier pinned version.  If not, I'll probably have to drop official Python 2 support.

**Comment by benjwadams** [comment]
OK, I think the DB references for WKT validation are fine, elsewhere it looks like `pyproj.CRS.from_wkt` is used.  In terms of tagged releases, that will probably require at least 2.x series for PyProj.  The latest build on conda-forge targeting both Windows x64 and Python 2.7 appears to be PyProj 1.9.6: https://anaconda.org/conda-forge/pyproj/files?sort=basename&sort_order=desc&page=1

Unless someone wants to attempt to build this on conda, it'll likely continue to be unsupported.  Assuming no packages are added to conda-forge, I'd like to just say that building Python 2.7 under Conda will be unsupported for now on so that we can create a release candidate.  I haven't formally put it anywhere in issues yet, but Python 2.7 generally is likely to follow on the next release given the upcoming EOL of Python 2.7 at the beginning of the new year.

@ocefpaf, OK to remove Python 2.7 from the AppVeyor test matrix here?  https://github.com/ioos/compliance-checker/blob/master/.appveyor.yml#L6

**Comment by ocefpaf** [comment]
>  The latest build on conda-forge targeting both 64-bit Windows and Python 2.7 appears to be PyProj 1.9.6: anaconda.org/conda-forge/pyproj/files?sort=basename&sort_order=desc&page=1

Yep. `Proj >=6` does not build with `vc9` (Python 2.7 on Windows).
> @ocefpaf, OK to remove Python 2.7 from the AppVeyor test matrix here? 

IMO yes. We don't have any officials plans to drop Python 2.7 in IOOS but based on my assessment last DMAC we are OK dropping support in Jan 1st, 2020.

**Comment by benjwadams** [comment]
We're now good after removing the Py2.7 build from AppVeyor.  Closing this issue.
