### ISSUE TITLE
Compile Glider DAC v2.0 requirements so that we can estimate the work needed for Glider checks.

### ISSUE THREAD

**Issue by dpsnowden** [ioos/compliance-checker#71]
@kknee, this fell off the plate during the last round of development because we hadn't yet solified the glider format.  Once you and @kerfoot are certain that the ioos/ioosngdac file description is accurate, we need to include this in our release planning for the next phase of development.  I expect that there will be other more granular issues all attached to this milestone.  This issue is just there to get the ball rolling toward planning.  @BeckyBaltes note that the milestone currently has no date.  Up to the team to figure out where it fits in the overall release planning.

**Comment by daf** [comment]
@lukecampbell done or still WIP?
