### ISSUE TITLE
cf_role check message unclear

### ISSUE THREAD

**Issue by daltonkell** [ioos/compliance-checker#718]
In the check for valid `cf_role` attribute

https://github.com/ioos/compliance-checker/blob/380e16a4f84135605632d75e398564d6885d0de1/compliance_checker/cf/cf.py#L3832-L3839

the message indicates that the *variable* is not a valid `cf_role`, when the `cf_role` attribute itself should be displayed.

**Comment by benjwadams** [comment]
Closed by #860.
