### ISSUE TITLE
CF check for actual_range fails for packed values and if _FillValues are used

### ISSUE THREAD

**Issue by yosoyjay** [ioos/compliance-checker#721]
The CF check for `actual_range` can erroneously fail under two conditions:
- If `_FillValues` is used
- If the data is packed and `valid_range` is defined

The `check_actual_range` method removes the mask exposing the `_FillValue` to be used as the basis for testing the range specified in `actual_range` [cf.py](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L3994-L3995).

If `valid_range` is also defined, the compliance checker will ensure that `actual_range` falls within the `valied_range` [cf.py](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L4028-L4029).  If data is packed it is extremely likely that the packed and unpacked data are of different types, e.g. (short for packed and float for unpacked).  If the file is following [CF 1.7](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#missing-data), the unpacked `actual_range` should be of the same type and match the actual range of the values.  However, the [NUG v4.7.3](https://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html) stipulates that the `valid_range` should have the same data type as the packed data.  So in a situation where data is packed, the checker is comparing data of two different types.

Finally, given that there is an actual comparison of floating point data in this test, the test is likely to be more robust if it used `np.close()` instead [an equivalence test in cf.py](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L4015-L4018).

**Comment by benjwadams** [comment]
> Finally, given that there is an actual comparison of floating point data in this test, the test is likely to be more robust if it used np.close() instead an equivalence test in cf.py.

#870 has taken care of this portion.  I will check out the other portions of this issue here.

**Comment by benjwadams** [comment]
@yosoyjay , I think #871 should fix this.   I'm not sure what purpose explicitly removing the mask served, but it gave some erroneous results.  From there, the transformation of `add_offset` and `scale_factor` values along with changes introduced in #870 should hopefully address the issues mentioned above.

**Comment by benjwadams** [comment]
I don't think `valid_min`/`valid_max` are handled when checking that things are contained within `actual_range`.  I'll check this tomorrow.
