### ISSUE TITLE
Sample ERDDAP datasets to test with Metadata Profile 1.2 

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#723]
@ioos/compliance-checker: Listing some existing ERDDAP datasets that have been updated to be compliant with version 1.2 of the IOOS Metadata Profile that you can test with for the upcoming milestone:

PacIOOS:
- https://pae-paha.pacioos.hawaii.edu/erddap/info/AWS-HIMB/index.html

SECOORA:
- http://erddap.secoora.org/erddap/tabledap/edu_usf_marine_comps_1407d550.html

CeNCOOS:
- http://erddap.cencoos.org/erddap/tabledap/bodega-bay-bml_wts.html
- http://erddap.cencoos.org/erddap/tabledap/fort-point.html
- http://erddap.cencoos.org/erddap/tabledap/edu_humboldt_humboldt.html
- http://erddap.cencoos.org/erddap/tabledap/edu_calpoly_marine_morro.html
- http://erddap.cencoos.org/erddap/tabledap/mlml_mlml_sea.html
- http://erddap.cencoos.org/erddap/tabledap/mlml_mlml_met.html
- http://erddap.cencoos.org/erddap/tabledap/mlml_monterey.html
- http://erddap.cencoos.org/erddap/tabledap/edu_humboldt_tdp.html

We also have several listed in the [Gold Standard Examples](https://ioos.github.io/ioos-metadata/gold-standard-examples.html) section of the profile (which might have overlap with the above).  

We're also working with NERACOOS on updating their ERDDAP with new datasets that comply with the profile, more info on that probably coming soon.

Hopefully I haven't missed any stations from various lists that have gone around.  Others can contribute updates/corrections to this if they have any.

cc: @jessicaaustin @ebridger

**Comment by jessicaaustin** [comment]
That looks like a good starting point. Also, I am happy to help test these compliance checker updates when they are ready, just message me here!

**Comment by pacioos** [comment]
PacIOOS:
- https://pae-paha.pacioos.hawaii.edu/erddap/info/AWS-HIMB/index.html
- https://pae-paha.pacioos.hawaii.edu/erddap/info/AWS-HNLPier1/index.html
- https://pae-paha.pacioos.hawaii.edu/erddap/info/WQB-04/index.html
- https://pae-paha.pacioos.hawaii.edu/erddap/info/WQB-05/index.html

**Comment by daltonkell** [comment]
Closing with the merging of #778
