### ISSUE TITLE
Add test for flag_values and flag_meanings

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#764]
Most likely we'll be adding the CF flagging-variables that apply to QARTOD variables per the IOOS profile - see: https://github.com/ioos/ioos-metadata/pull/16. 

These attributes are `flag_values` and `flag_meanings` as in Chap 3.5: http://cfconventions.org/cf-conventions/cf-conventions.html#flags.

In anticipation of that, can we add a check for these to the IOOS 1.2 plugin?  These would be recommended variables, so essentially the check would be to note `not present` if they're missing, and confirm they meet the CF requirements as described above if included.

**Comment by daltonkell** [comment]
@mwengren I think we have the machinery necessary for this already in the CF module.

Say we're testing [org_cormp_sun2.nc](http://testing.erddap.axds.co/erddap/tabledap/org_cormp_sun2.nc). The metadata for variable `air_temperature_qc_agg` looks like this:

```
        int air_temperature_qc_agg(row) ;
                air_temperature_qc_agg:_ChunkSizes = 7393, 2 ;
                air_temperature_qc_agg:_FillValue = 2 ;
                air_temperature_qc_agg:_Unsigned = "true" ;
                air_temperature_qc_agg:actual_range = 1, 4 ;
                air_temperature_qc_agg:flag_meanings = "PASS NOT_EVALUATED SUSPECT FAIL MISSING" ;
                air_temperature_qc_agg:flag_values = "1, 2, 3, 4, 9" ;
                air_temperature_qc_agg:ioos_category = "Other" ;
                air_temperature_qc_agg:long_name = "Air Temperature QARTOD Aggregate Quality Flag" ;
                air_temperature_qc_agg:missing_value = 2 ;
                air_temperature_qc_agg:references = "http://services.cormp.org/quality.php" ;
                air_temperature_qc_agg:standard_name = "aggregate_quality_flag" ;
```

The spec requires the `flag_values` to be an array, so the result of the CF test is:

```
...

§3.5 Flags
* air_temperature_qc_agg's flag_values must be an array of values not <class 'str'>

...
```

What do you think? I can get this into the IOOS checker by calling the CF checker. @benjwadams and I have already implemented something similar.

**Comment by mwengren** [comment]
Sure, let's add it.  Kudos for writing reusable code.  

Like I mentioned above the IOOS 1.2 check should do the following:

- note 'not present' using the standard phrasing for both `flag_values` and `flag_meanings` attributes for any QARTOD QC variables (identified by containing a valid QC standard name listed in the `qartod_variable:standard_name` table row here: https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#quality-controlqartod)
- use the CF checker validator rules to note when they're improperly formed
