### ISSUE TITLE
JSON/HTML output renders results with messages even if result passes (result display rendering logic discrepancies)

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#784]
The HTML and JSON formats will output any result objects which contain messages, even if the result itself passes.  This behavior is different than the plaintext output, which does not appear to output results when a given result passes.   Ideally the rendering of all results should use consistent rules.

Related to, and probably causing issues in #780, #757, #760.

**Comment by mwengren** [comment]
Resolved by #787, closing.
