### ISSUE TITLE
CF actual_range float comparison

### ISSUE THREAD

**Issue by daltonkell** [ioos/compliance-checker#785]
There is an attempted float comparison in the `actual_range` check:

https://github.com/ioos/compliance-checker/blob/5cab47362d80ebf9dc9afcf7c1cf2c3c4a97edcb/compliance_checker/cf/cf.py#L4006-L4017

Should look into using float comparison testing methods from `numpy`, or else precision nuances may indicate failures when datasets are compliant.

**Comment by benjwadams** [comment]
Use `numpy.isclose` and similar methods.

**Comment by benjwadams** [comment]
Closed by #860
