### ISSUE TITLE
Usage message not consistent with accepted command-line arguments

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#80]
The command-line usage message (output of `compliance-checker -h`) seems to suggest several ways of specifying which tests to apply:

     optional arguments:
      --test {acdd,cf,ioos} [{acdd,cf,ioos} ...], -t {acdd,cf,ioos} [{acdd,cf,ioos} ...], --test= {acdd,cf,ioos} [{acdd,cf,ioos} ...], -t= {acdd,cf,ioos} [{acdd,cf,ioos} ...]

However, several of these variants:

    $ compliance-checker -t acdd test.nc
    $ compliance-checker --test acdd test.nc
    $ compliance-checker --test= acdd test.nc

result in:

    compliance-checker: error: argument --test/-t/--test=/-t=: invalid choice: 'test.nc' (choose from 'acdd', 'cf', 'ioos')

Maybe the usage should just say it has to be `-t={acdd,cf,ioos}` or `--test={acdd,cf,ioos}` to keep it simple.

Also, it's not quite clear how to specify multiple tests. Comma or space-separated lists don't work.

**Comment by lukecampbell** [comment]
We fixed this when I rewrote the argument parser
