### ISSUE TITLE
command line option to download latest CF version does not work

### ISSUE THREAD

**Issue by s-pearce** [ioos/compliance-checker#803]
Update:  The only issue after some digging is now the `-d latest` does not work and causes a Python
exception: `requests.exceptions.HTTPError: 404 Client Error:` because it is looking for the CF directory "latest" which does not exist.  I am leaving the old trail of comments to show my confusion from the operation of the `-d` option.  I suggest adding a text snippet to the option description saying that it may use the CF standard name table described in the global attribute `standard_name_vocabulary`.

Previous:
I am finding that the `-d` option does not work properly from the command line interface. 
I tried to download CF standard name using `-d 71` and although it is downloaded and I can find the actual file for version 71 under the Anaconda site-packages location for compliance-checker it continues to create a cache and use version 27, even after the cached version has been deleted.  Also using latest as the argument to the `-d` option completely fails.  Here are the outputs over several attempts.
```
(base) C:\Users\spearce\data>compliance-checker -d 71
Downloading cf-standard-names table version 71 from: http://cfconventions.org/Data/cf-standard-names/71/src/cf-standard-name-table.xml
<and then prints out the -h usage, omitted here for brevity>

(base) C:\Users\spearce\data>compliance-checker -d 71 -f text -o compliance_output.txt --test=cf:1.6 ce_311_20190504T022740Z_delayed.nc
Downloading cf-standard-names table version 71 from: http://cfconventions.org/Data/cf-standard-names/71/src/cf-standard-name-table.xml
Running Compliance Checker on the datasets from: ['ce_311_20190504T022740Z_delayed.nc']
Downloading cf-standard-names table version 27 from: http://cfconventions.org/Data/cf-standard-names/27/src/cf-standard-name-table.xml
Using downloaded standard name table v27

(base) C:\Users\spearce\data>compliance-checker -d 71 -f text -o compliance_output.txt --test=cf:1.6 ce_311_20190504T022740Z_delayed.nc
Downloading cf-standard-names table version 71 from: http://cfconventions.org/Data/cf-standard-names/71/src/cf-standard-name-table.xml
Running Compliance Checker on the datasets from: ['ce_311_20190504T022740Z_delayed.nc']
Using cached standard name table v27 from C:\Users\spearce\.local\share\compliance-checker\cf-standard-name-table-test-27.xml

(base) C:\Users\spearce\data>compliance-checker -d latest
Traceback (most recent call last):
  File "C:\Users\spearce\Anaconda3\Scripts\compliance-checker-script.py", line 1
0, in <module>
    sys.exit(main())
  File "C:\Users\spearce\Anaconda3\Scripts\cchecker.py", line 175, in main
    download_cf_standard_name_table(args.download_standard_names)
  File "C:\Users\spearce\Anaconda3\lib\site-packages\compliance_checker\cf\util.
py", line 338, in download_cf_standard_name_table
    r.raise_for_status()
  File "C:\Users\spearce\Anaconda3\lib\site-packages\requests\models.py", line 9
41, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://cfcon
ventions.org/Data/cf-standard-names/latest/src/cf-standard-name-table.xml
```

**Comment by s-pearce** [comment]
Oh and I am using an Anaconda 3 installed for a specific user on Windows 7.
compliance-checker was installed with `conda install compliance-checker`

**Comment by s-pearce** [comment]
update, I am able to spoof it in the meantime by renaming version 72 as the same name as the cached version 27.

**Comment by s-pearce** [comment]
So I now realize that the Global Attribute `standard_name_vocabulary` within the netCDF file I was submitting, dictated which CF standard name table version to use.  If I change the version number in that attribute, the code correctly chooses that version.

I also see if I remove that attribute, the `-d` option seems to work fine; downloading and applying the version I ask for.

However, I am leaving this issue open because `-d latest` still causes an exception
`requests.exceptions.HTTPError: 404 Client Error:`
because it is looking for a CF directory named "latest" that does not exist.

**Comment by benjwadams** [comment]
Possibly check your running version of compliance checker -- I'm not able to reproduce this on master.  A feature was added to automatically parse standard name table links and fetch the latest one in a fairly recent commit: https://github.com/ioos/compliance-checker/commit/4586968d6c41441f5c1aa8fc3d92e8ca02427ece  .  When running against master, if I specify 'latest' to the `-d` option, I get back version 72 of the CF standard name tables, which is the most recent as of the time of this writing.  It's possible the built version doesn't have this feature yet.  If that is the case, just try using an explicit version number as you have done.

**Comment by s-pearce** [comment]
Thanks Ben.  You are right.  My apologies for not checking that the conda built version was the same as the latest Github version.  I do still suggest an explanatory statement that it will use the version described in the `standard_name_vocabulary` global attribute, but I am closing the issue.
Thanks, 
Stuart
