### ISSUE TITLE
check_data_types exception during cf test: type object 'str' has no attribute 'kind'

### ISSUE THREAD

**Issue by ancillary** [ioos/compliance-checker#809]
Using version 4.3.3rc2+54.gb086b57, I am getting the following exception for all of our netcdf files under cf:1.6 and cf:1.7 test... an example netcdf file: 
http://gyre.umeoce.maine.edu/ncei/neracoos/A01/A0141.ocean.001m.merged.nc

WARNING: The following exceptions occured during the cf:1.7 checker (possibly in
dicate compliance checker issues):
cf:1.7.check_data_types: type object 'str' has no attribute 'kind'
  File "c:\apps\anaconda3\envs\cc-test-dev\lib\site-packages\compliance_checker-
4.3.3rc2+54.gb086b57-py3.8.egg\compliance_checker\cf\cf.py", line 1326, in check
_data_types
    if v.dtype.kind != "S" and all(

Any thoughts appreciated.

**Comment by benjwadams** [comment]
NetCDF4-Python casts string-like attributes to `str` type, which is does not have `numpy`'s kind attribute.   There is code in the checker to address this discrepancy, but it looks like not all the edge cases are handled.  I'll take a look at what's occurring with this particular dataset.

**Comment by neumannd** [comment]
@benjwadams : What about checking in `cf.check_data_types` for type of `str` this way (the `if v.dtype is not str:` is new):

``` python
    def check_data_types(self, ds):
        """
        Checks the data type of all netCDF variables to ensure they are valid
        data types under CF.

        CF §2.2 The netCDF data types char, byte, short, int, float or real, and
        double are all acceptable

        :param netCDF4.Dataset ds: An open netCDF dataset
        :rtype: compliance_checker.base.Result
        """
        fails = []
        total = len(ds.variables)

        for k, v in ds.variables.items():
            # NEW: 
            if v.dtype is not str:
                if v.dtype.kind != "S" and all(
                    v.dtype.type != t
                    for t in (
                        np.character,
                        np.dtype("|S1"),
                        np.dtype("b"),
                        np.dtype("i2"),
                        np.dtype("i4"),
                        np.float32,
                        np.double,
                    )
                ):
                    fails.append(
                        "The variable {} failed because the datatype is {}".format(
                            k, v.datatype
                        )
                    )
        return Result(
            BaseCheck.HIGH,
            (total - len(fails), total),
            self.section_titles["2.2"],
            msgs=fails,
        )
```

**Note:** We need to check for `v.dtype is not str` because `not isinstance(v, str)` does not work (because `v` is of type `netCDF4._netCDF4.Variable`.

**Comment by neumannd** [comment]
Created a pull request for this. Hope that's what you thought of.
