### ISSUE TITLE
A dataset with a global "platform" attribute must platform have variables

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#817]
I feel like this particular unclear notification was fixed at some point, but a recent test of NANOOS dataset http://data.nanoos.org/erddap/tabledap/OOI_CE09OSSM with release 4.3.3 produced this output:

  * platform: A dataset with a global "platform" attribute must platform have variables

I'm not sure what we're trying to say here.... 'must have a Platform variable'?  

Can we investigate?

**Comment by benjwadams** [comment]
Link currently points at empty page.
