### ISSUE TITLE
CF checker doesn't allow additional conventions in Conventions attribute

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#82]
The test `check_conventions_are_cf_16` in cf.py requires the **Conventions** global attribute to be exactly equal to the string "CF-1.6". This is indeed what the [CF conventions document](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#identification-of-conventions) _recommends_. However, the [NetCDF User's Guide](http://www.unidata.ucar.edu/software/netcdf/docs/netcdf.html#Attribute-Conventions) allows this attribute to be a blank- or comma-separated list of convention names. 

Could the check be modifed to look for "CF-1.6" as a sub-string of the **Conventions** attribute?

E.g. [IMOS](http://imos.org.au/) data will usually have Conventions = "CF-1.6,IMOS-1.3". We would like these files to pass the CF checker.

**Comment by dpsnowden** [comment]
I think that was always the idea.  Another need for having this flexibility is that OceanSITES, ACDD, and perhaps Argo all specify their own conventions and versions.  We already support ACDD so we should be checking for it's presence in the Conventions attribute.  We should probably err on the side of warnings and not errors when we encounter misuse of these identifiers.  For example, we should encourage the use of ACDD-1.1 and not "Unidata Data Discovery Conventions 1.1" which you still see in practice.
