### ISSUE TITLE
issues with respect of generation of netCDF files from cdl files by the web-based IOOS Compliance Checker

### ISSUE THREAD

**Issue by neumannd** [ioos/compliance-checker#831]
# Problem description

The web-based IOOS Compliance Checker seems to generate netCDF files from cdl files with all dimensions set to length of 1. This might lead some checks to fail. This does not seem to affect the IOOS Compliance Checker in general but only the web-based version.

* Version IOOS Compliance Checker: 4.3.3
* Check: CF-1.7
* only web-bass IOOS CC affected; IOOS CC installed via conda forge  runs fine

# Reproduction of the Issue

Example input file header:

```
netcdf example_header_atmodat_standard { 
 dimensions: 
 	time = UNLIMITED ; // (25 currently) 
 	nv2 = 2 ; 
 	nv4 = 4 ; 
 	y = 106 ; 
 	x = 112 ; 
 	z = 1 ; 
 variables: 
 	double time(time) ; 
 		time:long_name = "time_bnds" ; 
 		time:bounds = "time_bnds" ; 
		time:axis = "T" ;
 		time:units = "seconds since 1900-01-01 00:00:00.0 UTC" ; 
		time:calendar = "noleap" ;
 	double time_bnds(time, nv2) ; 
 		time_bnds:units = "seconds since 1900-01-01 00:00:00.0 UTC" ; 
 	float lat(y, x) ; 
 		lat:bounds = "lat_bnds" ; 
 		lat:long_name = "latitude" ; 
 		lat:standard_name = "latitude" ; 
 		lat:units = "degree_north" ; 
		lat:axis = "Y" ;
 	float lat_bnds(y, x, nv4) ; 
 	float lon(y, x) ; 
 		lon:bounds = "lon_bnds" ; 
 		lon:long_name = "longitude" ; 
 		lon:standard_name = "longitude" ; 
 		lon:units = "degree_east" ; 
		lon:axis = "X" ;
 	float lon_bnds(y, x, nv4) ;  
 	float ta(time, z, y, x) ; 
 		ta:coordinates = "lon lat" ; 
 		ta:missing_value = -9.e+33f ; 
 		ta:standard_name = "air_temperature" ; 
 		ta:units = "K" ; 
  
 // global attributes: 
 		:Conventions = "CF-1.7" ; 
 		:history = "Wed Jul  6 09:40:15 2020: test\nWed Sep  6 10:35:40 2017: *some detailled NCO call ...*" ; 
		:license = "CC BY 4.0" ;
 		:standard_name_vocabulary = "CF Standard Name Table v45" ; 
 		:title = "Test" ; 
 }
```

Provide this file to the web-base IOOS Compliance Checker (https://compliance.ioos.us/) generates a netCDF file starting with

```
netcdf uploaded-file {
dimensions:
	time = 1 ;
	nv2 = 1 ;
	nv4 = 1 ;
	y = 1 ;
	x = 1 ;
	z = 1 ;
```

This leads to some warnings:

> §2.4 Dimensions: ta's dimensions are not in the recommended order T, Z, Y, X. They are time, z, y, x
> §7.1 Cell Boundaries: Dimension time_bnds of boundary variable (for  time) must have at least 2 elements to form a simplex/closed cell with  previous dimensions ('time',).
> §7.1 Cell Boundaries: Dimension lat_bnds of boundary variable (for  lat) must have at least 3 elements to form a simplex/closed cell with  previous dimensions ('y', 'x').
> §7.1 Cell Boundaries: Dimension lon_bnds of boundary variable (for  lon) must have at least 3 elements to form a simplex/closed cell with  previous dimensions ('y', 'x').

In contrast, when I manually generate a netCDF file from the cdl file via `ncgen INPUT_FILE.nc -o OUTPUT_FILE.nc` and provide this file to the web-based IOOS Compliance Checker, everything runs fine.

The IOOS Compliance Checker installed via conda-forge (same version as web-based checker) does generate the netCDF file properly (same file as when I call `ncgen` manually).

**Comment by daltonkell** [comment]
Successfully reproduced using my local development environment. Thanks for raising @neumannd, I'm looking into it.

**Comment by daltonkell** [comment]
@neumannd I'm going to close this as it's actually a Compliance Checker Web issue rather than an inconsistency in the Checker code here. Thanks again for raising. I have raised an issue in the Compliance Checker Web repository at https://github.com/ioos/compliance-checker-web/pull/112.
