### ISSUE TITLE
Add checks for new IOOS Metadata Profile 1.2 attributes: precision, accuracy, resolution, etc

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#839]
We made some new additions to IOOS Metadata Profile 1.2.  Specific commit can be found [here](https://github.com/ioos/ioos-metadata/commit/1eb32fa679b1b015493e75383808a8920e42b94e) for reference.

As I mentioned in https://github.com/ioos/compliance-checker/issues/819#issuecomment-657763655, we should add new checks for the following attributes (all recommended):
* `geophysical_variable:accuracy`
* `geophysical_variable:precision`
* `geophysical_variable:resolution`
* `instrument_variable:calibration_date`
* `instrument_variable:make_model`
* `instrument_vocabulary`

**Comment by daltonkell** [comment]
@mwengren In the specification, it is not mandated that `accuracy, precision, resolution` be numeric. Should this be tested for, or is it insignificant? Similarly, formats for `instrument_variable:calibration_date` (default ISO-8601?) and `instrument_variable:make_model` are not specified either.

**Comment by mwengren** [comment]
@daltonkell 

For `accuracy, precision, resolution` I think we only state they be the same units as the variables themselves.  Can this be tested easily? @jessicaaustin @lukecampbell what do you think - single value in same units OK?

For `calibration_date` I think ISO-8601 is appropriate.  I'll add that to the description unless anyone objects to that change.

`make_model` I would expect to be string values.  We don't want to over prescribe here I think, so that field should probably not be checked for compliance with a data type or pattern.

**Comment by daltonkell** [comment]
I think not over-prescribing is the right move :+1:

**Comment by mwengren** [comment]
Updated `calibration_date` description.  Are we good with the others?

**Comment by daltonkell** [comment]
Does "being the same units" mean "must include a units string"? E.g.

```
0.0025 degree_c
   |      |
quantity units
```

in which case the entire attribute would have to be a string.

**Comment by mwengren** [comment]
Hmmm.  This may be getting over my head, but I assumed by saying that  we were intending the value of the attribute to be numeric, and the units to match those specified in the `units` attribute.

**Comment by daltonkell** [comment]
Nope, that's what how I read it, just wanted to be crystal clear!

**Comment by jessicaaustin** [comment]
@daltonkell @mwengren Sorry for the delay in commenting, I was out on vacation. Here's my two cents:

* `make_model` -- i agree this could be any arbitrary string, so the only validation i could think of is check that it's not empty if it's provided
* `calibration_date` -- agreed this should be ISO-8601 format and should be validated as such
* accuracy, precision, and resolution (RAP)
  * Dalton you asked if it should include the units string. I think the answer is no. For example, you could provide `resolution: 0.1` for a water temp variable, and that would mean that it had an accuracy of `0.1 degrees C` if `units: degree_Celsius` was set on that variable. So basically I'm agreeing with Micah here.
   * I think we should be incredibly lenient on the validation for RAP attributes -- maybe just check that the value is not empty if it's provided. See the discussion under https://github.com/ioos/ioos-metadata/pull/28 for more background, but basically the values here could be much more complex than a simple numeric value -- for example the accuracy could be a function of depth (see [Appendix B for the data sheet](https://oceanobservatories.org/wp-content/uploads/2015/10/1341-00040_Data_Product_SPEC_PRACSAL_OOI.pdf) as a concrete example). 
   * That said, for NDBC/GTS, when they read salinity the explicitly want to know what the `accuracy` is, and we should ensure that the data provider is giving them something they should parse. So... could we add some extra validation if `gts_ingest: true`? Thoughts? 
       * If `gts_ingest: true` => any variable with `standard_name: sea_water_practical_salinity` should have a variable attribute called `accuracy` with a numeric value

**Comment by daltonkell** [comment]
Thanks for the input @jessicaaustin. I read through https://github.com/ioos/ioos-metadata/pull/28 and based on this and your above comment, I present:

- `precision` and `resolution` must be of the same units as the variable; whether they are explicitly encoded as numeric or not is irrelevant
- `accuracy` should be numeric __if__ the standard_name of the variable is `sea_water_practical_salinity` -- otherwise, it should just be present and in the same units (could be a more complex expression)

All three variables are `recommended`.

Are we good with testing for ISO-8601 representation for `calibration_date`?

**Comment by mwengren** [comment]
From Jessica's comment:

> That said, for NDBC/GTS, when they read salinity the explicitly want to know what the accuracy is, and we should ensure that the data provider is giving them something they should parse. So... could we add some extra validation if gts_ingest: true? Thoughts?
> - If gts_ingest: true => any variable with standard_name: sea_water_practical_salinity should have a variable attribute called accuracy with a numeric value

I'm not sure how much case logic we want to code into these checks, but it probably does make sense to only run the test you mentioned if `gts_ingest=True` for both global attribute and the salinity variable-specific attribute:

> accuracy should be numeric if the standard_name of the variable is sea_water_practical_salinity -- otherwise, it should just be present and in the same units (could be a more complex expression)

Since we don't mention these salinity-specific requirements in the metadata profile (yet), it seems they should only be reported on in the specific case of those variables being flagged for GTS ingest, to reduce confusion, hopefully.

**Comment by lukecampbell** [comment]
Since we're talking about the compliance checker I don't think there's a way for the tested dataset to communicate to the checker whether or not the value represented by the attribute has units or not, if it's a numeric value. So for the purpose of creating a check, the check wouldn't be able to verify anything except that the attribute exist and that it's data type matches the associated variable.

For the sake of clarity, if the attribute is a scalar value, is it implied that the value represents a range like ±0.25°C would be `0.25` ?

**Comment by daltonkell** [comment]
That's how I'm interpreting it, @lukecampbell.

So for now we're scratching the salinity context and instead, only if the variable attribute `gts_ingest` is `true`, we should test if the values are numeric?

**Comment by mwengren** [comment]
@daltonkell This is getting kind of confusing.  

How about we go with what @jessicaaustin said earlier, slightly adapted:

 If `gts_ingest: true` => any variable with `standard_name: sea_water_practical_salinity` and `gts_ingest: true` should have a variable attribute called `accuracy` with a numeric value

This fits with what you said in an earlier comment:

> `accuracy` should be numeric __if__ the standard_name of the variable is `sea_water_practical_salinity` -- otherwise, it should just be present and in the same units (could be a more complex expression)

with the addition of the check for variable-level `gts_ingest` attribute.
