### ISSUE TITLE
Miniconda on Linux requires setuptools for pkg_resources/running tests

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#84]
I need to explicitly install setuptools in my miniconda environment in order to run the tests.  Not sure if this is a platform issue, miniconda issue - should it be added to requirements.txt?

**Comment by abirger** [comment]
@daf , as far as I can recall I did not have to do that with a complete Anaconda. However, I had to set up the channels in `condarc`, and at some point install `binstar` (do not remember though was it on Windows or Linux).

**Comment by daf** [comment]
Will be fixed with #116

**Comment by daf** [comment]
Now #173

**Comment by daf** [comment]
Fixed in #173
