### ISSUE TITLE
Compliance Checker -- NCEI 

### ISSUE THREAD

**Issue by cyhsu** [ioos/compliance-checker#851]
https://github.com/BobSimons/erddap/issues/33

Question: In the DMAC meeting today, I addressed issues that are related to the Trajectory Profile dataset. One of the questions is the IOOS compliance checker - NCEI Trajectory Profile Orthogonal 2.0. The checker is asking the Trajectory Profile netCDF file must to set "cdm_data_type" = "Trajectory" and then set "featureType" = "trajectoryProfile," while in ERDDAP, it is saying "cdm_data_type" = "TrajectoryProfile". 

Please check whether we need to update the NCEI checker or which standard we need to follow. Thanks.

This is from [ERDDAP documents](https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html)
<img width="579" alt="Screen Shot 2020-10-14 at 4 08 39 PM" src="https://user-images.githubusercontent.com/5323645/96045418-89a1bb00-0e37-11eb-90a8-3a9d25a14688.png">

If I set cdm_data_type = "TrajectoryProfile"
<img width="783" alt="Screen Shot 2020-10-14 at 4 06 04 PM" src="https://user-images.githubusercontent.com/5323645/96045148-2c0d6e80-0e37-11eb-9818-b618f985a8ed.png">

and put this netCDF file to [IOOS compliance checker website](https://compliance.ioos.us/index.html)
<img width="1011" alt="Screen Shot 2020-10-14 at 4 06 47 PM" src="https://user-images.githubusercontent.com/5323645/96045214-447d8900-0e37-11eb-9982-bb31ba6bc7fa.png">

**Comment by benjwadams** [comment]
Please put issues with the NCEI checker over on https://github.com/ioos/cc-plugin-ncei/
