### ISSUE TITLE
New libnetcdf 4.8.0 introduces a bug on Windows, causing regression in Compliance Checker

### ISSUE THREAD

**Issue by openSourcerer9000** [ioos/compliance-checker#859]
**What's the problem?**

@daltonkell and I noticed this issue when [all of the tests failed in my PR](https://github.com/daltonkell/compliance-checker/runs/2384112222?check_suite_focus=true) which rely on ncgen-ing from a CDL file in test setup (126 failed). All tests had passed on local. While my local env uses libnetcdf 4.7, the github server built the env with the brand new libnetcdf 4.8.0. 

After some troubleshooting we were able to narrow it down to [this specific regression in netcdf-c 4.8.0, which we raised on their repo.](https://github.com/Unidata/netcdf-c/issues/1988). We were unable to produce the bug on Linux; it seems it is an issue in Windows only. 

For our developers, it's causing PR's to fail on github's microsoft server running windows. For our users, it will fail in the specific case that they try running the checker on a .cdl file provided as an absolute path on Windows. The below call will reproduce this with v4.8.0:

```
$ compliance-checker --test=cf:1.6 C:\Users\you\Desktop\temp\test_cdl.cdl
...
```
```
...
FileNotFoundError: [Errno 2] No such file or directory: b'C:\\Users\\you\\Desktop\\temp\\test_cdl.nc'
```

From the context of the linked netcdf-c issue, this happens because ncgen is generating the .nc at a bad path, then the checker attempts to check the file in the correct path, which doesn't exist.

**What's the solution?**

What I propose for now is simply to hardcode libnetcdf=4.7 into the github server testing env and the compliance-checker package, as this issue only arises with libnetcdf 4.8. 

Eventually we can let it upgrade once the netcdf-c issue has been resolved.

**Comment by benjwadams** [comment]
CI failures on Windows due to this issue addressed by #862.  We'll probably move to use the next netCDF version after a new release is issued on Unidata's end.
