### ISSUE TITLE
ncei-trajectory:2.0 low priority suggested global attribute checks

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/compliance-checker#861]
I am running a file against the ncei-trajectory:2.0 template and I think there is something wonky going on with the `data_metdata_modified` low priority check. The contents of the attribute `date_metadata_modified` are in ISO-8601 format (eg. "2021-04-20"). From the looks of the message, the check is looking for an ISO duration, not date, which I don't think is correct. Below is the message from the checker:
> date_metadata_modified should exist and be ISO-8601 format (example: PT1M30S), currently: 2021-04-20

Also, it looks like the `contributor_name` and `contributor_role` checks are duplicated:

> * contributor_name should exist and not be empty.
> * contributor_role should exist and not be empty.
> * contributor_name should exist and not be empty.
> * contributor_role should exist and not be empty.

**Comment by benjwadams** [comment]
Please create issues for the NCEI plugin over on the [cc-plugin-ncei repo](https://github.com/ioos/cc-plugin-ncei/).  Closing.
