### ISSUE TITLE
New release of compliance-checker

### ISSUE THREAD

**Issue by ocefpaf** [ioos/compliance-checker#866]
@daltonkell and @benjwadams it has been a while since the last release and a number of issues are fixed in the unreleased code, like #865. Should we merge #862 and #860 and issue a release? I'm not sure if you do a changelog or not, also if this would be a bugfix release or some major/minor changes are included. Please let me know if I can help you with that.

Pinging @mwengren and @MathewBiddle.

**Comment by benjwadams** [comment]
Outstanding PRs have been merged, but there appear to be some issues with the CI for `cc-plugin-glider` tests when attempting to run some of the NCEI related checks.

**Comment by benjwadams** [comment]
Update: I'd like to get #871 reviewed and merged prior to cutting a release.

**Comment by mhidas** [comment]
Hi All! Looking forward to the new release!
However, I'd like to note a couple of issues I've found with the current version of the code (on master branch):
* Issues with feature type checking (https://github.com/ioos/compliance-checker/pull/858#pullrequestreview-640541090)
* Exceptions when checking attributes scale_factor and add_offset (https://github.com/ioos/compliance-checker/issues/842#issuecomment-888861214)

Sorry I don't have time to help fix these at the moment. Any chance they could be looked at before the release?

**Comment by benjwadams** [comment]
@mhidas, I'm actively trying to wrap up at least some of the `scale_factor` and `add_offset` issues prior to release and have also made a number of fixes regarding some portions of their implementation.

**Comment by ocefpaf** [comment]
@benjwadams I'm locked out of my PyPI account (https://github.com/pypa/pypi-support/issues/1201). Do you mind setting the token and the secrets on GH so we can merge #867?

**Comment by benjwadams** [comment]
4.3.4 was released and appears to have successfully built on PyPI via GitHub Actions.  Closing.
