### ISSUE TITLE
Change issue template to request CDL or NetCDF files upon filing issues

### ISSUE THREAD

**Issue by benjwadams** [ioos/compliance-checker#876]
It is usually much more helpful when someone is reporting a bug to attach a CDL or NetCDF file showing at least a minimal example of the file structure that is causing a problem.  This makes debugging the issues much easier, however we don't currently request that the bug reporters attach a file.  As a result, we have to attempt to replicate the NetCDF file contents without much prior knowledge, and this makes picking up some of these bugs and fixing them more difficult.

@mwengren, I don't have the necessary permissions to modify this repo to add verbiage in the default issue template.  Could you please modify the default issue template to request a minimal CF or NetCDF file for the purposes of replicating compliance checker bugs?  This would considerably help with backlogged issues going forward.

**Comment by benjwadams** [comment]
Something along these lines would be good:

--------------------------------------------------

Current version of compliance checker running


Describe the checker this affects.  The ACDD, IOOS, and CF checkers are currently considered in scope for the purposes of the issue tracking on this repository.  Issues with other plugins should be placed into their respective repositories.

Attach a minimal CDL or NetCDF file which is able to reproduce the issue.

Describe the issue below:

**Comment by mwengren** [comment]
Ok, it's done: https://github.com/ioos/compliance-checker/issues/new/choose

Let me know if anything needs changing or let's go ahead and close this one out.

**Comment by benjwadams** [comment]
Thanks @mwengren.  This should go a long way towards helping make bug reports easier to reproduce.  Going to close now.
