### ISSUE TITLE
Incorrect attribute name in CF test check_data_types

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#88]
Whenever I run the CF checker, I get the following message at the start of the results:

    The following exceptions occured during the cf checker (possibly indicate compliance checker issues):
    cf.check_data_types: NetCDF: Attribute not found

Running it in verbose mode also prints a stack trace which points to line 271 of cf.py:

        for k, v in ds.dataset.variables.iteritems():
            if v.datatype not in [np.character,
			                     ...

Assuming v is a NetCDF4.Variable object, it should be `v.dtype` instead of `v.datatype`.

**Comment by mhidas** [comment]
PS: I just realised this was an issue with the version of the NetCDF4 module I was using (1.0.4). The [changelog](https://github.com/Unidata/netcdf4-python/blob/master/Changelog) for v1.0.5 includes:
> * add datatype property for Variable that returns numpy dtype for primitive
> datatypes (same as dtype attribute) but returns CompoundType or VLType
> instance for compound or vlen variables (issue 178).

In any case this will make the code compatible with earlier versions, and also more self-consistent, as `v.dtype` is used elsewhere in the code.

**Comment by daf** [comment]
I was wondering why I did not get the same error, but did see the
consistency issue.
