### ISSUE TITLE
check_scalar_coordinate_system not quite correct

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#89]
CF test `check_scalar_coordinate_system` aims to test CF's recommendation "against using a name for a scalar coordinate variable that matches the name of any dimension in the file" ([Section 5.7](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#scalar-coordinate-variables)). Scalar variables have `shape == ()`.

However, the code seems to check for coordinate variables associated with dimensions of size one (having `shape == (1,)` - see line 1662 in [cf.py](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L1668)), which are not quite the same thing.

Also, I don't see why this test wouldn't be applied to ALL scalar variables, not just ones listed in another variable's _coordinates_ attribute?

**Comment by mhidas** [comment]
[Here](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ABOS/SAZ/catalog.html?dataset=IMOS/eMII/checker_test/ABOS/SAZ/IMOS_ABOS-SOTS_RFK_20120724T000000Z_SAZ47_FV01_SAZ47-2012Sediment-Trap-Data-IRS_20130701T000000Z_C-20150210T043901Z.nc) is an example. The issue shows up in the results as:

    MASS_FLUX                          :2:     4/ 5 :  
        scalar_coordinates             :2:     0/ 1 : Scalar coordinate var
                                                      (DEPTH) of var (MASS_FLUX)
                                                      is correct size but is
                                                      present in the dimensions
                                                      list, which is not
                                                      allowed.

Here `DEPTH` is a proper coordinate variable. It does only have a single value, but it is not a "scalar coordinate variable" as defined here.

**Comment by daf** [comment]
Closed in #123
