### ISSUE TITLE
CF checker doesn't allow valid variables without units attribute

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#90]
The `check_units` test in cf.py returns a high-priority fail for variables without a _units_ attribute. Some exceptions are allowed for, but a couple of important ones are not:
 1) "Units are not required for dimensionless quantities" ([CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#units)), and
 2) It doesn't make sense for quality-control variables to have units, even if they are represented as numeric flags.

It's mainly the second case that is giving us errors for every IMOS file, where most data variables have an associated quality control flags variable of type byte.

Proposed solutions:
 1) Allow for more exceptions to this rule, e.g. exempt any variable with a _flag_values_ attribute. This will resolve the second issue above, but not the first.
 2) Make the 'check_units' test return a medium- or low-priority fail for variables that don't have a _units_ attribute. If the attribute does exist, the other checks on it should remain high-priority.

**Comment by benjwadams** [comment]
I ran into this today running the CF checker.  I noticed that the CF checker attempts to look for "modifiers" in standard names -- see  http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#standard-name-modifiers

In the case of flags, it's a `status_flag` separated by a space at the end of the standard name.  You'll notice that `status_flag` has no units in the table provided in Appendix C.  The checker picks up the modifier, so yet another method would be to look for a `status_flag` modifier, at least in the case of flag variables.

**Comment by mhidas** [comment]
@benjwadams Good point. The limitation of that approach is that it only works for variables that have an appropriate CF standard_name. Unfortunately for us this is not always the case. On the other hand, all quality flag variables should have a `flag_meanings` attribute, to explain what the flags mean. So I think the solution in #96  is good (we just need to get the unit test right...)

**Comment by mhidas** [comment]
Fixed in #102.
