### ISSUE TITLE
CF test check_coordinate_axis_attr is too strict

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#91]
The test `check_coordinate_axis_attr` in cf.py only allows coordinate variables (i.e. those with only one dimension, of the same name) to have an _axis_ attribute. However, the conventions document ([Chapter 4](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#coordinate-types)) states:
"The methods of identifying coordinate types described in this section apply both to coordinate variables and to auxiliary coordinate variables named by the coordinates attribute"

So this test should allow auxiliary coordinate variables to have an _axis_ attribute.

I think this is one of the issues reported in #83.

**Comment by mhidas** [comment]
[Here](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/timeSeries/catalog.html?dataset=IMOS/eMII/checker_test/ANMN/timeSeries/IMOS_ANMN-NRS_TZ_20140808T024500Z_NRSROT_FV01_NRSROT-1408-SBE39-27_END-20141216T025000Z_C-20141219T060000Z.nc) is a sample file that shows this issue.

The result in question looks like this:

    Name                             Priority:     Score:Reasoning
    --------------------------------------------------------------------------------
    axis                                   :3:    12/13 :  
    DEPTH                              :3:     3/ 4 :  
        is_coordinate_var              :3:     0/ 1 : DEPTH is not allowed to
                                                      have an axis attr as it is
                                                      not a coordinate var

**Comment by daf** [comment]
@mhidas can you elaborate on how the sample file shows an error?  I'm not a CF expert, but the way I'm reading the document:

DEPTH is not a coordinate variable (it does not have a dimension of the same name)
DEPTH is not an auxiliary coordinate variable (no variable has a coordinates attribute referencing DEPTH)

Therefore, an axis attribute is not allowed.  Am I reading this wrong?

**Comment by mhidas** [comment]
@daf You're absolutely right. Sorry, I picked the wrong file as an example.

[Here](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/timeSeries/catalog.html?dataset=IMOS/eMII/checker_test/ANMN/timeSeries/IMOS_ANMN-QLD_TZ_20140907T063947Z_ITFTIS_FV01_ITFTIS-1409-SBE39-94_END-20150207T065000Z_C-20150219T005030Z.nc) is a better one. E.g. the variable TEMP has attribute `TEMP:coordinates = "TIME LATITUDE LONGITUDE NOMINAL_DEPTH DEPTH" ;`

But in the results we still get

    axis                                   :3:    12/15 :
        LATITUDE                           :3:     3/ 4 :
            is_coordinate_var              :3:     0/ 1 : LATITUDE is not allowed to
                                                          have an axis attr as it is
                                                          not a coordinate var

... and similar for `LONGITUDE` and `NOMINAL_DEPTH`, which are all auxiliary coordinate variables.

**Comment by daf** [comment]
Thanks @mhidas, the patch now solves the issues seen there.

**Comment by daf** [comment]
Fixed via #95

**Comment by mhidas** [comment]
@daf Thanks, that looks good!
