### ISSUE TITLE
IOOS:1.2 Profile - Command Line `--display-checks` raises exception

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#934]
**Version of compliance checker running:**
`a37a961abf2bfb4b9c27b255ef7cb53cdc4148d3`

**Describe the checker this affects:**
IOOS:1.2

**Attach a minimal CDL or NetCDF file which is able to reproduce the issue**
N/A

**To Reproduce:**
```
compliance-checker -t ioos:1.2 buf.nc -D
```

**Describe the issue below:**
```
==========
 ioos:1.2
==========
Traceback (most recent call last):
  File "/home/luke/miniconda3/envs/compliance-checker/bin/compliance-checker", line 33, in <module>
    sys.exit(load_entry_point('compliance-checker', 'console_scripts', 'compliance-checker')())
  File "/home/luke/code/compliance-checker/cchecker.py", line 260, in main
    check_suite._print_checker(check_suite.checkers[checker_name])
  File "/home/luke/code/compliance-checker/compliance_checker/suite.py", line 107, in _print_checker
    check_functions = self._get_checks(checker_obj, defaultdict(lambda: None))
TypeError: _get_checks() missing 1 required positional argument: 'skip_checks'
```

**Expectation**
A list of the checks performed by the IOOS:1.2 profile to be displayed.

**Comment by benjwadams** [comment]
This was likely due to a change in the interface that added support for running only certain checks.  I've been trying to improve test coverage of most issues, but evidently, this one slipped through.

**Comment by lukecampbell** [comment]
Looks good! Thanks!
