### ISSUE TITLE
Compliance checker .ncCF attribute warning "_Encoding" - file and attribute generated by ERDDAP

### ISSUE THREAD

**Issue by jacobthompson101** [ioos/compliance-checker#936]
**Version of compliance checker running:**
v5.0.2

**Describe the checker this affects:**
_The ACDD, IOOS, and CF checkers are currently considered in scope for the purposes of the issue tracking on this repository. Issues with other plugins should be placed into their respective repositories._
CF 1.6 and greater.

Example warning output:
"....attribute buoy_name:_Encoding should begin with a letter and be composed of letters, digits, and underscores"

**Attach a minimal CDL or NetCDF file which is able to reproduce the issue**
[cmar_fca0_698a_0716_8f02_143d_7e69.zip](https://github.com/ioos/compliance-checker/files/8952467/cmar_fca0_698a_0716_8f02_143d_7e69.zip)

**To Reproduce:**
_List the steps or command line to run to reproduce the issue_
Export any appropriate dataset from ERDDAP datasets page, as a .ncCF file to then run in the compliance checker website at:
https://compliance.ioos.us/index.html

For example this dataset has a "String" datatype for Buoy Name, warning goes away if setting to "int" but that is just avoiding the warning not solving the underlying issue, since ERDDAP is adding the "_Encoding" attribute on .ncCF file download.
`<dataType>String</dataType>`

**Describe the issue below:**
_Any additional detail or information relevant to the issue_
The following links to the relevant code for a potential solution, not sure of the implications.
https://github.com/ioos/compliance-checker/blob/54f76447863069dc737779fee6a9ea9b3a3b15ce/compliance_checker/cf/cf_1_6.py#L232

The following function has a variable with the following, is it going to break something if we added "_Encoding" to this list of ignore attributes?
`"def check_naming_conventions"
...
ignore_attributes = [
            "_FillValue",
            "DODS",
            "_ChunkSizes",
            "_Coordinate",
            "_Unsigned",
        ]`

My goal in all of this is to "solve" all warnings/errors ideally, and I think that can help with data providers who are testing dataset CF compliance and potentially save some time. I don't know the implications of altering this, and my coworker and I were curious as why it wasn't originally added to this ignore list?

**Comment by benjwadams** [comment]
@jacobthompson101 , please check against latest master and if this looks good we can close this issue.

**Comment by benjwadams** [comment]
Closing due to passed test.
