### ISSUE TITLE
Improve CF Conformance: 4.3.3 Parameterized Vertical Coordinate

### ISSUE THREAD

**Issue by jamesdoyle21** [ioos/compliance-checker#946]
4.3.3 Parameterized Vertical Coordinate
Requirements:

- [x]  The formula_terms attribute is only allowed on a coordinate variable which has a standard_name listed in Appendix C.

 

- [x] The type of the formula_terms attribute is a string whose value is list of blank separated word pairs in the form term: var. The legal values term are contained in Appendix C for each valid standard_name. The values of var must be variables that exist in the file.

Note: Appendix C contains only the valid_modifiers list.

 

- [x] Where indicated by the appropriate definition in Appendix D, the standard_name attributes of variables named by the formula_terms attribute must be consistent with the standard_name of the coordinate variable it is attached to, according to the appropriate definition in Appendix D.

- [x]  The computed_standard_name attribute is only allowed on a coordinate variable which has a formula_terms attribute.

 

- [x] The computed_standard_name attribute is a string whose value must be consistent with the standard_name of the coordinate variable it is attached to, and in some cases also with the standard_name attributes of variables named by the formula_terms attribute, according to the appropriate definition in Appendix D.

- [x] The units of a variable named by the formula_terms attribute must be consistent with the units defined in Appendix D.

**Comment by benjwadams** [comment]
Closed by #946
