### ISSUE TITLE
Improve CF Conformance: 7.4 Climatological Statistics

### ISSUE THREAD

**Issue by jamesdoyle21** [ioos/compliance-checker#954]
7.4 Climatological Statistics
Requirements:

- [x]  The climatology attribute may only be attached to a time coordinate variable.

- [x]  The type of the climatology attribute is a string whose value is a single variable name. The specified variable must exist in the file.

 

- [x] A climatology variable must have the same dimension as its associated time coordinate variable, and have a trailing dimension (CDL order) of size 2.

 

- [x] A climatology variable must be a numeric data type.

 

- [x] If a climatology variable has units, standard_name, or calendar attributes, they must agree with those of its associated variable.

- [x]  A climatology variable must not have _FillValue or missing_value attributes.

**Comment by benjwadams** [comment]
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf_1_6.py#L2999-L3042 handles point 3 in both the dimension order and size.  Closing as already implemented.
