### ISSUE TITLE
CF: time variable incorrectly identified as non-standard calendar

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#971]
**Version of compliance checker running:** 5.0.2 (does not occur in 5.0.0)

**Describe the checker this affects:** CF (all versions)

**Attach a minimal CDL or NetCDF file which is able to reproduce the issue**
https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/SRS/SST/ghrsst/L4/GAMSSA/2022/20221119120000-ABOM-L4_GHRSST-SSTfnd-GAMSSA_28km-GLOB-v02.0-fv01.0.nc
The `time` variable has the following key attributes:
```
        int time(time) ;
                time:standard_name = "time" ;
                time:axis = "T" ;
                time:units = "seconds since 1981-01-01 00:00:00" ;
                time:calendar = "Standard" ;
```

**To Reproduce:**
`$ compliance-checker -t cf:1.6 ../NetCDF/20221119120000-ABOM-L4_GHRSST-SSTfnd-GAMSSA_28km-GLOB-v02.0-fv01.0.nc`

**Describe the issue below:**
The output includes
```
                                     Errors                                     
--------------------------------------------------------------------------------
§4.4 Time Coordinate
* For nonstandard calendar on variable time, attribute month_lengths must be supplied as a 12-element integer array
```
However, this variable _does_ use the standard calendar, so does not require a `month_lengths` attribute.

The only reason this is not correctly identified is that the value of the `calendar` attribute in this file begins with a capital letter, while the [code](https://github.com/ioos/compliance-checker/blob/b4e39458bc445f7e1c08a074f844ef4600ecc2aa/compliance_checker/cf/cf_1_6.py#L1951) checks this attribute in a case-sensitive way.

The [CF conventions document](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#calendar) doesn't mention case-sensitivity of the `calendar` attribute. However, the [Conformance Requirements and Recommendations](http://cfconventions.org/Data/cf-documents/requirements-recommendations/requirements-recommendations-1.6.html) says:
> The standardized values of the calendar attribute are gregorian, standard, proleptic_gregorian, noleap, 365_day, all_leap, 366_day, 360_day, julian, and none **(case insensitive)**.

**Comment by benjwadams** [comment]
Fixed by #987.
