### ISSUE TITLE
CF-1.9 and CF-1.10 compliance check?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/compliance-checker#972]
@benjwadams any ETA of when CF-1.9 and CF-1.10 compliance will be available?
In particular, I'm looking forward to the new datatypes allowed in CF-1.9 (particularly `int64`)!

**Comment by benjwadams** [comment]
Hey Rich, there is a 1.9 branch currently.  A lot of the focus has been on correcting some of the deficiencies the checker had with respect to conformance docs.  1.9 is mostly done, but not rebased against the aforementioned fixes in `master` yet.  One reason for the holdup is that we're having difficulty locating datasets that use [lossy compression by coordinate subsampling (Section 8.3)](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#compression-by-coordinate-subsampling) in the wild.  If you happen to know of any datasets that we could use a reference, it'd be very useful.

**Comment by benjwadams** [comment]
We may also release a partial 1.9 checker if desired without the lossy compression until we can properly understand and implement that section.

**Comment by benjwadams** [comment]
OK, we'll cut a release soon after some PRs have been merged and note the lack of the compression implementation in the README.

**Comment by benjwadams** [comment]
Closed with release of build support CF 1.9.  CF 1.10 will be upcoming.
