### ISSUE TITLE
compliance-checker conda update channels

### ISSUE THREAD

**Issue by abirger** [ioos/compliance-checker#98]
@lukecampbell , @daf , what is the schedule for the compliance-checker package release updates? I can see a lot of important changes and fixes done for compliance checker but every time I run conda update command, I get the same response:

```
Fetching package metadata: ........
# All requested packages already installed.
# packages in environment at /home/ioos/anaconda/envs/compliance_checker:
#
compliance-checker        1.0.0                    py27_0  

```

What would be the right way to get the most recent updates?

**Comment by lukecampbell** [comment]
Someone needs to update the conda recipe for compliance checker
https://github.com/ioos/conda-recipes/blob/master/compliance-checker/meta.yaml

**Comment by lukecampbell** [comment]
Also, we haven't released a version since 1.0. Not sure who to ask about releases.

**Comment by daf** [comment]
Going to make a 1.1 milestone (prolly 1.2) and assign a few of the remaining issues to it.  I'm still interested in managing the project, however unofficial it currently is.

**Comment by lukecampbell** [comment]
I just released 1.2

**Comment by daf** [comment]
1.0.2 you mean

**Comment by ocefpaf** [comment]
The conda package will be online as soon as we fix a :fire: in the system :wink: 

https://github.com/ioos/conda-recipes/pull/124

BTW ioos/conda-recipes happy to accept PRs when new release are issued.

**Comment by abirger** [comment]
@daf , I don't know what @rsignell-usgs included in the 1.0.1 release but I am sure that he has not published it with binstar:

```
compliance-checker        1.0.0                    py27_0  
(compliance_checker)ioos@ioos-VirtualBox ~/anaconda $ binstar search compliance-checker
Using binstar api site https://api.binstar.org
Run 'binstar show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     IOOS/compliance-checker   |    1.0.0 | conda           | linux-64, osx-64
                                          : Checks Datasets and SOS endpoints for standards compliance
     pypi/compliance-checker   |    1.0.0 | pypi            |                
                                          : Checks Datasets and SOS endpoints for standards compliance
     rsignell/compliance-checker |    1.0.0 | conda           | linux-64       
                                          : Checks Datasets and SOS endpoints for standards compliance
Found 3 packages
```

**Comment by abirger** [comment]
@daf , @lukecampbell , @ocefpaf , it looks like the compliance-checker has been updated in a number of binstar channels. Which one of them would be the "official" channel to look for the checker updates?

```
$ binstar search compliance-checker
Using binstar api site https://api.binstar.org
Run 'binstar show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     IOOS-RHEL6/compliance-checker |    1.0.2 | conda           | linux-64       
                                          : Checks Datasets and SOS endpoints for standards compliance
     IOOS/compliance-checker   |    1.0.2 | conda           | linux-64, osx-64
                                          : Checks Datasets and SOS endpoints for standards compliance
     ocefpaf/compliance-checker |    1.0.2 | conda           | osx-64         
                                          : Checks Datasets and SOS endpoints for standards compliance
     pypi/compliance-checker   |    1.0.0 | pypi            |                
                                          : Checks Datasets and SOS endpoints for standards compliance
     tarankalra/compliance-checker |    1.0.2 | conda           | osx-64         
                                          : Checks Datasets and SOS endpoints for standards compliance
Found 5 packages
```

**Comment by daf** [comment]
@abirger the official one is/should be IOOS.

**Comment by ocefpaf** [comment]
@abirger I recommend you to use the `IOOS` channels.  The `IOOS-RHEL` is for old Linux systems (Centos, Red Hat Enterprise Linux, etc) the other one has Linux, Windows32 and 64, and MacOS.

Ignore the user channels like mine and @tarankalra's channel.  They are only for tests before we upload to the main IOOS channel.
