### ISSUE TITLE
CF: unreasonable error on dimensionless variable of type char

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#985]
**Version of compliance checker running:** current master (e.g. at 799bf15318)

**Describe the checker this affects:**
CF-1.6 (presumably also 1.7 and 1.8)

**Attach a minimal CDL or NetCDF file which is able to reproduce the issue**
```
netcdf char_container_var {
dimensions:
        TIME = 918254 ;
variables:
        char PLATFORM ;
                PLATFORM:trans_system_id = "Irridium" ;
                PLATFORM:positioning_system = "GPS" ;
                PLATFORM:platform_type = "Seaglider 1kA" ;
                PLATFORM:long_name = "Platform information" ;
        char DEPLOYMENT ;
                DEPLOYMENT:deployment_start_date = "2018-03-19-T23:03:11Z" ;
                DEPLOYMENT:deployment_start_latitude = -27.2662 ;
                DEPLOYMENT:deployment_start_longitude = 153.7137 ;
                DEPLOYMENT:long_name = "Deployment information" ;
}
```

**To Reproduce:**
Running the `cf:1.6` check suite results in these errors:
```
§2.2 Data Types
* The fixed-length string variable PLATFORM must be one or two-dimensional, current length is 0
* The fixed-length string variable DEPLOYMENT must be one or two-dimensional, current length is 0
```

**Describe the issue below:**
It seems common practice to use "container variables" to group together attributes that logically belong together, as in the CDL above (another example is a _grid mapping variable_, as described in [CF](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#terminology)). Such variables don't contain any data, so they can be dimensionless and the type doesn't matter. 

I don't see anything in the CF-1.6 convention (or even later versions) that says variables of type `char` must be 1 or 2 dimensional. The section (2.2)  of the [conformance document](http://cfconventions.org/Data/cf-documents/requirements-recommendations/requirements-recommendations-1.6.html) cited in the error messages says:
> CF **attributes** that take string values must be 1D character arrays.

I don't fully understand what this is trying to say, but it's not referring to variables.

**Comment by mhidas** [comment]
I can see this check was added recently in #961 - sorry I missed it, otherwise I would have pointed this out back then.

**Comment by benjwadams** [comment]
Oops, we misinterpreted that section. Will revert and see if I can create appropriate behavior for attributes.  I have reopened the referring issues as well.  Underneath the hood, my understanding is that attributes are arrays of some type anyhow, but I haven't really tried creating > one-dimensional attributes before.

**Comment by mhidas** [comment]
:+1: Reverting #961 works for me. Happy for this issue to be closed.

**Comment by benjwadams** [comment]
I'll close this, but may want to revisit the section that has the attributes, although I don't know what a two-dimensional string attribute would look like.
